import { choice, cloze, mcq } from "../question-helpers";
import type { Question } from "../types";

export const coreQuestions: Question[] = [
  mcq({
    id: "art-01",
    skillId: "articles",
    difficulty: 1,
    level: "A1",
    prompt: "Valitse oikea vaihtoehto.",
    sentence: "I have ___ dog.",
    choices: [
      choice("a", "a"),
      choice("an", "an", "An tulee vokaaliäänteen eteen. Dog alkaa konsonantilla."),
      choice("the", "the", "The viittaa tiettyyn, jo tunnettuun koiraan. Koira mainitaan tässä ensimmäistä kertaa."),
      choice("zero", "— ei artikkelia", "Yksiköllinen laskettava sana tarvitsee artikkelin."),
    ],
    answer: "a",
    fill: "a",
    rule: "Yksi uusi, laskettava asia saa a:n, jos sana alkaa konsonanttiäänteellä.",
    why: "Koira mainitaan ensimmäistä kertaa ja sitä on yksi. Dog ääntyy konsonantilla, joten a dog.",
    example: "I have a cat. She bought a book.",
    trap: "Suomeksi sanotaan ”minulla on koira” ilman pientä sanaa edessä. Englannissa se pieni sana on pakollinen.",
  }),
  mcq({
    id: "art-02",
    skillId: "articles",
    difficulty: 1,
    level: "A1",
    prompt: "Valitse oikea vaihtoehto.",
    sentence: "She ate ___ apple.",
    choices: [
      choice("a", "a", "A tulee konsonanttiäänteen eteen. Apple alkaa vokaaliäänteellä."),
      choice("an", "an"),
      choice("the", "the", "Omenaa ei ole vielä yksilöity."),
      choice("zero", "— ei artikkelia", "Yksikkö apple tarvitsee artikkelin."),
    ],
    answer: "an",
    fill: "an",
    rule: "An tulee, kun seuraava sana alkaa vokaaliäänteellä: a, e, i, o, u.",
    why: "Apple alkaa vokaaliäänteellä /æ/, ja omena on yksi uusi kappale. Siksi an apple.",
    example: "an egg, an idea, an umbrella",
    trap: "Ratkaisee äänne, ei aina kirjain. Siksi seuraavat tehtävät tuntuvat poikkeuksilta.",
  }),
  mcq({
    id: "art-03",
    skillId: "articles",
    difficulty: 2,
    level: "A2",
    prompt: "Valitse oikea vaihtoehto.",
    sentence: "We waited for ___ hour.",
    choices: [
      choice("a", "a", "Hour kirjoitetaan h:lla, mutta h ei äänny. Alku on vokaaliäänne."),
      choice("an", "an"),
      choice("the", "the", "Tässä ei tarkoiteta tiettyä sovittua tuntia."),
      choice("zero", "— ei artikkelia", "Hour on yksiköllinen laskettava sana."),
    ],
    answer: "an",
    fill: "an",
    rule: "Artikkeli valitaan ääntämyksen mukaan. Hiljainen h käyttäytyy kuin vokaali.",
    why: "Hour ääntyy /aʊə/: ensimmäinen äänne on vokaali, vaikka kirjain on h. Siksi an hour.",
    example: "an honest answer, an heir. Vertaa: a house, koska siinä h ääntyy.",
    trap: "Kirjaimen tuijottaminen vie harhaan. Sano sana ääneen.",
  }),
  mcq({
    id: "art-04",
    skillId: "articles",
    difficulty: 3,
    level: "B1",
    prompt: "Valitse oikea vaihtoehto.",
    sentence: "She wants to study at ___ university in Scotland.",
    choices: [
      choice("a", "a"),
      choice("an", "an", "University alkaa kirjaimella u, mutta äänne on /j/ kuten sanassa you."),
      choice("the", "the", "Yliopistoa ei ole vielä nimetty."),
      choice("zero", "— ei artikkelia", "Yksikkö university tarvitsee artikkelin."),
    ],
    answer: "a",
    fill: "a",
    rule: "Jos u ääntyy /juː/, edellä on a, koska ensimmäinen äänne on konsonantti /j/.",
    why: "University alkaa samalla äänteellä kuin you. Ensimmäinen äänne on konsonantti, joten a university.",
    example: "a European city, a useful tip. Mutta: an umbrella, koska alku on /ʌ/.",
    trap: "Vokaalikirjain ei aina tarkoita vokaaliäännettä.",
  }),
  mcq({
    id: "art-05",
    skillId: "articles",
    difficulty: 2,
    level: "A2",
    prompt: "Valitse oikea vaihtoehto.",
    sentence: "___ sun rises in the east.",
    choices: [
      choice("a", "A", "Aurinkoja ei ole monta, joista valittaisiin yksi satunnainen."),
      choice("an", "An", "Sun alkaa konsonantilla, eikä an olisi oikea silloinkaan."),
      choice("the", "The"),
      choice("zero", "— ei artikkelia", "Ainutlaatuinen asia saa the-artikkelin."),
    ],
    answer: "the",
    fill: "The",
    rule: "Ainutlaatuinen asia, jota on vain yksi, saa the-artikkelin.",
    why: "Aurinkoja on yksi ja kaikki tietävät mistä puhutaan. Siksi the sun. Samoin the moon ja the sky.",
    example: "The earth moves around the sun.",
    trap: "Suomessa ”aurinko nousee” ilman artikkelia. Englannissa ainutlaatuisuus merkitään the-sanalla.",
  }),
  mcq({
    id: "art-06",
    skillId: "articles",
    difficulty: 3,
    level: "B1",
    prompt: "Valitse oikea vaihtoehto.",
    sentence: "My brother plays ___ piano.",
    choices: [
      choice("a", "a", "Soittimesta puhuttaessa taito ilmaistaan the-artikkelilla, ei yhdellä pianolla."),
      choice("an", "an", "Piano alkaa konsonantilla."),
      choice("the", "the"),
      choice("zero", "— ei artikkelia", "Soittimen edestä the puuttuu usein suomalaiselta kirjoittajalta."),
    ],
    answer: "the",
    fill: "the",
    rule: "Soittimista käytetään the-artikkelia, kun puhutaan soittotaidosta.",
    why: "Play the piano tarkoittaa, että hän osaa soittaa pianoa. Kyse ei ole yhdestä uudesta esineestä.",
    example: "She plays the violin. He plays the guitar.",
    trap: "Urheilulajit ovat päinvastaisia: play football, ilman artikkelia.",
  }),
  mcq({
    id: "art-07",
    skillId: "articles",
    difficulty: 3,
    level: "B1",
    prompt: "Valitse oikea vaihtoehto.",
    sentence: "The children go to ___ school by bus.",
    choices: [
      choice("a", "a", "A school olisi joku koulu rakennuksena, ei oppilaana olemista."),
      choice("the", "the", "The school korostaisi tiettyä rakennusta, esimerkiksi vanhempien vierailua."),
      choice("zero", "— ei artikkelia"),
    ],
    answer: "zero",
    fill: "",
    rule: "School, home, work ja bed ovat ilman artikkelia, kun puhutaan niiden käytöstä eikä rakennuksesta.",
    why: "Lapset menevät kouluun oppilaina. Silloin englannissa sanotaan go to school. Go to the school tarkoittaisi matkaa siihen rakennukseen jotain muuta varten.",
    example: "She's at home. Dad is at work. I go to bed at ten.",
    trap: "Suomen ”kouluun” ei kerro, pitääkö englannissa olla the. Ratkaisee se, mennäänkö sinne käyttäjäksi.",
  }),
  mcq({
    id: "art-08",
    skillId: "articles",
    difficulty: 4,
    level: "B2",
    prompt: "Valitse oikea vaihtoehto.",
    sentence: "We travelled to ___ Netherlands in June.",
    choices: [
      choice("a", "a", "Maan nimi ei saa a-artikkelia."),
      choice("the", "the"),
      choice("zero", "— ei artikkelia", "Useimmat maat ovat ilman artikkelia, mutta monikolliset nimet ovat poikkeus."),
    ],
    answer: "the",
    fill: "the",
    rule: "Monikolliset ja jotkin yhdysnimet saavat the-artikkelin: the Netherlands, the United States. Useimmat maat eivät.",
    why: "Netherlands on muodoltaan monikko, ja nimen vakiintunut asu on the Netherlands. Finland, Sweden ja France ovat ilman artikkelia.",
    example: "I live in Finland. She moved to the United Kingdom.",
    trap: "Yksi sääntö ”maiden edessä ei ole artikkelia” jättää monikolliset nimet huomiotta.",
  }),

  mcq({
    id: "pre-01",
    skillId: "present",
    difficulty: 1,
    level: "A1",
    prompt: "Valitse verbin oikea muoto.",
    sentence: "She ___ in a bank.",
    choices: [
      choice("work", "work", "He, she ja it tarvitsevat -s-päätteen present simpleen."),
      choice("works", "works"),
      choice("working", "working", "Pelkkä -ing ei ole verbin muoto. Tarvitaan myös be."),
      choice("is-work", "is work", "Is ja perusmuoto eivät muodosta preesensiä."),
    ],
    answer: "works",
    fill: "works",
    rule: "Present simple, he/she/it: verbiin tulee -s.",
    why: "She on yksikön kolmas persoona, ja lause kertoo pysyvän työn. Siksi works.",
    example: "He lives in Tampere. It rains a lot.",
    trap: "Suomessa verbi ei muutu subjektin she takia. Englannissa -s on pakollinen.",
  }),
  mcq({
    id: "pre-02",
    skillId: "present",
    difficulty: 2,
    level: "A2",
    prompt: "Valitse verbin oikea muoto.",
    sentence: "Look! The bus ___.",
    choices: [
      choice("comes", "comes", "Comes kertoisi aikataulusta tai tottumuksesta, ei siitä mitä tapahtuu juuri nyt."),
      choice("come", "come", "Yksikkö the bus ei saa perusmuotoa."),
      choice("is-coming", "is coming"),
      choice("came", "came", "Came on mennyt aika. Look! osoittaa nykyhetkeen."),
    ],
    answer: "is-coming",
    fill: "is coming",
    rule: "Look, listen ja right now viittaavat siihen, että teko on käynnissä: be + -ing.",
    why: "Look! pyytää katsomaan parhaillaan tapahtuvaa asiaa. Bussi on saapumassa nyt, joten is coming.",
    example: "Listen! Somebody is singing.",
    trap: "Suomen ”bussi tulee” voi olla sekä aikataulu että juuri nyt. Englannissa ne eroavat.",
  }),
  cloze({
    id: "pre-03",
    skillId: "present",
    difficulty: 2,
    level: "A2",
    prompt: "Kirjoita kieltomuoto. Verbi on like.",
    sentence: "I ___ coffee.",
    answer: "don't like",
    accept: ["do not like", "dont like"],
    fill: "don't like",
    rule: "Present simplen kielto: don't tai doesn't + verbin perusmuoto.",
    why: "Subjekti on I, joten apuverbi on don't. Like pysyy perusmuodossa: I don't like coffee.",
    example: "They don't live here. He doesn't like tea.",
    trap: "I not like ja I don't like coffee eivät toimi. Kielto tarvitsee do-apuverbin.",
  }),
  mcq({
    id: "pre-04",
    skillId: "present",
    difficulty: 2,
    level: "A2",
    prompt: "Mikä kysymys on oikein?",
    choices: [
      choice("a", "Does she works here?", "Does vie -s-päätteen. Pääverbi jää perusmuotoon."),
      choice("b", "Does she work here?"),
      choice("c", "Do she work here?", "She käyttää does-muotoa, ei do."),
      choice("d", "Works she here?", "Englannin kysymys ei käännä pääverbiä subjektin eteen."),
    ],
    answer: "b",
    rule: "Kysymyksessä does + perusmuoto. -s ei jää pääverbiin.",
    why: "She vaatii does-apuverbin. Works menettää -s:n, koska does kantaa sen: Does she work here?",
    example: "Where does he live? It does not snow here.",
    trap: "Kun -s on jo sanassa does, sitä ei kirjoiteta toiseen kertaan verbiin work.",
  }),
  mcq({
    id: "pre-05",
    skillId: "present",
    difficulty: 3,
    level: "B1",
    prompt: "Valitse oikea lause.",
    choices: [
      choice("a", "Water is boiling at 100 °C.", "Is boiling kuvaisi vettä, joka kiehuu juuri nyt kattilassa."),
      choice("b", "Water boils at 100 °C."),
      choice("c", "Water boil at 100 °C.", "Water yksiköllisenä asiana saa -s-päätteen."),
      choice("d", "Water does boils at 100 °C.", "Does ja -s yhdessä on liikaa."),
    ],
    answer: "b",
    rule: "Yleinen fakta ja luonnonlaki ilmaistaan present simplellä.",
    why: "Kiehumispiste on aina totta, ei vain tällä hetkellä. Siksi Water boils at 100 °C.",
    example: "The sun rises in the east. Ice melts in the sun.",
    trap: "-ing tuntuu ”oikeammalta”, koska ilmiö tapahtuu. Fakta ei silti ole continuous.",
  }),
  mcq({
    id: "pre-06",
    skillId: "present",
    difficulty: 3,
    level: "B1",
    prompt: "Mihin usually kuuluu?",
    choices: [
      choice("a", "She goes usually to bed at ten.", "Taajuusadverbi ei jää verbin ja sen kohteen väliin."),
      choice("b", "She usually goes to bed at ten."),
      choice("c", "She goes to usually bed at ten.", "Usually ei voi katkaista ilmaisua to bed."),
      choice("d", "She goes to bed at usually ten.", "Usually ei määritä kellonaikaa."),
    ],
    answer: "b",
    rule: "Usually, often ja never tulevat present simple -pääverbin eteen.",
    why: "Taajuusadverbin peruspaikka on subjektin ja pääverbin välissä: She usually goes.",
    example: "I often walk to school. He never drinks milk.",
    trap: "Suomessa ”yleensä” voi seistä alussa tai lopussa. Englannissa keskipaikka on varmin.",
  }),
  mcq({
    id: "pre-07",
    skillId: "present",
    difficulty: 4,
    level: "B1",
    prompt: "Valitse verbin oikea muoto.",
    sentence: "The train ___ at 8 every morning.",
    choices: [
      choice("leaves", "leaves"),
      choice("is-leaving", "is leaving", "Every morning kertoo aikataulusta, ei yhdestä käynnissä olevasta lähdöstä."),
      choice("will-leave", "will leave", "Aikataulu ei tarvitse will-muotoa."),
      choice("leave", "leave", "The train on yksikkö."),
    ],
    answer: "leaves",
    fill: "leaves",
    rule: "Aikataulut ja ohjelmat käyttävät present simpleä, vaikka tapahtuma on edessäpäin.",
    why: "Juna lähtee joka aamu kahdeksalta. Se on aikataulu, joten leaves.",
    example: "The film starts at 19:00. School finishes at two.",
    trap: "Tuleva aika houkuttelee will-muotoon. Junan lähtöaika on silti present simple.",
  }),
  mcq({
    id: "pre-08",
    skillId: "present",
    difficulty: 5,
    level: "B2",
    prompt: "Valitse luontevin muoto.",
    sentence: "He ___ his keys. It drives me mad.",
    choices: [
      choice("always-loses", "always loses", "Always loses on neutraali fakta. Jatkossa ärsytys kuuluu sävyyn."),
      choice("is-always-losing", "is always losing"),
      choice("always-is-losing", "always is losing", "Always tulee be-verbin jälkeen."),
      choice("is-lose", "is always lose", "Continuous tarvitsee -ing-muodon."),
    ],
    answer: "is-always-losing",
    fill: "is always losing",
    rule: "Always + present continuous kuvaa ärsyttävää, toistuvaa tapaa.",
    why: "It drives me mad kertoo, että tapa harmittaa. Siksi is always losing, ei pelkkä loses.",
    example: "She is always interrupting. You are always forgetting your pass.",
    trap: "Always ei automaattisesti valitse simple-muotoa. Sävyn kanssa se voi ottaa -ing-muodon.",
  }),

  mcq({
    id: "past-01",
    skillId: "past",
    difficulty: 1,
    level: "A2",
    prompt: "Valitse verbin oikea muoto.",
    sentence: "I ___ that film yesterday.",
    choices: [
      choice("saw", "saw"),
      choice("have-seen", "have seen", "Yesterday on päättynyt aika. Present perfect ei sovi sen kanssa."),
      choice("seen", "seen", "Seen tarvitsee apuverbin, eikä sekään sopisi sanaan yesterday."),
      choice("see", "see", "Yesterday vaatii menneen ajan."),
    ],
    answer: "saw",
    fill: "saw",
    rule: "Yesterday, last year ja in 2019 ovat päättynyttä aikaa: past simple.",
    why: "Eilen on ohi. Elokuvan katsominen sijoittuu suljettuun hetkeen, joten saw.",
    example: "She called me last night. We met in 2019.",
    trap: "Suomen perfekti ”olen nähnyt eilen” ei siirry englantiin. Yesterday katkaisee present perfectin.",
  }),
  mcq({
    id: "past-02",
    skillId: "past",
    difficulty: 2,
    level: "A2",
    prompt: "Valitse verbin oikea muoto.",
    sentence: "I ___ here since 2020.",
    choices: [
      choice("live", "live", "Since vaatii yhteyden menneestä tähän hetkeen, eli perfectin."),
      choice("lived", "lived", "Lived sopisi, jos asuminen olisi jo päättynyt eikä lauseessa olisi since."),
      choice("have-lived", "have lived"),
      choice("am-living", "am living", "Since-alkuhetki ilmaistaan present perfectillä."),
    ],
    answer: "have-lived",
    fill: "have lived",
    rule: "Since + aloituspiste, ja tilanne jatkuu yhä: have/has + partisiippi.",
    why: "Asuminen alkoi 2020 ja puhuja asuu yhä täällä. Since 2020 pakottaa muotoon have lived.",
    example: "She has worked here since May. I have known him since school.",
    trap: "Suomessa ”asun täällä vuodesta 2020” voi näyttää preesensiltä. Englannissa se on have lived.",
  }),
  mcq({
    id: "past-03",
    skillId: "past",
    difficulty: 2,
    level: "A2",
    prompt: "Valitse oikea sana.",
    sentence: "She has studied English ___ six years.",
    choices: [
      choice("for", "for"),
      choice("since", "since", "Since kertoo aloituspisteen, kuten since 2019. Six years on kesto."),
      choice("from", "from", "From ei ole perfectin keston prepositio."),
      choice("during", "during", "During viittaa jakson sisällä tapahtumiseen, ei keston mittaan."),
    ],
    answer: "for",
    fill: "for",
    rule: "For + kesto. Since + hetki, jolloin asia alkoi.",
    why: "Six years on ajan määrä, ei kalenterin kohta. Siksi for six years. Since sopisi muotoon since 2019.",
    example: "I have waited for twenty minutes. I have waited since noon.",
    trap: "Suomen ”kuusi vuotta” ja ”vuodesta 2019” näyttävät samanlaisilta. Englanti erottaa for ja since.",
  }),
  mcq({
    id: "past-04",
    skillId: "past",
    difficulty: 3,
    level: "B1",
    prompt: "Mikä kysymys sopii, kun halutaan tietää elämänkokemuksesta?",
    choices: [
      choice("a", "Did you ever eat sushi?", "Did rajaisi kokemuksen päättyneeseen aikaan."),
      choice("b", "Have you ever eaten sushi?"),
      choice("c", "Have you ever eat sushi?", "Ever-kysymys tarvitsee partisiipin eaten."),
      choice("d", "Do you ever eaten sushi?", "Do ja eaten eivät kuulu samaan rakenteeseen."),
    ],
    answer: "b",
    rule: "Kokemus tähän asti, ilman päättynyttä aikaa: Have you ever + partisiippi.",
    why: "Ever kysyy, onko näin käynyt joskus elämän aikana. Eat on epäsäännöllinen, joten eaten.",
    example: "Have you ever been to Rovaniemi?",
    trap: "Did you ever eat kuuluu korvaan, mutta koulumuoto kokemukselle on present perfect.",
  }),
  mcq({
    id: "past-05",
    skillId: "past",
    difficulty: 3,
    level: "B1",
    prompt: "Valitse luontevin muoto.",
    sentence: "I ___ my keys. I can't get in.",
    choices: [
      choice("lost", "lost", "Lost yksin ei kerro, että ongelma on yhä käsillä, ellei aikaa rajata."),
      choice("have-lost", "have lost"),
      choice("have-been-losing", "have been losing", "Avaimia ei hukata jatkuvana prosessina tässä."),
      choice("lose", "lose", "Hukkaaminen on jo tapahtunut."),
    ],
    answer: "have-lost",
    fill: "have lost",
    rule: "Present perfect sopii, kun mennyt teko näkyy nykyhetken tuloksena.",
    why: "Avaimet ovat hukassa nyt, ja siksi puhuja ei pääse sisään. Tuloksen takia have lost.",
    example: "She has broken her arm. It hurts.",
    trap: "Jos lisäät yesterday, muoto vaihtuu: I lost my keys yesterday.",
  }),
  mcq({
    id: "past-06",
    skillId: "past",
    difficulty: 3,
    level: "B1",
    prompt: "Valitse verbin oikea muoto.",
    sentence: "I ___ in Oulu in 2019.",
    choices: [
      choice("lived", "lived"),
      choice("have-lived", "have lived", "In 2019 on päättynyt vuosi."),
      choice("had-lived", "had lived", "Past perfect vaatisi toisen, myöhemmän menneen tapahtuman."),
      choice("live", "live", "Vuosi 2019 on mennyttä."),
    ],
    answer: "lived",
    fill: "lived",
    rule: "Kalenterivuosi, joka on ohi, rajaa tapahtuman past simpleen.",
    why: "2019 on päättynyt. Asuminen sijoittuu suljettuun jaksoon, joten lived, vaikka asuminen olisi kestänyt pitkään.",
    example: "We were in Rome in July. She worked there in 2018.",
    trap: "Pitkä kesto ei itsessään tee perfectiä. Ratkaisee se, jatkuuko jakso.",
  }),
  mcq({
    id: "past-07",
    skillId: "past",
    difficulty: 4,
    level: "B1",
    prompt: "Valitse verbin oikea muoto.",
    sentence: "I ___ her for ten years.",
    choices: [
      choice("know", "know", "For ten years ja yhä jatkuva tunteminen vaativat perfectin."),
      choice("have-known", "have known"),
      choice("have-been-knowing", "have been knowing", "Know ei yleensä käytä -ing-muotoa."),
      choice("knew", "knew", "Knew tarkoittaisi, että tunteminen on päättynyt."),
    ],
    answer: "have-known",
    fill: "have known",
    rule: "Know, like ja be pitävät present perfectissä partisiipin ilman -ing-muotoa.",
    why: "Tunteminen alkoi kymmenen vuotta sitten ja jatkuu. Know on tilaverbi: have known, ei have been knowing.",
    example: "I have been here for an hour. She has had that bike for years.",
    trap: "For-kesto houkuttelee been + -ing -muotoon. Know ei taivu siihen.",
  }),
  mcq({
    id: "past-08",
    skillId: "past",
    difficulty: 5,
    level: "B2",
    prompt: "Valitse verbin oikea muoto.",
    sentence: "When we arrived, the film ___ already ___.",
    choices: [
      choice("started", "started", "Started jättäisi järjestyksen epäselväksi. Elokuva ehti alkaa ennen saapumista."),
      choice("has-started", "has started", "Has started linkittää nykyhetkeen. Molemmat tapahtumat ovat menneisyydessä."),
      choice("had-started", "had started"),
      choice("was-starting", "was starting", "Already kertoo, että alku oli jo tapahtunut, ei vasta alkamassa."),
    ],
    answer: "had-started",
    fill: "had started",
    rule: "Kun kaksi mennyttä tapahtumaa ovat peräkkäin, aiempi on past perfect: had + partisiippi.",
    why: "Saapuminen on past simple (arrived). Elokuva ehti alkaa sitä ennen, joten had already started.",
    example: "I had finished dinner when she called.",
    trap: "Suomessa pluskvamperfekti jää helposti pois. Englannissa had kertoo, kumpi oli ensin.",
  }),

  mcq({
    id: "fut-01",
    skillId: "future",
    difficulty: 2,
    level: "A2",
    prompt: "Valitse luontevin muoto.",
    sentence: "I think it ___ tomorrow.",
    choices: [
      choice("rains", "rains", "I think + arvaus tulevasta käyttää will-muotoa, ei aikataulun preesensiä."),
      choice("will-rain", "will rain"),
      choice("is-raining", "is raining", "Is raining olisi käynnissä nyt."),
      choice("rain", "rain", "It ei saa pelkkää perusmuotoa."),
    ],
    answer: "will-rain",
    fill: "will rain",
    rule: "Arvaus ja mielipide tulevasta: I think + will.",
    why: "Puhuja arvaa huomisen sään. Siitä ei ole sovittua aikataulua eikä näkyvää merkkiä, joten will rain.",
    example: "I think she will like the gift.",
    trap: "Think ei itsessään ole futuuri. Tuleva arvaus tarvitsee silti will-muodon.",
  }),
  mcq({
    id: "fut-02",
    skillId: "future",
    difficulty: 2,
    level: "A2",
    prompt: "Valitse luontevin muoto.",
    sentence: "Look at those clouds. It ___.",
    choices: [
      choice("will-rain", "will rain", "Will on pelkkä arvaus. Pilvet ovat jo näkyvä todiste."),
      choice("going-to", "is going to rain"),
      choice("rains", "rains", "Rains olisi yleinen fakta, ei tämä sadepilvi."),
      choice("is-rain", "is rain", "Rakenne be going to tarvitsee going to ja verbin."),
    ],
    answer: "going-to",
    fill: "is going to rain",
    rule: "Kun merkki näkyy jo, ennuste on be going to.",
    why: "Pilvet ovat todiste. Puhuja ei arvaile tyhjästä, joten is going to rain.",
    example: "Watch out! You're going to drop the glass.",
    trap: "Will ja going to eivät ole sama ennuste. Going to nojaa merkkiin tai aiempaan päätökseen.",
  }),
  mcq({
    id: "fut-03",
    skillId: "future",
    difficulty: 3,
    level: "B1",
    prompt: "Valitse luontevin muoto.",
    sentence: "The doorbell is ringing. I ___ it.",
    choices: [
      choice("get", "get", "Tarvitaan futuuri, koska teko alkaa vasta nyt tehdystä päätöksestä."),
      choice("ll-get", "I'll get"),
      choice("getting", "I'm getting", "Ovipuhelimeen vastaamista ei ole sovittu etukäteen."),
      choice("going", "I'm going to get", "Going to sopisi aiempaan suunnitelmaan. Päätös syntyy tässä hetkessä."),
    ],
    answer: "ll-get",
    fill: "I'll get",
    rule: "Päätös, joka syntyy puhehetkellä: will.",
    why: "Kello soi nyt, ja puhuja päättää samalla sekunnilla vastata. Siksi I'll get it.",
    example: "It's cold. I'll close the window.",
    trap: "Going to kuulostaa harjoitellulta, mutta se on liian suunniteltu tähän tilanteeseen.",
  }),
  mcq({
    id: "fut-04",
    skillId: "future",
    difficulty: 3,
    level: "B1",
    prompt: "Valitse luontevin muoto.",
    sentence: "We ___ Tom at six. The table is booked.",
    choices: [
      choice("meet", "meet", "Aikataulu ilman järjestelyä olisi simple. Pöytävaraus tekee tästä tapaamisen."),
      choice("will-meet", "will meet", "Will ei kerro, että aika on jo sovittu."),
      choice("are-meeting", "are meeting"),
      choice("meeting", "meeting", "Pelkkä -ing puuttuu be-verbin."),
    ],
    answer: "are-meeting",
    fill: "are meeting",
    rule: "Sovittu tapaaminen ihmisten välillä on present continuous.",
    why: "Aika on sovittu ja pöytä varattu. Kyse on järjestelystä, joten are meeting.",
    example: "I'm seeing the dentist on Friday.",
    trap: "Will on mahdollinen, mutta se kadottaa tiedon siitä, että suunnitelma on valmis.",
  }),
  mcq({
    id: "fut-05",
    skillId: "future",
    difficulty: 3,
    level: "B1",
    prompt: "Valitse luontevin muoto.",
    sentence: "The lesson ___ at nine tomorrow.",
    choices: [
      choice("starts", "starts"),
      choice("is-starting", "is starting", "Oppitunnin alkaminen on aikataulu, ei yksityinen sopimus."),
      choice("will-start", "will start", "Virallinen aikataulu ei tarvitse will-muotoa."),
      choice("start", "start", "The lesson on yksikkö."),
    ],
    answer: "starts",
    fill: "starts",
    rule: "Koulun, junan ja elokuvan aikataulu on present simple.",
    why: "Oppitunti alkaa huomenna yhdeksältä, koska lukujärjestys sanoo niin. Siksi starts.",
    example: "The shop opens at 10 tomorrow.",
    trap: "Tomorrow ei automaattisesti tuo will-muotoa.",
  }),
  mcq({
    id: "fut-06",
    skillId: "future",
    difficulty: 2,
    level: "A2",
    prompt: "Valitse luontevin muoto.",
    sentence: "I ___ medicine next year. I've already applied.",
    choices: [
      choice("study", "study", "Next year tarvitsee futuurin ilmaisun."),
      choice("will-study", "will study", "Hakeminen osoittaa, että päätös on tehty aiemmin."),
      choice("going", "am going to study"),
      choice("studying", "am studying", "Am studying sopisi, jos opinnot olisivat jo käynnissä."),
    ],
    answer: "going",
    fill: "am going to study",
    rule: "Aiemmin tehty aikomus tai päätös: be going to.",
    why: "Hakemus on jo lähetetty. Päätös ei synny puhehetkellä, joten am going to study.",
    example: "We're going to move in August. The flat is ready.",
    trap: "Will on kieliopillisesti mahdollinen, mutta se kadottaa aiemman päätöksen.",
  }),
  mcq({
    id: "fut-07",
    skillId: "future",
    difficulty: 4,
    level: "B1",
    prompt: "Mikä lause on oikein?",
    choices: [
      choice("a", "When I will arrive, I call you.", "When-lauseessa ei käytetä will-muotoa."),
      choice("b", "When I arrive, I will call you."),
      choice("c", "When I arrive, I call you.", "Päälause tarvitsee will-muodon, koska soitto on tuleva päätös."),
      choice("d", "When I will arrive, I will call you.", "Will molemmissa osissa on suomalaisille tyypillinen virhe."),
    ],
    answer: "b",
    rule: "Aika- ja ehtolauseessa (when, if, as soon as) käytetään present simpleä. Will tulee päälauseeseen.",
    why: "When I arrive on sivulause. Will siirtyy päälauseeseen: I will call you.",
    example: "I'll text you as soon as I land.",
    trap: "Suomen tulevaisuus molemmissa lauseissa houkuttelee kahta will-muotoa.",
  }),
  mcq({
    id: "fut-08",
    skillId: "future",
    difficulty: 5,
    level: "B2",
    prompt: "Valitse luontevin muoto.",
    sentence: "Don't call at eight. I ___ my homework then.",
    choices: [
      choice("do", "do", "Then viittaa tulevaan kellonaikaan, ei tottumukseen."),
      choice("will-do", "will do", "Will do sanoo, että läksyt tehdään joskus kahdeksan tienoilla, ei että ne ovat kesken."),
      choice("will-be-doing", "will be doing"),
      choice("doing", "am doing", "Am doing olisi nyt, ei kahdeksalta."),
    ],
    answer: "will-be-doing",
    fill: "will be doing",
    rule: "Future continuous kertoo, mitä on kesken tiettynä tulevana hetkenä: will be + -ing.",
    why: "Kahdeksalta läksyt ovat parhaillaan tekeillä. Siksi älä soita. Will be doing.",
    example: "This time tomorrow I will be sitting on a train.",
    trap: "Will + perusmuoto ei näytä, että teko on kesken juuri sillä hetkellä.",
  }),
];
