import { choice, cloze, mcq } from "../question-helpers";
import type { Question } from "../types";

export const patternQuestions: Question[] = [
  mcq({
    id: "prep-01",
    skillId: "prepositions",
    difficulty: 1,
    level: "A1",
    prompt: "Valitse oikea prepositio.",
    sentence: "The test is ___ Monday.",
    choices: [
      choice("in", "in", "In sopii kuukauteen ja vuoteen: in May, in 2026."),
      choice("on", "on"),
      choice("at", "at", "At sopii kellonaikaan: at 9."),
      choice("by", "by", "By tarkoittaisi takarajaa: by Monday, viimeistään maanantaina."),
    ],
    answer: "on",
    fill: "on",
    rule: "Viikonpäivän edessä on on.",
    why: "Monday on viikonpäivä. Päivän edessä prepositio on on.",
    example: "on Friday, on 5 May, on my birthday",
    trap: "Suomen ”maanantaina” ei kerro, onko englannissa in, on vai at.",
  }),
  mcq({
    id: "prep-02",
    skillId: "prepositions",
    difficulty: 2,
    level: "A2",
    prompt: "Valitse oikea prepositio.",
    sentence: "I read ___ the morning.",
    choices: [
      choice("in", "in"),
      choice("on", "on", "On kuuluu päivään, ei päivän osaan morning."),
      choice("at", "at", "At kuuluu kellonaikaan ja sanaan night."),
      choice("to", "to", "To ei ilmaise aikaa tässä."),
    ],
    answer: "in",
    fill: "in",
    rule: "In the morning, in the afternoon, in the evening. Poikkeus: at night.",
    why: "Morning on päivän osa, ja sen kanssa kulkee the sekä in.",
    example: "in the afternoon, in the evening",
    trap: "At the morning kuulostaa järjestelmälliseltä, koska at night on olemassa. Morning ei käytä at-sanaa.",
  }),
  mcq({
    id: "prep-03",
    skillId: "prepositions",
    difficulty: 2,
    level: "A2",
    prompt: "Valitse oikea prepositio.",
    sentence: "The bus leaves ___ night.",
    choices: [
      choice("in", "in", "In the night on mahdollinen, kun tarkoitetaan yön aikana. Vakiintunut ilmaus on at night."),
      choice("on", "on", "On ei sovi sanaan night."),
      choice("at", "at"),
      choice("to", "to", "To ei ilmaise vuorokaudenaikaa."),
    ],
    answer: "at",
    fill: "at",
    rule: "At night ja at kellonaika. Morning, afternoon ja evening käyttävät in-sanaa.",
    why: "Night on poikkeus päivän osien joukossa. Ilmaus on at night, ilman the-artikkelia.",
    example: "at 7 o'clock, at midnight, at night",
    trap: "In the night ja at night eivät ole sama vakiintunut pari kuin in the morning.",
  }),
  mcq({
    id: "prep-04",
    skillId: "prepositions",
    difficulty: 3,
    level: "B1",
    prompt: "Valitse oikea prepositio.",
    sentence: "See you ___ the weekend.",
    choices: [
      choice("at", "at"),
      choice("in", "in", "In the weekend ei ole kummankaan päämurteen muoto."),
      choice("on", "on", "On the weekend on amerikanenglantia. Tässä linja on brittienglanti."),
      choice("by", "by", "By the weekend tarkoittaisi viikonloppuun mennessä."),
    ],
    answer: "at",
    fill: "at",
    rule: "Brittienglannissa at the weekend. Amerikanenglannissa on the weekend.",
    why: "Suomalainen koulu opettaa yleensä brittiläisen muodon at the weekend.",
    example: "What are you doing at the weekend?",
    trap: "On tuntuu loogiselta, koska on Monday on tuttu. Viikonloppu on eri ilmaus.",
  }),
  mcq({
    id: "prep-05",
    skillId: "prepositions",
    difficulty: 3,
    level: "B1",
    prompt: "Valitse oikea prepositio.",
    sentence: "She is good ___ maths.",
    choices: [
      choice("in", "in", "In maths kuvaisi joskus oppiainetta muussa rakenteessa. Good ottaa at-sanan."),
      choice("at", "at"),
      choice("on", "on", "Good on ei ole englantia."),
      choice("of", "of", "Of kuuluu esimerkiksi ilmaisuun afraid of."),
    ],
    answer: "at",
    fill: "at",
    rule: "Good at, bad at ja brilliant at kertovat taidosta.",
    why: "Taito yhdistetään at-prepositioon: good at maths.",
    example: "He is bad at remembering names. She's brilliant at chess.",
    trap: "Suomen ”hyvä matematiikassa” houkuttelee in-prepositioon.",
  }),
  mcq({
    id: "prep-06",
    skillId: "prepositions",
    difficulty: 4,
    level: "B1",
    prompt: "Valitse oikea prepositio.",
    sentence: "We arrived ___ Paris at noon.",
    choices: [
      choice("to", "to", "Arrive ei käytä to-prepositiota. To kuuluu verbiin go."),
      choice("in", "in"),
      choice("at", "at", "At sopii rakennukseen ja pieneen paikkaan: arrive at the station."),
      choice("on", "on", "On ei sovi kaupunkiin."),
    ],
    answer: "in",
    fill: "in",
    rule: "Arrive in a city or country. Arrive at a building, station or event.",
    why: "Paris on kaupunki, joten arrived in Paris. Asemalle saavuttaessa sanottaisiin arrived at the station.",
    example: "They arrived in Japan. She arrived at the hotel.",
    trap: "Go to Paris on oikein, ja siksi arrive to Paris tuntuu samalta. Arrive ei ota to-sanaa.",
  }),
  mcq({
    id: "prep-07",
    skillId: "prepositions",
    difficulty: 3,
    level: "A2",
    prompt: "Valitse oikea ilmaus.",
    sentence: "She goes to work ___ foot.",
    choices: [
      choice("by", "by", "By sopii kulkuneuvoon: by bus, by car. Kävely on poikkeus."),
      choice("on", "on"),
      choice("with", "with", "With foot ei ole ilmaus."),
      choice("in", "in", "In foot ei ole ilmaus."),
    ],
    answer: "on",
    fill: "on",
    rule: "Kulkuneuvon kanssa by: by bus, by car, by train. Kävely on on foot.",
    why: "Foot ei ole ajoneuvo. Vakiintunut ilmaus on on foot.",
    example: "I came by bike, and she came on foot.",
    trap: "By foot kuuluu korvaan, koska by bus on tuttu. Se ei ole vakiintunut muoto.",
  }),
  cloze({
    id: "prep-08",
    skillId: "prepositions",
    difficulty: 4,
    level: "B1",
    prompt: "Kirjoita puuttuva prepositio.",
    sentence: "The result depends ___ the weather.",
    answer: "on",
    accept: ["on"],
    fill: "on",
    rule: "Depend on, interested in, afraid of ja married to kuljettavat oman prepositionsa.",
    why: "Depend ei elä yksin. Sen pari on on: depends on the weather.",
    example: "It depends on you. She is interested in biology.",
    trap: "Suomen ”riippua jostakin” ei kerro englannin prepositiota. Pari pitää muistaa sanana depend on.",
  }),

  mcq({
    id: "cond-01",
    skillId: "conditionals",
    difficulty: 2,
    level: "A2",
    prompt: "Valitse oikea muoto.",
    sentence: "If you heat ice, it ___.",
    choices: [
      choice("melts", "melts"),
      choice("will-melt", "will melt", "Will tekisi tästä tulevan mahdollisuuden. Jään sulaminen on fakta."),
      choice("melt", "melt", "It tarvitsee -s-päätteen."),
      choice("melted", "melted", "Fakta ei ole menneessä ajassa."),
    ],
    answer: "melts",
    fill: "melts",
    rule: "Nollakonditionaali on aina totta: if + present, present.",
    why: "Jää sulaa kuumennettaessa joka kerta. Molemmat puolet ovat present simpleä: heat, melts.",
    example: "If you mix red and blue, you get purple.",
    trap: "Will tuntuu englannin tulevaisuudelta, mutta luonnonlaki ei tarvitse sitä.",
  }),
  mcq({
    id: "cond-02",
    skillId: "conditionals",
    difficulty: 2,
    level: "A2",
    prompt: "Valitse oikea muoto.",
    sentence: "If it rains tomorrow, I ___ at home.",
    choices: [
      choice("stay", "stay", "Päälause tarvitsee will-muodon, kun kyse on tulevasta mahdollisuudesta."),
      choice("will-stay", "will stay"),
      choice("stayed", "stayed", "Stayed tekisi kuvitelman, ei huomisen sään."),
      choice("am-stay", "am stay", "Rakenne ei ole englantia."),
    ],
    answer: "will-stay",
    fill: "will stay",
    rule: "Ykköskonditionaali: if + present, will + perusmuoto.",
    why: "Huominen sade on mahdollinen. Ehto on preesensissä (rains) ja seuraus will-muodossa.",
    example: "If she studies, she will pass.",
    trap: "Suomen konditionaali molemmissa lauseissa ei tarkoita, että englannissa would tulisi kumpaankin.",
  }),
  mcq({
    id: "cond-03",
    skillId: "conditionals",
    difficulty: 3,
    level: "B1",
    prompt: "Mikä lause on oikein?",
    choices: [
      choice("a", "If it will rain, I will stay home.", "If-lauseeseen ei tule will."),
      choice("b", "If it rains, I will stay home."),
      choice("c", "If it rain, I will stay home.", "It tarvitsee muodon rains."),
      choice("d", "If it would rain, I will stay home.", "Would ei tule if-lauseeseen."),
    ],
    answer: "b",
    rule: "Will ja would eivät kuulu if-lauseen sisään ykkös- ja kakkoskonditionaalissa.",
    why: "Ehto on if it rains. Seuraus on I will stay home. Will vain toisessa puoliskossa.",
    example: "If you call, I will answer.",
    trap: "Kaksi will-muotoa on suomalaisen kirjoittajan tavallisin if-virhe.",
  }),
  mcq({
    id: "cond-04",
    skillId: "conditionals",
    difficulty: 3,
    level: "B1",
    prompt: "Valitse huolelliseen kieleen sopiva muoto.",
    sentence: "If I ___ you, I would take the bus.",
    choices: [
      choice("was", "was", "Was on yleinen puheessa. Huolellisessa kielessä kuvitelman be on were."),
      choice("were", "were"),
      choice("am", "am", "Am tekisi ehdosta nykyisen faktan."),
      choice("would-be", "would be", "Would ei tule if-lauseeseen."),
    ],
    answer: "were",
    fill: "were",
    rule: "Kuvitteellinen nykyhetki: if + mennyt muoto, would + perusmuoto. Be on were kaikilla persoonilla.",
    why: "Puhuja ei ole kuulija. Kyse on neuvosta ja kuvitelmasta. Huolellinen muoto on If I were you.",
    example: "If I were rich, I would travel.",
    trap: "Would be if-lauseessa ja was kouluesseessä ovat ne kaksi muotoa, jotka tehtävä haluaa karsia.",
  }),
  mcq({
    id: "cond-05",
    skillId: "conditionals",
    difficulty: 4,
    level: "B1",
    prompt: "Valitse muoto, joka tarkoittaa että hän ei opiskele.",
    sentence: "If she ___ harder, she would pass.",
    choices: [
      choice("studies", "studies", "Studies + will olisi todellinen mahdollisuus."),
      choice("studied", "studied"),
      choice("will-study", "will study", "Will ei tule if-lauseeseen."),
      choice("had-studied", "had studied", "Had studied kuuluu menneeseen katumukseen: would have passed."),
    ],
    answer: "studied",
    fill: "studied",
    rule: "Kakkoskonditionaali kuvaa epätodennäköistä tai epätotta nykyhetkeä: if + past simple, would.",
    why: "Would pass kertoo kuvitelmasta. Ehto on siksi studied, ei studies. Hän ei todellisuudessa opiskele kovemmin.",
    example: "If we left now, we would catch the train. But we are still eating.",
    trap: "Mennyt muoto if-lauseessa ei aina tarkoita mennyttä aikaa. Kakkonen puhuu nykykuvitelmasta.",
  }),
  mcq({
    id: "cond-06",
    skillId: "conditionals",
    difficulty: 3,
    level: "B1",
    prompt: "Valitse sana, joka tarkoittaa if not.",
    sentence: "___ you hurry, you will miss the bus.",
    choices: [
      choice("unless", "Unless"),
      choice("if", "If", "If you hurry kääntäisi merkityksen: jos kiirehdit, myöhästyt."),
      choice("when", "When", "When ei aseta ehtoa."),
      choice("although", "Although", "Although on myönnytys, ei ehto."),
    ],
    answer: "unless",
    fill: "Unless",
    rule: "Unless tarkoittaa if not. Sen jälkeen tulee present, kun seuraus on will.",
    why: "Bussi jää väliin, jos et kiirehdi. Unless you hurry = if you don't hurry.",
    example: "Unless it rains, we'll walk.",
    trap: "Unless-lauseeseen ei lisätä toista kieltoa. Unless you don't hurry on liikaa.",
  }),
  cloze({
    id: "cond-07",
    skillId: "conditionals",
    difficulty: 4,
    level: "B2",
    prompt: "Kirjoita verbin know oikea muoto.",
    sentence: "I wish I ___ the answer.",
    answer: "knew",
    accept: ["knew"],
    fill: "knew",
    rule: "I wish nykyisestä kuvitelmasta käyttää mennyttä muotoa, kuten kakkoskonditionaali.",
    why: "Puhuja ei tiedä vastausta nyt. Wish siirtää verbin menneeseen: I wish I knew.",
    example: "I wish I were taller. I wish we lived closer.",
    trap: "I wish I know ja I wish I would know tuntuvat suomen konditionaalilta. Know taipuu muotoon knew.",
  }),
  mcq({
    id: "cond-08",
    skillId: "conditionals",
    difficulty: 5,
    level: "B2",
    prompt: "Valitse oikea muoto.",
    sentence: "If I ___ about the test, I would have revised.",
    choices: [
      choice("knew", "knew", "Knew + would revise olisi nykykuvitelma, ei mennyttä katumusta."),
      choice("had-known", "had known"),
      choice("would-know", "would know", "Would ei tule if-lauseeseen."),
      choice("have-known", "have known", "Have known linkittää nykyhetkeen. Testi on jo ohi."),
    ],
    answer: "had-known",
    fill: "had known",
    rule: "Kolmoskonditionaali on mennyttä, jota ei voi muuttaa: if + had + partisiippi, would have + partisiippi.",
    why: "Kertaus jäi tekemättä, koska tieto tuli liian myöhään. Molemmat puolet ovat mennyttä: had known, would have revised.",
    example: "If she had left earlier, she would have caught the train.",
    trap: "Would have molemmissa lauseissa on yleinen virhe. If-puoli saa had-muodon.",
  }),

  mcq({
    id: "mod-01",
    skillId: "modals",
    difficulty: 1,
    level: "A1",
    prompt: "Valitse oikea muoto.",
    sentence: "She ___ swim.",
    choices: [
      choice("can", "can"),
      choice("cans", "cans", "Modaali ei saa -s-päätettä."),
      choice("can-to", "can to", "Can-sanan jälkeen ei tule to."),
      choice("can-swims", "can swims", "Modaalin jälkeen verbi on perusmuodossa."),
    ],
    answer: "can",
    fill: "can",
    rule: "Can kertoo taidon tai mahdollisuuden. Sen jälkeen tulee verbin perusmuoto ilman to-sanaa.",
    why: "Uimataito on can swim. She ei lisää s-kirjainta modaaliin.",
    example: "I can drive. They can come tomorrow.",
    trap: "Can to swim jäljittelee rakennetta want to. Can ei ota to-sanaa.",
  }),
  mcq({
    id: "mod-02",
    skillId: "modals",
    difficulty: 2,
    level: "A2",
    prompt: "Valitse neuvoon sopiva sana.",
    sentence: "You ___ see a doctor.",
    choices: [
      choice("should", "should"),
      choice("shouldn't", "shouldn't", "Kielto kääntäisi neuvon päinvastaiseksi."),
      choice("should-to", "should to", "Should-sanan jälkeen ei tule to."),
      choice("musts", "musts", "Must ei saa -s:ää, eikä tehtävä pyydä pakkoa."),
    ],
    answer: "should",
    fill: "should",
    rule: "Should on neuvo. Must on vahvempi velvollisuus.",
    why: "Lääkärissä käynti esitetään tässä neuvona, ei lakina. You should see a doctor.",
    example: "You should sleep more. You should ask the teacher.",
    trap: "Must tuntuu vahvemmalta ja siksi varmemmalta. Neuvo on should.",
  }),
  mcq({
    id: "mod-03",
    skillId: "modals",
    difficulty: 3,
    level: "B1",
    prompt: "Valitse kieltoon sopiva muoto.",
    sentence: "You ___ park here. The sign says no parking.",
    choices: [
      choice("don't-have-to", "don't have to", "Don't have to tarkoittaa, että pakkoa ei ole. Saat silti pysäköidä."),
      choice("mustn't", "mustn't"),
      choice("must-not-to", "must not to", "Must-sanan jälkeen ei tule to."),
      choice("don't-must", "don't must", "Must ei tee kieltoa do-apuverbin kanssa."),
    ],
    answer: "mustn't",
    fill: "mustn't",
    rule: "Mustn't on kielto. Don't have to tarkoittaa, että jotain ei ole pakko tehdä.",
    why: "Kyltti kieltää pysäköinnin. Siksi mustn't, ei don't have to.",
    example: "You mustn't shout in the library.",
    trap: "Suomen ”ei tarvitse” ja ”ei saa” menevät helposti samaan muottiin.",
  }),
  mcq({
    id: "mod-04",
    skillId: "modals",
    difficulty: 3,
    level: "B1",
    prompt: "Valitse muoto, joka tarkoittaa että pakkoa ei ole.",
    sentence: "You ___ come if you are busy.",
    choices: [
      choice("mustn't", "mustn't", "Mustn't kieltäisi tulemisen."),
      choice("don't-have-to", "don't have to"),
      choice("should", "should", "Should neuvoisi tulemaan."),
      choice("can't", "can't", "Can't sanoisi, että tuleminen on mahdotonta."),
    ],
    answer: "don't-have-to",
    fill: "don't have to",
    rule: "Don't have to = ei ole pakko. Mustn't = ei saa.",
    why: "Kiireinen saa jäädä pois. Tulemista ei kielletä, mutta sitä ei vaadita. Don't have to.",
    example: "You don't have to bring food. We already have some.",
    trap: "Mustn't kuulostaa must-sanan kieltolauseelta ja siksi ”ei tarvitse” -käännökseltä. Merkitys on ankarampi.",
  }),
  mcq({
    id: "mod-05",
    skillId: "modals",
    difficulty: 4,
    level: "B1",
    prompt: "Kumpi merkitys lauseella on?",
    sentence: "You don't have to wear a tie.",
    choices: [
      choice("ban", "Solmion käyttäminen on kielletty.", "Kielto olisi mustn't wear a tie."),
      choice("free", "Saat käyttää solmiota, mutta sinun ei ole pakko."),
      choice("advice", "Sinun kannattaisi käyttää solmiota.", "Neuvo olisi should."),
      choice("past", "Et käyttänyt solmiota aiemmin.", "Lause ei ole menneessä ajassa."),
    ],
    answer: "free",
    rule: "Don't have to poistaa velvollisuuden. Se ei kiellä tekoa.",
    why: "Solmio on vapaaehtoinen. Lause ei sano, että solmio olisi kielletty tai suositeltava.",
    example: "You don't have to answer every question.",
    trap: "Have to opitaan sanana pakko, ja sen kielto luetaan vahingossa kielloksi.",
  }),
  mcq({
    id: "mod-06",
    skillId: "modals",
    difficulty: 4,
    level: "B2",
    prompt: "Valitse päättelyyn sopiva muoto.",
    sentence: "The lights are on. She ___ be at home.",
    choices: [
      choice("must", "must"),
      choice("can", "can", "Can be on vain mahdollisuus. Valot tekevät päättelystä varman."),
      choice("mustn't", "mustn't", "Mustn't be tarkoittaisi, että hänen ei pitäisi olla kotona."),
      choice("must-to", "must to", "Must-sanan jälkeen ei tule to."),
    ],
    answer: "must",
    fill: "must",
    rule: "Must + perusmuoto voi olla päättely: tämän täytyy olla totta. Kielteinen päättely on can't.",
    why: "Valot ovat todiste. Puhuja päättelee, että hän on kotona. She must be at home. Jos talo olisi pimeä, päättely olisi She can't be at home.",
    example: "He's smiling. He must be happy. That can't be true.",
    trap: "Must on opetettu vain pakoksi. Todisteen kanssa se on päättely.",
  }),
  mcq({
    id: "mod-07",
    skillId: "modals",
    difficulty: 5,
    level: "B2",
    prompt: "Valitse mennyttä katumusta kuvaava muoto.",
    sentence: "I ___ harder for the test.",
    choices: [
      choice("should-revise", "should revise", "Should revise neuvoo nykyhetkeä tai tulevaa."),
      choice("should-have-revised", "should have revised"),
      choice("must-have-revise", "must have revise", "Partisiippi on revised, ja must have olisi päättely, ei neuvo."),
      choice("should-revised", "should revised", "Should-sanan ja partisiipin väliin kuuluu have."),
    ],
    answer: "should-have-revised",
    fill: "should have revised",
    rule: "Menneen ajan neuvo ja katumus: should have + partisiippi.",
    why: "Koe on ohi ja kertaus jäi tekemättä. Should have revised kertoo, mitä olisi pitänyt tehdä.",
    example: "You should have told me. She shouldn't have left.",
    trap: "Should revised jättää have-sanan pois. Ilman sitä rakenne ei ole mennyttä.",
  }),
  mcq({
    id: "mod-08",
    skillId: "modals",
    difficulty: 2,
    level: "A2",
    prompt: "Mikä lause on oikein?",
    choices: [
      choice("a", "He can to drive.", "Can-sanan jälkeen ei tule to."),
      choice("b", "He can drive."),
      choice("c", "He cans drive.", "Can ei saa -s-päätettä."),
      choice("d", "He can drives.", "Drives ei saa -s:ää modaalin jälkeen."),
    ],
    answer: "b",
    rule: "Modaalin jälkeen verbi on perusmuodossa: can drive, must go, should ask.",
    why: "Can ei taivu eikä ota to-sanaa. Ainoa oikea lause on He can drive.",
    example: "She must leave. We should wait.",
    trap: "Want to, need to ja have to kuljettavat to-sanaa. Can, must ja should eivät.",
  }),

  mcq({
    id: "wo-01",
    skillId: "word-order",
    difficulty: 1,
    level: "A1",
    prompt: "Mikä kysymys on oikein?",
    choices: [
      choice("a", "Where you live?", "Kysymys tarvitsee apuverbin."),
      choice("b", "Where do you live?"),
      choice("c", "Where live you?", "Pääverbi ei käänny subjektin eteen."),
      choice("d", "Where you do live?", "Apuverbi tulee subjektin eteen, ei perään."),
    ],
    answer: "b",
    rule: "Kysymyssana + do/does/did + subjekti + perusmuoto.",
    why: "Live tarvitsee apuverbin do, koska lauseessa ei ole muuta apuverbiä. Järjestys on Where do you live?",
    example: "Where does she work? What do they want?",
    trap: "Suomessa kysymyssana riittää. Englannissa do on pakollinen, jos be-verbiä tai modaalia ei ole.",
  }),
  mcq({
    id: "wo-02",
    skillId: "word-order",
    difficulty: 2,
    level: "A2",
    prompt: "Mikä kysymys on oikein?",
    choices: [
      choice("a", "Does she like coffee?"),
      choice("b", "Does she likes coffee?", "Does vie -s-päätteen."),
      choice("c", "Do she like coffee?", "She käyttää does-muotoa."),
      choice("d", "Likes she coffee?", "Pääverbi ei aloita kysymystä."),
    ],
    answer: "a",
    rule: "Does + subjekti + verbin perusmuoto.",
    why: "She vaatii does. Like pysyy perusmuodossa, koska -s on jo sanassa does.",
    example: "Does it work? Does he know?",
    trap: "Does she likes tuntuu huolelliselta, koska she ja -s on opetettu yhdessä. Kysymyksessä -s siirtyy.",
  }),
  mcq({
    id: "wo-03",
    skillId: "word-order",
    difficulty: 2,
    level: "A2",
    prompt: "Valitse oikea muoto.",
    sentence: "Where ___ last night?",
    choices: [
      choice("you-went", "you went", "Went on väitelauseen muoto. Kysymys tarvitsee did-apuverbin."),
      choice("did-you-go", "did you go"),
      choice("did-you-went", "did you went", "Did vie menneen ajan. Go jää perusmuotoon."),
      choice("went-you", "went you", "Went ei käänny subjektin eteen."),
    ],
    answer: "did-you-go",
    fill: "did you go",
    rule: "Menneen ajan kysymys: did + subjekti + perusmuoto. Ei did + went.",
    why: "Did kertoo menneen ajan. Go ei saa toista mennyttä muotoa. Where did you go last night?",
    example: "Did you see him? What did she say?",
    trap: "Did you went ja did you saw ovat tavallisia, koska menneisyys halutaan näkyviin kahdesti.",
  }),
  mcq({
    id: "wo-04",
    skillId: "word-order",
    difficulty: 3,
    level: "B1",
    prompt: "Mihin never kuuluu?",
    choices: [
      choice("a", "I eat never meat.", "Never ei jää verbin ja objektin väliin."),
      choice("b", "I never eat meat."),
      choice("c", "Never I eat meat.", "Never lauseen alussa vaatisi käännetyn järjestyksen, eikä sekään ole tavallinen."),
      choice("d", "I eat meat never.", "Lauseen loppu on taajuusadverbin heikko paikka."),
    ],
    answer: "b",
    rule: "Never, often ja usually tulevat present simple -pääverbin eteen.",
    why: "Taajuusadverbin paikka on subjektin ja pääverbin välissä: I never eat meat.",
    example: "She often walks. They usually agree.",
    trap: "Suomen ”en koskaan syö” järjestys ei siirry sanan never paikaksi verbin jälkeen.",
  }),
  mcq({
    id: "wo-05",
    skillId: "word-order",
    difficulty: 3,
    level: "B1",
    prompt: "Mikä kysymys on oikein?",
    choices: [
      choice("a", "How long you have lived here?", "Apuverbi have tulee subjektin eteen."),
      choice("b", "How long have you lived here?"),
      choice("c", "How long have you live here?", "Have-perfect tarvitsee partisiipin lived."),
      choice("d", "How long did you have lived here?", "Did ja have perfect yhdessä sekoittavat kaksi aikamuotoa."),
    ],
    answer: "b",
    rule: "Present perfect -kysymys: How long have/has + subjekti + partisiippi.",
    why: "Asuminen jatkuu yhä, joten perfect. Have on apuverbi ja siirtyy subjektin eteen: have you lived.",
    example: "How long has she known him?",
    trap: "How long do you live here on yleinen virhe. Kesto tähän asti on have you lived.",
  }),
  mcq({
    id: "wo-06",
    skillId: "word-order",
    difficulty: 4,
    level: "B1",
    prompt: "Mikä lause on oikein?",
    choices: [
      choice("a", "Can you tell me where is the station?", "Epäsuorassa kysymyksessä be-verbi jää subjektin jälkeen."),
      choice("b", "Can you tell me where the station is?"),
      choice("c", "Can you tell me where the station is it?", "It on ylimääräinen."),
      choice("d", "Can you tell me where does the station is?", "Does ei kuulu be-verbin kysymykseen eikä epäsuoraan kysymykseen."),
    ],
    answer: "b",
    rule: "Epäsuora kysymys käyttää väitelauseen sanajärjestystä.",
    why: "Suora kysymys on Where is the station? Kun se upotetaan lauseeseen, järjestys palautuu: where the station is.",
    example: "Do you know what time it is? I wonder where she lives.",
    trap: "Where is haluaa jäädä tuttuun kysymysjärjestykseen myös tell me -rakenteen sisään.",
  }),
  mcq({
    id: "wo-07",
    skillId: "word-order",
    difficulty: 4,
    level: "B2",
    prompt: "Mikä lause on oikein?",
    choices: [
      choice("a", "I don't know what does she want.", "Epäsuorassa kysymyksessä ei ole does-käännöstä."),
      choice("b", "I don't know what she wants."),
      choice("c", "I don't know what she does want.", "Does want olisi painotus, ei neutraali epäsuora kysymys."),
      choice("d", "I don't know what wants she.", "Verbi ei käänny subjektin eteen."),
    ],
    answer: "b",
    rule: "What, where ja if upotettuna lauseeseen: subjekti + verbi, ilman do-käännöstä.",
    why: "I don't know tekee kysymyksestä epäsuoran. She wants jää väitelauseen järjestykseen, ja -s palaa verbiin koska does poistuu.",
    example: "Tell me if he is at home. I asked what they needed.",
    trap: "Does katoaa, ja siksi -s palaa. What she want ilman -s:ää on toinen tavallinen virhe.",
  }),
  mcq({
    id: "wo-08",
    skillId: "word-order",
    difficulty: 4,
    level: "B1",
    prompt: "Mikä lause on oikein?",
    choices: [
      choice("a", "She speaks very well English.", "Very well ei jää verbin ja objektin väliin."),
      choice("b", "She speaks English very well."),
      choice("c", "She very well speaks English.", "Very well ei ole taajuusadverbi, joka istuisi verbin eteen."),
      choice("d", "She speaks very English well.", "Very ei määritä sanaa English."),
    ],
    answer: "b",
    rule: "Tavan adverbi tulee yleensä objektin jälkeen: verb + object + very well.",
    why: "English on objekti. Very well kertoo miten, ja se siirtyy objektin taakse.",
    example: "He plays the piano beautifully. They did the work carefully.",
    trap: "Suomen ”hyvin englantia” järjestys tuottaa very well English. Englannissa objekti tulee ensin.",
  }),
];
