import { choice, mcq } from "../question-helpers";
import type { Question } from "../types";

export const structureQuestions: Question[] = [
  mcq({
    id: "agr-01",
    skillId: "agreement",
    difficulty: 1,
    level: "A1",
    prompt: "Valitse oikea muoto.",
    sentence: "She ___ tired today.",
    choices: [
      choice("is", "is"),
      choice("are", "are", "Are kuuluu monikolle ja sanalle you."),
      choice("am", "am", "Am kuuluu vain sanaan I."),
      choice("be", "be", "Be on perusmuoto, ei taivutettu verbi."),
    ],
    answer: "is",
    fill: "is",
    rule: "She, he ja it käyttävät muotoa is.",
    why: "She on yksikön kolmas persoona. Olla-verbin muoto on is.",
    example: "He is late. It is cold.",
    trap: "Suomen ”on” ei vaihdu. Englannissa am, is ja are valitaan subjektin mukaan.",
  }),
  mcq({
    id: "agr-02",
    skillId: "agreement",
    difficulty: 2,
    level: "A2",
    prompt: "Valitse oikea muoto.",
    sentence: "There ___ two mistakes in this sentence.",
    choices: [
      choice("is", "is", "Is katsoisi yhtä asiaa. Mistakes on monikko."),
      choice("are", "are"),
      choice("be", "be", "There-lause tarvitsee taivutetun be-verbin."),
      choice("have", "have", "Olemassaolo ilmaistaan there is / there are -rakenteella."),
    ],
    answer: "are",
    fill: "are",
    rule: "There-lauseessa verbi seuraa sitä sanaa, joka tulee sen jälkeen.",
    why: "Two mistakes on monikko, joten are. There is a mistake olisi oikein, jos virheitä olisi yksi.",
    example: "There is a cat outside. There are three cats outside.",
    trap: "There is jää helposti paikalleen, vaikka lista olisi monikossa.",
  }),
  mcq({
    id: "agr-03",
    skillId: "agreement",
    difficulty: 2,
    level: "A2",
    prompt: "Mikä lause on oikein?",
    choices: [
      choice("a", "She don't like coffee.", "She käyttää doesn't-muotoa."),
      choice("b", "She doesn't likes coffee.", "Doesn't vie -s-päätteen. Like jää perusmuotoon."),
      choice("c", "She doesn't like coffee."),
      choice("d", "She not like coffee.", "Kielto tarvitsee apuverbin."),
    ],
    answer: "c",
    rule: "He, she ja it: doesn't + verbin perusmuoto.",
    why: "She vaatii doesn't. Pääverbi like ei saa toista -s:ää.",
    example: "He doesn't live here. It doesn't work.",
    trap: "Don't on tutumpi, ja -s haluaisi jäädä verbiin. Molemmat yhdessä tekevät virheen.",
  }),
  mcq({
    id: "agr-04",
    skillId: "agreement",
    difficulty: 3,
    level: "B1",
    prompt: "Valitse oikea muoto.",
    sentence: "Everyone ___ a pencil.",
    choices: [
      choice("have", "have", "Everyone on kieliopillisesti yksikkö."),
      choice("has", "has"),
      choice("are", "are", "Everyone ei ole monikon be-verbin subjekti."),
      choice("haves", "haves", "Have ei saa -s-päätettä. Yksikkö on has."),
    ],
    answer: "has",
    fill: "has",
    rule: "Everyone, everybody, someone ja each ovat yksikköjä: has, is, does.",
    why: "Everyone tarkoittaa jokaista yhtä ihmistä. Verbi on siksi has, vaikka mielessä olisi koko luokka.",
    example: "Somebody is at the door. Each student has a locker.",
    trap: "Suomeksi ”kaikilla on” tuntuu monikolta. Englannin everyone on silti yksikkö.",
  }),
  mcq({
    id: "agr-05",
    skillId: "agreement",
    difficulty: 3,
    level: "B1",
    prompt: "Valitse oikea muoto.",
    sentence: "The news ___ surprising.",
    choices: [
      choice("is", "is"),
      choice("are", "are", "News päättyy s-kirjaimeen, mutta se on yksikkö."),
      choice("were", "were", "Lause ei ole menneessä ajassa, eikä news ole monikko."),
      choice("be", "be", "Tarvitaan taivutettu muoto."),
    ],
    answer: "is",
    fill: "is",
    rule: "News, mathematics ja physics ovat yksikköjä, vaikka ne päättyvät s-kirjaimeen.",
    why: "News on yksi uutiskokonaisuus, ei monikko. Siksi the news is surprising.",
    example: "Mathematics is my best subject. Physics is hard.",
    trap: "S-pääte ei aina tarkoita monikkoa.",
  }),
  mcq({
    id: "agr-06",
    skillId: "agreement",
    difficulty: 2,
    level: "A2",
    prompt: "Valitse oikea muoto.",
    sentence: "People ___ waiting outside.",
    choices: [
      choice("is", "is", "People on monikko. Yksikkö olisi person."),
      choice("are", "are"),
      choice("be", "be", "Waiting tarvitsee be-verbin taivutetun muodon."),
      choice("am", "am", "Am kuuluu vain sanaan I."),
    ],
    answer: "are",
    fill: "are",
    rule: "People on monikko: people are. Yksi ihminen on a person.",
    why: "People tarkoittaa ihmisiä. Continuous-muoto on are waiting.",
    example: "People are friendly here. A person is waiting.",
    trap: "People näyttää yksiköltä, koska sillä ei ole erillistä s-päätettä.",
  }),
  mcq({
    id: "agr-07",
    skillId: "agreement",
    difficulty: 4,
    level: "B2",
    prompt: "Valitse oikea muoto.",
    sentence: "The number of students ___ rising.",
    choices: [
      choice("is", "is"),
      choice("are", "are", "Are sopisi ilmaisuun a number of students, ei the number of."),
      choice("be", "be", "Rising tarvitsee be-verbin taivutetun muodon."),
      choice("have", "have", "Nouseminen ilmaistaan be + -ing."),
    ],
    answer: "is",
    fill: "is",
    rule: "The number of + monikko käyttää yksikköverbiä, koska pääsana on number.",
    why: "Pääsana on number, yksi luku. Students vain määrittää sitä. Siksi is rising. A number of students are olisi monikko.",
    example: "The number of mistakes is small.",
    trap: "Silmä tarttuu sanaan students ja valitsee monikon. Verbi katsoo sanaa number.",
  }),
  mcq({
    id: "agr-08",
    skillId: "agreement",
    difficulty: 5,
    level: "B2",
    prompt: "Valitse oikea muoto.",
    sentence: "Neither of the answers ___ correct.",
    choices: [
      choice("is", "is"),
      choice("are", "are", "Puhekieli hyväksyy joskus are-muodon, mutta huolellinen muoto on is."),
      choice("be", "be", "Tarvitaan taivutettu muoto."),
      choice("am", "am", "Am ei sovi."),
    ],
    answer: "is",
    fill: "is",
    rule: "Neither of ja either of ottavat yksikköverbin huolellisessa kielessä.",
    why: "Neither tarkoittaa ei kumpaakaan, siis yhtä kerrallaan. Kokeessa ja huolellisessa tekstissä: is correct.",
    example: "Neither of my parents is at home.",
    trap: "Of the answers näyttää monikolta. Neither pitää verbin yksikössä.",
  }),

  mcq({
    id: "pro-01",
    skillId: "pronouns",
    difficulty: 1,
    level: "A1",
    prompt: "Valitse oikea pronomini.",
    sentence: "My sister says ___ is tired.",
    choices: [
      choice("he", "he", "Sister on tyttö tai nainen."),
      choice("she", "she"),
      choice("it", "it", "It viittaa asioihin ja eläimiin, ei sisareen."),
      choice("his", "his", "His on omistusmuoto, ei subjekti."),
    ],
    answer: "she",
    fill: "she",
    rule: "Naisesta tai tytöstä käytetään pronominia she.",
    why: "Sister on nainen. Hän-pronomini on she, ja verbi is sopii siihen.",
    example: "My brother says he is hungry. Anna says she is ready.",
    trap: "Suomen hän ei kerro sukupuolta. Englannissa se pitää valita.",
  }),
  mcq({
    id: "pro-02",
    skillId: "pronouns",
    difficulty: 2,
    level: "A2",
    prompt: "Valitse oikea sana.",
    sentence: "Anna lost ___ bag.",
    choices: [
      choice("she", "she", "She on subjekti, ei omistaja substantiivin edessä."),
      choice("her", "her"),
      choice("hers", "hers", "Hers seisoo yksin: The bag is hers."),
      choice("his", "his", "Anna ei ole he."),
    ],
    answer: "her",
    fill: "her",
    rule: "Substantiivin edessä omistus on her, his, my tai their. Hers ja mine tulevat yksin.",
    why: "Bag tarvitsee määreen. Annan laukku on her bag. Hers bag ei ole englantia.",
    example: "Tom lost his phone. The phone is his.",
    trap: "Her on sekä omistus että objekti. Tässä se on omistus, koska seuraavana tulee bag.",
  }),
  mcq({
    id: "pro-03",
    skillId: "pronouns",
    difficulty: 2,
    level: "A2",
    prompt: "Valitse oikea sana.",
    sentence: "This book is ___.",
    choices: [
      choice("my", "my", "My tarvitsee substantiivin peräänsä: my book."),
      choice("mine", "mine"),
      choice("me", "me", "Me on objekti, ei omistaja."),
      choice("I", "I", "I on subjekti."),
    ],
    answer: "mine",
    fill: "mine",
    rule: "Kun omistettavaa sanaa ei toisteta, käytä mine, yours, hers, ours tai theirs.",
    why: "Book on jo sanottu. Loppuun jää itsenäinen omistusmuoto mine.",
    example: "That seat is yours. The idea was hers.",
    trap: "My book on oikein, mutta my yksin lauseen lopussa ei.",
  }),
  mcq({
    id: "pro-04",
    skillId: "pronouns",
    difficulty: 3,
    level: "B1",
    prompt: "Valitse oikea sana.",
    sentence: "The dog wagged ___ tail.",
    choices: [
      choice("its", "its"),
      choice("it's", "it's", "It's tarkoittaa it is. Tähän tarvitaan omistusmuoto."),
      choice("its'", "its'", "Omistusmuoto its ei käytä heittomerkkiä."),
      choice("his", "his", "Koiran sukupuolta ei ole kerrottu. Eläimestä neutraali omistus on its."),
    ],
    answer: "its",
    fill: "its",
    rule: "Its = sen. It's = it is tai it has.",
    why: "Häntä kuuluu koiralle. Omistus ilman heittomerkkiä on its. It's tail tarkoittaisi it is tail.",
    example: "The company changed its name. It's a new name.",
    trap: "Heittomerkki tuntuu omistukselta, koska suomessa genetiivi merkitään. Its on poikkeus.",
  }),
  mcq({
    id: "pro-05",
    skillId: "pronouns",
    difficulty: 3,
    level: "B1",
    prompt: "Mikä lause on oikein?",
    choices: [
      choice("a", "Between you and I, this is a secret.", "Prepositionin jälkeen tulee objektimuoto me, ei I."),
      choice("b", "Between you and me, this is a secret."),
      choice("c", "Between you and my, this is a secret.", "My on omistus."),
      choice("d", "Between you and mine, this is a secret.", "Mine on itsenäinen omistusmuoto."),
    ],
    answer: "b",
    rule: "Prepositionin jälkeen pronomini on objektimuodossa: me, him, her, us, them.",
    why: "Between on prepositio. I on subjektin muoto, joten se vaihtuu muotoon me.",
    example: "She sat beside him. Give it to us.",
    trap: "You and I on oikein subjektina: You and I are ready. Prepositionin jälkeen sääntö vaihtuu.",
  }),
  mcq({
    id: "pro-06",
    skillId: "pronouns",
    difficulty: 3,
    level: "B1",
    prompt: "Valitse oikea sana.",
    sentence: "The children enjoyed ___.",
    choices: [
      choice("themselves", "themselves"),
      choice("themself", "themself", "Monikon refleksiivi on themselves."),
      choice("themselves'", "theirselves", "Theirselves ei ole englannin sana."),
      choice("them", "them", "Enjoy itseensä viitattaessa tarvitsee refleksiivin."),
    ],
    answer: "themselves",
    fill: "themselves",
    rule: "Kun subjekti ja teon kohde ovat samat, käytä refleksiiviä: myself, yourself, herself, themselves.",
    why: "Lapset viihdyttivät itseään. Children on monikko, joten themselves.",
    example: "I taught myself. She hurt herself.",
    trap: "Them olisi toinen joukko ihmisiä. Themselves kertoo, että kohde on sama kuin subjekti.",
  }),
  mcq({
    id: "pro-07",
    skillId: "pronouns",
    difficulty: 4,
    level: "B1",
    prompt: "Valitse oikea sana.",
    sentence: "A friend of ___ called last night.",
    choices: [
      choice("me", "me", "Of-rakenne käyttää itsenäistä omistusmuotoa, ei objektia."),
      choice("my", "my", "My friend on eri rakenne. Of my ei sovi tähän."),
      choice("mine", "mine"),
      choice("I", "I", "I on subjekti."),
    ],
    answer: "mine",
    fill: "mine",
    rule: "A friend of mine tarkoittaa yhtä ystävääni. Of-sanan jälkeen tulee mine, yours tai hers.",
    why: "Rakenne on vakiintunut: of + itsenäinen omistusmuoto. A friend of mine, ei a friend of me.",
    example: "A neighbour of ours is moving. That joke of yours is old.",
    trap: "Suomen ”ystäväni” kääntyy helposti my friendiksi. Of-rakenne on eri muotti.",
  }),
  mcq({
    id: "pro-08",
    skillId: "pronouns",
    difficulty: 4,
    level: "B2",
    prompt: "Valitse oikea sana.",
    sentence: "She taught ___ to play the guitar.",
    choices: [
      choice("her", "her", "Her tarkoittaisi, että hän opetti jotakuta toista."),
      choice("herself", "herself"),
      choice("she", "she", "She ei voi olla verbin kohde."),
      choice("hers", "hers", "Hers on omistusmuoto."),
    ],
    answer: "herself",
    fill: "herself",
    rule: "Teach, hurt ja enjoy viittaavat itseensä refleksiivillä.",
    why: "Hän oli sekä opettaja että oppilas. Siksi herself, ei her.",
    example: "He cut himself. I introduced myself.",
    trap: "She taught her olisi kieliopillinen, mutta silloin oppilaana olisi joku muu tyttö.",
  }),

  mcq({
    id: "qua-01",
    skillId: "quantifiers",
    difficulty: 1,
    level: "A2",
    prompt: "Valitse oikea sana.",
    sentence: "How ___ apples do we need?",
    choices: [
      choice("much", "much", "Much kuuluu ei-laskettavaan sanaan, kuten water tai money."),
      choice("many", "many"),
      choice("a-lot", "a lot", "How a lot ei ole kysymysrakenne."),
      choice("few", "few", "Few ei sovi how-kysymykseen."),
    ],
    answer: "many",
    fill: "many",
    rule: "How many + laskettava monikko. How much + ei-laskettava sana.",
    why: "Omenoita voi laskea kappaleina. Kysymys on how many apples.",
    example: "How many students are absent? How much sugar is left?",
    trap: "Much ja many eivät vaihdu sen mukaan, onko määrä iso. Ne vaihtuvat sanan laskettavuuden mukaan.",
  }),
  mcq({
    id: "qua-02",
    skillId: "quantifiers",
    difficulty: 1,
    level: "A2",
    prompt: "Valitse oikea sana.",
    sentence: "How ___ water do you drink?",
    choices: [
      choice("many", "many", "Water on ei-laskettava."),
      choice("much", "much"),
      choice("few", "few", "Few kuuluu laskettavaan monikkoon."),
      choice("a-few", "a few", "A few ei sovi how-kysymykseen eikä veteen."),
    ],
    answer: "much",
    fill: "much",
    rule: "Vesi, raha, aika ja maito ovat ei-laskettavia: how much.",
    why: "Water ei taivu monikkoon waters, kun puhutaan määrästä. Siksi how much water.",
    example: "How much time do we have? How much money is left?",
    trap: "Jos lasit voi laskea, kysymys muuttuu: How many glasses of water?",
  }),
  mcq({
    id: "qua-03",
    skillId: "quantifiers",
    difficulty: 2,
    level: "A2",
    prompt: "Valitse luontevin sana.",
    sentence: "Would you like ___ tea?",
    choices: [
      choice("any", "any", "Any on tyypillinen kysymyksissä, mutta tarjous käyttää some-sanaa."),
      choice("some", "some"),
      choice("many", "many", "Tea on tässä ei-laskettava juoma."),
      choice("a", "a", "A tea tarkoittaisi annosta ravintolakielessä, ei tätä tarjousta."),
    ],
    answer: "some",
    fill: "some",
    rule: "Tarjouksissa ja pyynnöissä käytetään some-sanaa, vaikka lause on kysymys.",
    why: "Would you like on tarjous. Puhuja olettaa, että tee kelpaa. Siksi some tea, ei any tea.",
    example: "Can I have some water? Do you want some help?",
    trap: "Sääntö ”kysymyksessä any” pitää paikkansa avoimissa kysymyksissä, ei tarjouksissa.",
  }),
  mcq({
    id: "qua-04",
    skillId: "quantifiers",
    difficulty: 2,
    level: "A2",
    prompt: "Valitse oikea sana.",
    sentence: "There isn't ___ milk in the fridge.",
    choices: [
      choice("some", "some", "Some kuuluu myönteiseen lauseeseen: There is some milk."),
      choice("any", "any"),
      choice("many", "many", "Milk on ei-laskettava."),
      choice("no", "no", "Isn't ja no yhdessä tekisivät kaksoiskiellon."),
    ],
    answer: "any",
    fill: "any",
    rule: "Kieltolauseessa some vaihtuu sanaksi any.",
    why: "Isn't tekee lauseesta kiellon. Maito on ei-laskettava, joten any milk.",
    example: "I don't have any questions. She didn't buy any bread.",
    trap: "Some tuntuu turvalliselta, koska se on tuttu myönteisistä lauseista.",
  }),
  mcq({
    id: "qua-05",
    skillId: "quantifiers",
    difficulty: 3,
    level: "B1",
    prompt: "Valitse oikea vaihtoehto.",
    sentence: "She gave me ___ advice.",
    choices: [
      choice("an", "an advice", "Advice on ei-laskettava. An advice ei ole englantia."),
      choice("some", "some advice"),
      choice("advices", "advices", "Advice ei saa monikon -s:ää."),
      choice("an-advise", "an advise", "Advise on verbi. Substantiivi on advice."),
    ],
    answer: "some",
    fill: "some advice",
    rule: "Advice, information, homework ja luggage ovat ei-laskettavia. Määrä tulee sanasta some tai a piece of.",
    why: "Neuvoa ei lasketa kappaleina sanalla an advice. Oikea muoto on some advice tai a piece of advice.",
    example: "I need some information. There is too much homework.",
    trap: "Suomen ”neuvo” ja ”läksy” tuntuvat laskettavilta. Englannissa ne ovat massasanoja.",
  }),
  mcq({
    id: "qua-06",
    skillId: "quantifiers",
    difficulty: 4,
    level: "B1",
    prompt: "Kumpi sopii, jos ystäviä on muutama ja siitä ollaan iloisia?",
    sentence: "I have ___ friends in this town.",
    choices: [
      choice("few", "few", "Few korostaa, että määrä on harmillisen pieni."),
      choice("a-few", "a few"),
      choice("little", "little", "Little kuuluu ei-laskettavaan sanaan."),
      choice("a-little", "a little", "Friends on laskettava monikko."),
    ],
    answer: "a-few",
    fill: "a few",
    rule: "A few on pieni myönteinen määrä. Few on pieni kielteinen määrä.",
    why: "Tehtävä sanoo, että ystävistä ollaan iloisia. A few friends tarkoittaa, että heitä on joitakin. Few friends tarkoittaisi, ettei heitä juuri ole.",
    example: "Stay a few minutes. Few people understood the joke.",
    trap: "A-kirjain muuttaa sävyn. Se ei ole pelkkä täytesana.",
  }),
  mcq({
    id: "qua-07",
    skillId: "quantifiers",
    difficulty: 4,
    level: "B1",
    prompt: "Valitse muoto, joka tarkoittaa että rahaa on liian vähän.",
    sentence: "I have ___ money, so I can't come.",
    choices: [
      choice("little", "little"),
      choice("a-little", "a little", "A little tarkoittaisi, että rahaa on sentään jonkin verran."),
      choice("few", "few", "Money on ei-laskettava."),
      choice("a-few", "a few", "A few ei sovi sanaan money."),
    ],
    answer: "little",
    fill: "little",
    rule: "Little ja few ovat kielteisiä: määrä ei riitä. A little ja a few ovat myönteisiä.",
    why: "Puhuja ei voi tulla, koska rahaa ei käytännössä ole. Little money kertoo puutteesta.",
    example: "There is little time left. We have a little time, so let's sit down.",
    trap: "Little kääntyy helposti sanaksi vähän myönteisessä sävyssä. Ilman a-kirjainta sävy on kielteinen.",
  }),
  mcq({
    id: "qua-08",
    skillId: "quantifiers",
    difficulty: 5,
    level: "B2",
    prompt: "Valitse oikea sana.",
    sentence: "There were ___ students than last year.",
    choices: [
      choice("less", "less", "Less kuuluu ei-laskettavaan määrään: less time, less money."),
      choice("fewer", "fewer"),
      choice("little", "little", "Than-vertailu tarvitsee vertailumuodon."),
      choice("few", "few", "Few ei ole vertailumuoto."),
    ],
    answer: "fewer",
    fill: "fewer",
    rule: "Laskettavien vertailu: fewer. Ei-laskettavien vertailu: less.",
    why: "Students voi laskea. Vertailumuoto on fewer students. Less students on yleinen puhekielen lipsahdus, mutta huolellisessa tekstissä se on virhe.",
    example: "Fewer cars, less traffic. Less sugar, fewer biscuits.",
    trap: "Less on niin yleinen, että se leviää myös ihmisiin ja esineisiin. Kokeessa students saa fewer-sanan.",
  }),

  mcq({
    id: "cmp-01",
    skillId: "comparison",
    difficulty: 1,
    level: "A1",
    prompt: "Valitse oikea muoto.",
    sentence: "Anna is ___ than her brother.",
    choices: [
      choice("tall", "tall", "Than vaatii vertailumuodon."),
      choice("taller", "taller"),
      choice("more-tall", "more tall", "Yhden tavun adjektiivi saa -er, ei more."),
      choice("tallest", "tallest", "Tallest on superlatiivi ja vaatisi the-artikkelin sekä joukon."),
    ],
    answer: "taller",
    fill: "taller",
    rule: "Yhden tavun adjektiivi: -er + than.",
    why: "Tall on lyhyt adjektiivi ja vertailussa on than. Muoto on taller.",
    example: "This room is smaller than ours. He is older than me.",
    trap: "More tall tuntuu loogiselta, koska more on opittu vertailusanaksi. Lyhyet sanat eivät käytä sitä.",
  }),
  mcq({
    id: "cmp-02",
    skillId: "comparison",
    difficulty: 2,
    level: "A2",
    prompt: "Valitse oikea muoto.",
    sentence: "This box is ___ than that one.",
    choices: [
      choice("biger", "biger", "Yksi vokaali ja yksi konsonantti: loppu kahdentuu."),
      choice("bigger", "bigger"),
      choice("more-big", "more big", "Big on yhden tavun sana."),
      choice("biggest", "biggest", "Than vaatii komparatiivin, ei superlatiivia."),
    ],
    answer: "bigger",
    fill: "bigger",
    rule: "Lyhyt adjektiivi, joka päättyy yhteen vokaaliin ja yhteen konsonanttiin, kahdentaa konsonantin: big, bigger, the biggest.",
    why: "Big taipuu kahdentumalla. Oikea kirjoitusasu on bigger.",
    example: "hot, hotter. thin, thinner. fat, fatter.",
    trap: "Biger näyttää säännön -er mukaiselta, mutta yksi kirjain puuttuu.",
  }),
  mcq({
    id: "cmp-03",
    skillId: "comparison",
    difficulty: 2,
    level: "A2",
    prompt: "Valitse oikea muoto.",
    sentence: "This story is ___ than the last one.",
    choices: [
      choice("interestinger", "interestinger", "Pitkä adjektiivi ei saa -er-päätettä."),
      choice("more-interesting", "more interesting"),
      choice("most-interesting", "most interesting", "Most on superlatiivi. Than vaatii komparatiivin."),
      choice("more-interestinger", "more interestinger", "More ja -er yhdessä on liikaa."),
    ],
    answer: "more-interesting",
    fill: "more interesting",
    rule: "Pitkä adjektiivi vertaillaan sanoilla more ja the most.",
    why: "Interesting on pitkä. Vertailumuoto on more interesting than.",
    example: "more expensive, more difficult, more useful",
    trap: "Interestinger ei ole sana, vaikka -er toimii sanassa tall.",
  }),
  mcq({
    id: "cmp-04",
    skillId: "comparison",
    difficulty: 2,
    level: "A2",
    prompt: "Valitse oikea muoto.",
    sentence: "This film is ___ than the book.",
    choices: [
      choice("good", "good", "Than vaatii vertailumuodon."),
      choice("gooder", "gooder", "Good ei taivu säännöllisesti."),
      choice("better", "better"),
      choice("more-good", "more good", "More good ei ole englannin vertailumuoto."),
    ],
    answer: "better",
    fill: "better",
    rule: "Good, better, the best. Bad, worse, the worst.",
    why: "Good on epäsäännöllinen. Komparatiivi on better.",
    example: "She feels better today. This is the best answer.",
    trap: "Gooder ja more good ovat johdonmukaisia, mutta englanti ei taivuta good-sanaa niin.",
  }),
  mcq({
    id: "cmp-05",
    skillId: "comparison",
    difficulty: 3,
    level: "B1",
    prompt: "Valitse oikea muoto.",
    sentence: "She is ___ player on the team.",
    choices: [
      choice("best", "best", "Superlatiivin edessä on the."),
      choice("the-best", "the best"),
      choice("better", "better", "Better vertaa kahta. Joukon ykkönen on superlatiivi."),
      choice("the-better", "the better", "The better ei tarkoita joukon parasta."),
    ],
    answer: "the-best",
    fill: "the best",
    rule: "Superlatiivi yksilöi joukon ääripään ja ottaa the-artikkelin.",
    why: "On the team rajaa joukon. Ääripää on the best player.",
    example: "the longest day, the most expensive ticket",
    trap: "Best yksin kuulostaa mainokselta. The kuuluu rakenteeseen.",
  }),
  mcq({
    id: "cmp-06",
    skillId: "comparison",
    difficulty: 3,
    level: "B1",
    prompt: "Mikä lause on oikein?",
    choices: [
      choice("a", "She is as taller as Anna.", "As-rakenteessa adjektiivi on perusmuodossa."),
      choice("b", "She is as tall as Anna."),
      choice("c", "She is so tall as Anna.", "So tall as kuuluu kieltoon vanhemmassa tyylissä, ei tähän."),
      choice("d", "She is as tall than Anna.", "Yhtäsuuruus käyttää as ... as, ei than."),
    ],
    answer: "b",
    rule: "Yhtä suuri ominaisuus: as + perusmuoto + as.",
    why: "Kukaan ei ole pidempi. Rakenne on as tall as, ilman -er-päätettä ja ilman than-sanaa.",
    example: "This bag is as heavy as yours. He is not as old as he looks.",
    trap: "Than ja -er tulevat mukaan, koska vertailu on mielessä. As-rakenne on eri muotti.",
  }),
  mcq({
    id: "cmp-07",
    skillId: "comparison",
    difficulty: 4,
    level: "B1",
    prompt: "Valitse oikea muoto.",
    sentence: "The weather is ___ than yesterday.",
    choices: [
      choice("badder", "badder", "Bad ei saa -er-päätettä."),
      choice("worse", "worse"),
      choice("more-bad", "more bad", "More bad ei ole vertailumuoto."),
      choice("worst", "worst", "Worst on superlatiivi: the worst."),
    ],
    answer: "worse",
    fill: "worse",
    rule: "Bad taipuu worse ja the worst. Ei badder eikä more bad.",
    why: "Sää on huonompi kuin eilen. Komparatiivi on worse.",
    example: "This result is worse. It was the worst day of the trip.",
    trap: "Worse ja worst sekoittuvat. Than kertoo, että kyse on komparatiivista worse.",
  }),
  mcq({
    id: "cmp-08",
    skillId: "comparison",
    difficulty: 5,
    level: "B2",
    prompt: "Mikä lause on oikein?",
    choices: [
      choice("a", "The sooner we leave, the better."),
      choice("b", "Sooner we leave, better it is.", "Rakenne tarvitsee the-sanan molempiin puoliskoihin."),
      choice("c", "The soonest we leave, the best.", "Rakenne käyttää komparatiivia, ei superlatiivia."),
      choice("d", "Sooner we leave, the better.", "Ensimmäinen the puuttuu."),
    ],
    answer: "a",
    rule: "The + komparatiivi, the + komparatiivi kuvaa, että kaksi asiaa muuttuu yhdessä.",
    why: "Mitä nopeammin lähdemme, sitä parempi. Molemmat puolet ovat komparatiivissa ja molemmissa on the.",
    example: "The more you practise, the easier it gets.",
    trap: "Suomen ”mitä ... sitä” ei käänny sanalla what. Englannin muotti on the ... the.",
  }),
];
