import type { Field, FieldGroup, FieldId } from "./types";

export const FIELDS: Field[] = [
  {
    id: "construction",
    group: "Tekniikka ja työmaa",
    title: "Rakennusala",
    summary: "Työmaalla englantia tarvitaan turvaohjeisiin, mittoihin, piirustuksiin ja siihen, että vaaran ehtii sanoa ajoissa.",
    need: [
      "Käskeä pitämään kypärä, valjaat ja turvakengät.",
      "Lukea mitta piirustuksesta: metri, millimetri, kerros.",
      "Varoittaa aukosta, tuoreesta betonista ja putoamisesta.",
      "Kertoa työnjohtajalle, ennen kuin kantavaa rakennetta leikataan.",
    ],
    phrases: [
      { en: "Wear your harness before you climb.", fi: "Laita valjaat ennen kuin kiipeät." },
      { en: "Mind the opening.", fi: "Varo aukkoa." },
      { en: "The slab is 150 millimetres thick.", fi: "Laatta on 150 millimetriä paksu." },
      { en: "Check with the site manager first.", fi: "Varmista ensin työnjohtajalta." },
    ],
    trap: "Suomeksi käsky on usein pelkkä verbi. Englannissa työmaakäsky on kokonainen lause: Wear your helmet, ei Wear helmet.",
  },
  {
    id: "electrical",
    group: "Tekniikka ja työmaa",
    title: "Sähköala",
    summary: "Sähkötyössä väärä sana on vaarallinen. Erota jännitteellinen ja jännitteetön, ja sano erotus selvästi.",
    need: [
      "Erottaa syöttö ja lukita se.",
      "Sanoa, onko piiri jännitteellinen.",
      "Kertoa jännite ja että vikavirtasuoja laukesi.",
      "Kieltää jännitetyö, jos lupaa ei ole.",
    ],
    phrases: [
      { en: "Isolate the supply and lock it off.", fi: "Erota syöttö ja lukitse se." },
      { en: "The circuit is still live.", fi: "Piiri on yhä jännitteellinen." },
      { en: "Test before you touch.", fi: "Testaa ennen kuin kosket." },
      { en: "The RCD has tripped.", fi: "Vikavirtasuoja on lauennut." },
    ],
    trap: "Live tarkoittaa jännitteellistä. Life on elämä. Työmaalla ne eivät ole sama sana.",
  },
  {
    id: "hvac",
    group: "Tekniikka ja työmaa",
    title: "Talotekniikka",
    summary: "Asiakkaan kodissa ja konehuoneessa pitää osata kertoa vuodosta, paineesta ja siitä, milloin tulette takaisin.",
    need: [
      "Sulkea vesi ennen avaamista.",
      "Kertoa, missä vuoto on.",
      "Selittää kattilan paine ja patterin ilmaus.",
      "Sopia asiakkaan kanssa paluuajasta.",
    ],
    phrases: [
      { en: "Turn the water off first.", fi: "Sulje vesi ensin." },
      { en: "There is a leak under the sink.", fi: "Allaskaapin alla on vuoto." },
      { en: "The boiler pressure is too high.", fi: "Kattilan paine on liian korkea." },
      { en: "We will be back tomorrow morning.", fi: "Palaamme huomenna aamulla." },
    ],
    trap: "Under the sink on allaskaapin alla. Below the sink voi kuulostaa siltä, että vuoto on alemmassa kerroksessa.",
  },
  {
    id: "surface",
    group: "Tekniikka ja työmaa",
    title: "Pintakäsittely",
    summary: "Maalauksessa ja ruiskutuksessa englanti kertoo kerrokset, tuuletuksen ja sen, milloin pinta on tarpeeksi kuiva.",
    need: [
      "Vaatia hengityssuojain ja tuuletus ennen ruiskutusta.",
      "Suojaa reunat ja sano kerrosten määrä.",
      "Tarkistaa, että alusta on kuiva.",
      "Hioa kerrosten välissä.",
    ],
    phrases: [
      { en: "Ventilate the room before you spray.", fi: "Tuuleta huone ennen ruiskutusta." },
      { en: "Apply two coats.", fi: "Levitä kaksi kerrosta." },
      { en: "The substrate must be dry.", fi: "Alustan pitää olla kuiva." },
      { en: "Sand between coats.", fi: "Hio kerrosten välissä." },
    ],
    trap: "Coat on maalikerros. Jacket on takki. Työohjeessa coat ei tarkoita vaatetta.",
  },
  {
    id: "property",
    group: "Tekniikka ja työmaa",
    title: "Kiinteistönhoito",
    summary: "Huollossa englantia tarvitaan vikailmoitukseen, asukkaan kanssa sopimiseen ja siihen, mitä käytävässä tai pihalla pitää tehdä heti.",
    need: [
      "Kirjata vuoto, kylmä patteri tai palanut lamppu.",
      "Sopia käynti asukkaan kanssa etukäteen.",
      "Kertoa, mikä on rikki ja mitä teet seuraavaksi.",
      "Hoitaa liukas piha ja kulkuväylä.",
    ],
    phrases: [
      { en: "The tenant reports a leak.", fi: "Asukas ilmoittaa vuodosta." },
      { en: "I will call before I come in.", fi: "Soitan ennen kuin tulen sisään." },
      { en: "The radiator is cold.", fi: "Patteri on kylmä." },
      { en: "The path needs gritting.", fi: "Kulkuväylä pitää hiekoittaa." },
    ],
    trap: "Tenant on vuokralainen. Tenet ei ole englantia tässä työssä. Älä käännä asukasta sanalla customer, jos kyse on vuokratalosta.",
  },
  {
    id: "automotive",
    group: "Tekniikka ja työmaa",
    title: "Autoala",
    summary: "Asiakkaalle pitää osata sanoa, mikä on kulunut, saako autolla ajaa ja mitä katsastuksessa tai huollossa löytyi.",
    need: [
      "Selittää jarrut, renkaat ja nestevuodot selvällä kielellä.",
      "Kieltää ajo, jos auto ei ole turvallinen.",
      "Kertoa, milloin varoitusvalo syttyi.",
      "Erottaa kulunut osa ja ehjä osa.",
    ],
    phrases: [
      { en: "The front brake pads are worn.", fi: "Etujarrupalat ovat kuluneet." },
      { en: "Do not drive it like this.", fi: "Älä aja sillä tässä kunnossa." },
      { en: "The warning light came on.", fi: "Varoitusvalo syttyi." },
      { en: "The tyre pressure is low.", fi: "Rengaspaine on matala." },
    ],
    trap: "Brittienglannissa tyre on rengas. Tire on sama asia amerikanenglannissa, mutta koulun ja monen ohjekirjan linja on tyre.",
  },
  {
    id: "logistics",
    group: "Liikenne ja luonto",
    title: "Logistiikka",
    summary: "Kuljetuksessa pitää osata lasti, kuitti, myöhästyminen ja se, mihin lava jätetään.",
    need: [
      "Pyytää kuittaus toimituksesta.",
      "Sanoa, että lähetys on myöhässä ja miksi.",
      "Varoittaa trukin lähellä.",
      "Kertoa, jos tullipaperi tai rahtikirja puuttuu.",
    ],
    phrases: [
      { en: "Please sign for the delivery.", fi: "Kuittaa toimitus." },
      { en: "The shipment is delayed.", fi: "Lähetys on myöhässä." },
      { en: "Look behind you before you reverse.", fi: "Katso taaksesi ennen peruutusta." },
      { en: "This side up.", fi: "Tämä puoli ylöspäin." },
    ],
    trap: "Delivery on toimitus. Delivering on tekeminen. Asiakkaalle sanotaan The delivery is here, ei The delivering.",
  },
  {
    id: "maritime",
    group: "Liikenne ja luonto",
    title: "Merenkulku",
    summary: "Radiossa ja kannella sanat on standardoitu. Mayday, pan-pan ja man overboard eivät ole vapaata puhetta.",
    need: [
      "Erottaa hätäpuhelu ja kiireellinen vikailmoitus.",
      "Huutaa mies yli laidan ja puoli.",
      "Antaa köysikäsky selvästi.",
      "Luovuttaa vahti niin, että seuraava tietää tilanteen.",
    ],
    phrases: [
      { en: "Mayday. We need immediate help.", fi: "Mayday. Tarvitsemme apua heti." },
      { en: "Man overboard, starboard side.", fi: "Mies yli laidan, styyrpuuri." },
      { en: "Stand by the lines.", fi: "Olkaa valmiina köysillä." },
      { en: "I am handing over the watch.", fi: "Luovutan vahdin." },
    ],
    trap: "Mayday on hätä, jossa on välitön vaara. Pan-pan on kiireellinen, mutta ei vielä sama kuin Mayday. Niitä ei vaihdeta keskenään.",
  },
  {
    id: "agriculture",
    group: "Liikenne ja luonto",
    title: "Maatalous",
    summary: "Navetassa ja pellolla englantia tarvitaan eläimen vikaan, koneeseen ja siihen, että portti ja vaara-alue tulevat sanotuksi.",
    need: [
      "Kertoa, että eläin ontuu tai ei syö.",
      "Varoittaa traktorin takana seisomisesta.",
      "Sanoa, että aita on auki tai pakkanen tulee.",
      "Muistuttaa portin sulkemisesta.",
    ],
    phrases: [
      { en: "The cow is lame.", fi: "Lehmä ontuu." },
      { en: "Do not stand behind the tractor.", fi: "Älä seiso traktorin takana." },
      { en: "The fence is down.", fi: "Aita on poikki." },
      { en: "Shut the gate behind you.", fi: "Sulje portti perässäsi." },
    ],
    trap: "Lame tarkoittaa ontuvaa eläintä tai ihmistä. Lazy on laiska. Ne eivät kuvaa samaa vikaa.",
  },
  {
    id: "forestry",
    group: "Liikenne ja luonto",
    title: "Metsäala",
    summary: "Kaadossa englanninkielinen ohje kertoo kaatosuunnan, pakoreitin ja sen, milloin tuuli keskeyttää työn.",
    need: [
      "Sopia kaatosuunta ennen loveusta.",
      "Varmistaa pakoreitti.",
      "Keskeyttää työ kovalla tuulella.",
      "Pitää turvahousut ja kypärä päällä.",
    ],
    phrases: [
      { en: "Clear the escape route before you cut.", fi: "Avaa pakoreitti ennen loveusta." },
      { en: "Stop work. The wind is too strong.", fi: "Keskeytä työ. Tuuli on liian kova." },
      { en: "Wear chainsaw trousers.", fi: "Pidä turvahousut." },
      { en: "The tree will fall that way.", fi: "Puu kaatuu tuohon suuntaan." },
    ],
    trap: "Fall on kaatuminen. Feel on tunne. Kaatosuunnassa tarvitaan fall, ei feel.",
  },
  {
    id: "machining",
    group: "Tekniikka ja työmaa",
    title: "Kone- ja tuotantotekniikka",
    summary: "Koneistuksessa pitää osata pysäyttää kone, kertoa toleranssi ja sanoa, että terä tai kappale ei ole mitassa.",
    need: [
      "Pysäyttää kone ennen mittausta.",
      "Lukea toleranssi.",
      "Kieltää suojan poistaminen käynnin aikana.",
      "Ilmoittaa, että kappale on toleranssin ulkopuolella.",
    ],
    phrases: [
      { en: "Stop the machine before you measure.", fi: "Pysäytä kone ennen mittausta." },
      { en: "The tolerance is five hundredths of a millimetre.", fi: "Toleranssi on viisi sadasosamillimetriä." },
      { en: "Do not remove the guard.", fi: "Älä irrota suojusta." },
      { en: "The part is out of tolerance.", fi: "Kappale ei ole toleranssissa." },
    ],
    trap: "Out of tolerance tarkoittaa, että mitta ei kelpaa. Out of order tarkoittaa, että kone on rikki. Ne ovat eri ilmoituksia.",
  },
  {
    id: "process",
    group: "Tekniikka ja työmaa",
    title: "Prosessiteollisuus",
    summary: "Vuoronvaihdossa ja häiriössä pitää osata venttiili, paine, vuoto ja se, ettei hälytystä ohiteta omin päin.",
    need: [
      "Sulkea venttiili, kun paine nousee.",
      "Luovuttaa vuoro niin, että vika on sanottu.",
      "Rajata vuoto ja kutsua apu.",
      "Kieltää hälytyksen ohitus ilman lupaa.",
    ],
    phrases: [
      { en: "The pressure is rising. Close the inlet valve.", fi: "Paine nousee. Sulje tuloventtiili." },
      { en: "The pump is down.", fi: "Pumppu on pois käytöstä." },
      { en: "Contain the spill and call the supervisor.", fi: "Rajaa vuoto ja kutsu esimies." },
      { en: "Do not bypass the alarm.", fi: "Älä ohita hälytystä." },
    ],
    trap: "Spill on valunut aine. Spell on kirjoitusasu. Häiriöilmoituksessa tarvitaan spill.",
  },
  {
    id: "laboratory",
    group: "Viestintä ja tarkkuus",
    title: "Laboratorioala",
    summary: "Laboratoriossa näyte, päiväys ja poikkeava tulos pitää osata sanoa niin, ettei näyte sekoitu.",
    need: [
      "Merkitä näytteeseen nimi, päivä ja aika.",
      "Kieltää pipetointi suulla.",
      "Ilmoittaa, että tulos on alueen ulkopuolella.",
      "Riisua hanskat ennen näppäimistöä.",
    ],
    phrases: [
      { en: "Label the sample with the date and time.", fi: "Merkitse näytteeseen päivä ja aika." },
      { en: "Do not pipette by mouth.", fi: "Älä pipetoi suulla." },
      { en: "The result is out of range.", fi: "Tulos on alueen ulkopuolella." },
      { en: "Take your gloves off before the keyboard.", fi: "Riisu hanskat ennen näppäimistöä." },
    ],
    trap: "Sample on näyte. Example on esimerkki. Pöytäkirjassa ne eivät vaihdu.",
  },
  {
    id: "restaurant",
    group: "Palvelu ja ihmiset",
    title: "Ravintola- ja catering-ala",
    summary: "Sali- ja keittiötyössä englanti on allergeeneja, varausta, tilausta ja laskua. Yksi väärä ainesosa on asiakkaan turvallisuus.",
    need: [
      "Kysyä pähkinä, gluteeni ja muut allergeenit.",
      "Ottaa pöytävaraus nimellä.",
      "Sanoa, jos sali on täynnä.",
      "Tuoda lasku ja erottaa se lapusta.",
    ],
    phrases: [
      { en: "Does this contain nuts?", fi: "Onko tässä pähkinää?" },
      { en: "The table is booked under Nieminen.", fi: "Pöytä on varattu nimellä Nieminen." },
      { en: "I am sorry, we are fully booked.", fi: "Valitettavasti olemme täynnä." },
      { en: "How would you like your steak?", fi: "Miten haluatte pihvin?" },
    ],
    trap: "Bill on lasku ravintolassa. Note on lappu tai viesti. Asiakas pyytää the bill, ei the note.",
  },
  {
    id: "food",
    group: "Palvelu ja ihmiset",
    title: "Elintarvikeala",
    summary: "Elintarviketyössä kylmäketju, päiväys ja hygieniasanat pitää osata, koska tarkastaja ja resepti voivat olla englanniksi.",
    need: [
      "Sanoa kylmiön lämpötila.",
      "Erottaa parasta ennen ja viimeinen käyttöpäivä.",
      "Kieltää uudelleenjäädytys.",
      "Vaatia käsien pesu ja päähine.",
    ],
    phrases: [
      { en: "The cold room is at four degrees.", fi: "Kylmiö on neljässä asteessa." },
      { en: "Wash your hands.", fi: "Pese kädet." },
      { en: "Do not refreeze it.", fi: "Älä jäädytä sitä uudelleen." },
      { en: "Check the use-by date.", fi: "Tarkista viimeinen käyttöpäivä." },
    ],
    trap: "Use by on viimeinen käyttöpäivä, jonka jälkeen tuote ei ole turvallinen. Best before on parasta ennen, joka kertoo laadusta.",
  },
  {
    id: "tourism",
    group: "Palvelu ja ihmiset",
    title: "Matkailuala",
    summary: "Vastaanotossa kerrosnumerointi, sisäänkirjautuminen ja reittiohje menevät pieleen, jos brittienglannin ground floor sekoittuu suomalaiseen ykköskerrokseen.",
    need: [
      "Tehdä check-in ja kertoa aamiainen.",
      "Ohjata perille: vasemmalle, kirkon luona, kolmas kerros.",
      "Ottaa vastaan valitus suihkusta tai melusta.",
      "Sopia myöhäisempi uloskirjautuminen.",
    ],
    phrases: [
      { en: "Check-in is from three o'clock.", fi: "Sisäänkirjautuminen alkaa kello kolme." },
      { en: "Your room is on the first floor.", fi: "Huoneenne on ensimmäisessä kerroksessa katutasosta." },
      { en: "Breakfast is served from seven to ten.", fi: "Aamiainen on tarjolla seitsemästä kymmeneen." },
      { en: "The shower in room 12 does not work.", fi: "Huoneen 12 suihku ei toimi." },
    ],
    trap: "Brittienglannissa ground floor on katutaso. First floor on sitä seuraava kerros. Suomen 1. kerros on usein ground floor, ei first floor.",
  },
  {
    id: "business",
    group: "Palvelu ja ihmiset",
    title: "Liiketoiminta",
    summary: "Toimistossa englanti on sähköpostia, laskua, tapaamista ja kohteliasta kieltäytymistä.",
    need: [
      "Vahvistaa tapaaminen kirjallisesti.",
      "Laittaa lasku liitteeksi.",
      "Sanoa, että lasku on myöhässä.",
      "Peruuttaa tapaaminen ilman töksähtävää no-sanaa.",
    ],
    phrases: [
      { en: "I am writing to confirm our meeting.", fi: "Vahvistan tapaamisemme." },
      { en: "Please find the invoice attached.", fi: "Lasku on liitteenä." },
      { en: "The invoice is overdue.", fi: "Lasku on myöhässä." },
      { en: "I am afraid I cannot make Thursday.", fi: "Torstai ei valitettavasti sovi." },
    ],
    trap: "I am afraid ei tarkoita, että pelkäät. Se pehmentää huonoa uutista: valitettavasti en pääse.",
  },
  {
    id: "care",
    group: "Palvelu ja ihmiset",
    title: "Sosiaali- ja terveysala",
    summary: "Hoidossa kysytään kipu, lupa ja mitä vuoron aikana tapahtui. Lääkettä ei luvata eikä anneta omin sanoin.",
    need: [
      "Kysyä, missä koskee.",
      "Pyytää lupa mittaukseen.",
      "Raportoida kaatuminen ja syöminen.",
      "Kieltäytyä antamasta lääkettä, jota ei ole määrätty.",
    ],
    phrases: [
      { en: "Where does it hurt?", fi: "Missä koskee?" },
      { en: "Is it all right if I check your blood pressure?", fi: "Saanko mitata verenpaineen?" },
      { en: "She fell this morning.", fi: "Hän kaatui tänä aamuna." },
      { en: "She has not eaten since breakfast.", fi: "Hän ei ole syönyt aamupalan jälkeen." },
    ],
    trap: "Has not eaten since breakfast kertoo tilanteen, joka alkoi aamulla ja jatkuu yhä. Did not eat breakfast kertoo vain aamupalasta.",
  },
  {
    id: "beauty",
    group: "Palvelu ja ihmiset",
    title: "Hius- ja kauneudenhoitoala",
    summary: "Asiakastyössä allergeenitesti, aika ja jälkihoito-ohje pitää osata ennen väriä tai kestotaivutusta.",
    need: [
      "Kysyä allergiat ja aiempi testi.",
      "Sopia aika puolelta.",
      "Kertoa, ettei hiuksia pestä heti värin jälkeen.",
      "Selittää, että väriaineen pitää vaikuttaa.",
    ],
    phrases: [
      { en: "Have you had a patch test?", fi: "Onko sinulle tehty allergeenitesti?" },
      { en: "Your appointment is at half past two.", fi: "Aikasi on puoli kolme." },
      { en: "Do not wash your hair for 48 hours.", fi: "Älä pese hiuksia 48 tuntiin." },
      { en: "The colour needs to develop.", fi: "Värin pitää antaa vaikuttaa." },
    ],
    trap: "Half past two on 14.30. Half two on brittirepliikeissä sama asia, mutta half to two tarkoittaisi 13.30. Sano half past, niin aika ei vaihdu.",
  },
  {
    id: "cleaning",
    group: "Palvelu ja ihmiset",
    title: "Puhtauspalveluala",
    summary: "Siivouksessa aineet, kyltti ja rikkinäinen lukko pitää osata sanoa. Kahta ainetta ei sekoiteta, vaikka purkissa olisi englantia.",
    need: [
      "Kieltää kloorin ja hapon sekoitus.",
      "Laittaa märän lattian kyltti.",
      "Valita aine lasille ja lattialle.",
      "Ilmoittaa rikkinäinen lukko tai vuoto.",
    ],
    phrases: [
      { en: "Never mix bleach with acid.", fi: "Älä sekoita klooria ja happoa." },
      { en: "Put out the wet floor sign.", fi: "Laita märän lattian kyltti." },
      { en: "Use the glass cleaner on the mirrors.", fi: "Käytä lasinpesuainetta peileihin." },
      { en: "The lock on the side door is broken.", fi: "Sivuoven lukko on rikki." },
    ],
    trap: "Bleach on klooripohjainen valkaisuaine. Beach on ranta. Aineohjeessa ero on turvallisuuskysymys.",
  },
  {
    id: "security",
    group: "Palvelu ja ihmiset",
    title: "Turvallisuusala",
    summary: "Ovella ja kierroksella englanti on henkilöllisyys, kulkuoikeus, hälytys ja se, mitä kirjoitetaan raporttiin.",
    need: [
      "Pyytää henkilöllisyystodistus.",
      "Estää perässä hiipiminen ovesta.",
      "Ohjata ulos lähimmästä uloskäynnistä.",
      "Kirjata mitä tapahtui, milloin ja kuka.",
    ],
    phrases: [
      { en: "Can I see your ID, please?", fi: "Saanko nähdä henkilöllisyystodistuksen?" },
      { en: "Please do not tailgate.", fi: "Älkää tulko samalla ovenavauksella perässä." },
      { en: "Leave by the nearest exit.", fi: "Poistukaa lähimmästä uloskäynnistä." },
      { en: "Please sign the visitors' book.", fi: "Kuitatkaa vieraskirjaan." },
    ],
    trap: "Tailgate on tulla ovesta toisen perässä ilman omaa kulkuoikeutta. Se ei ole sama kuin portti tai häntä.",
  },
  {
    id: "ict",
    group: "Viestintä ja tarkkuus",
    title: "Tieto- ja viestintätekniikka",
    summary: "Tukipyynnössä pitää osata katko, salasana, varmuuskopio ja se, ettei asiakkaan salasanaa pyydetä chatissa.",
    need: [
      "Kysyä, onko laite käynnistetty uudelleen.",
      "Kieltää salasanan jakaminen.",
      "Avata tiketti ja kertoa aloitusaika.",
      "Varmuuskopioida ennen päivitystä.",
    ],
    phrases: [
      { en: "Have you turned it off and on again?", fi: "Oletko sammuttanut sen ja käynnistänyt uudelleen?" },
      { en: "Do not share your password.", fi: "Älä jaa salasanaasi." },
      { en: "I will raise a ticket.", fi: "Teen tukipyynnön." },
      { en: "The outage started at eight.", fi: "Katko alkoi kello kahdeksan." },
    ],
    trap: "Outage on käyttökatko. Outrage on tuohtumus. Vikailmoituksessa sana on outage.",
  },
  {
    id: "media",
    group: "Viestintä ja tarkkuus",
    title: "Media-ala",
    summary: "Toimituksessa deadline, kuvan oikeudet ja alaikäisen nimi ovat asioita, jotka pitää osata sanoa ennen julkaisua.",
    need: [
      "Kertoa, milloin juttu tai leikkaus pitää olla valmis.",
      "Kysyä, saako haastattelun nauhoittaa.",
      "Tarkistaa, kuka omistaa kuvan.",
      "Jättää alaikäisen nimi julkaisematta.",
    ],
    phrases: [
      { en: "The copy is due at noon.", fi: "Tekstin pitää olla valmis keskipäivällä." },
      { en: "May I record this interview?", fi: "Saanko nauhoittaa tämän haastattelun?" },
      { en: "Who owns the rights to this photo?", fi: "Kuka omistaa tämän kuvan oikeudet?" },
      { en: "Do not publish the child's name.", fi: "Älä julkaise lapsen nimeä." },
    ],
    trap: "Due at noon tarkoittaa, että työ pitää luovuttaa keskipäivällä. Due to noon tarkoittaisi syytä, ei kellonaikaa.",
  },
  {
    id: "textile",
    group: "Viestintä ja tarkkuus",
    title: "Tekstiili- ja muotiala",
    summary: "Sovituksessa ja ompelussa mitta, helma, kutistuminen ja pesuohje pitää osata sanoa asiakkaalle.",
    need: [
      "Ottaa vyötärömitta.",
      "Lyhentää helma asiakkaan pyynnöstä.",
      "Varoittaa, että kangas kutistuu.",
      "Lukea pesumerkintä.",
    ],
    phrases: [
      { en: "Take the waist measurement.", fi: "Ota vyötärömitta." },
      { en: "The client wants the hem shorter.", fi: "Asiakas haluaa helman lyhyemmäksi." },
      { en: "This fabric shrinks in the wash.", fi: "Tämä kangas kutistuu pesussa." },
      { en: "The seam has split.", fi: "Sauma on ratkennut." },
    ],
    trap: "Hem on helma. Him on hänet. Sovituksessa väärä sana muuttaa koko ohjeen.",
  },
];

const byId = new Map(FIELDS.map((field) => [field.id, field]));

export function isFieldId(value: string): value is FieldId {
  return byId.has(value as FieldId);
}

export function getField(id: string): Field | undefined {
  return byId.get(id as FieldId);
}

export function fieldsInGroup(group: FieldGroup): Field[] {
  return FIELDS.filter((field) => field.group === group);
}

export const FIELD_GROUPS: FieldGroup[] = [
  "Tekniikka ja työmaa",
  "Liikenne ja luonto",
  "Palvelu ja ihmiset",
  "Viestintä ja tarkkuus",
];
