import { FIELD_IDS, type FieldId, type Occupation, type QualificationName, type Term, type TermGroup } from "./types";

export type TradePack = {
  qualification: QualificationName;
  occupations: Occupation[];
  terms: Term[];
};

function job(fi: string, en: string, does: string, official = false): Occupation {
  return official ? { fi, en, does, official: true } : { fi, en, does };
}

function word(en: string, fi: string, group: TermGroup): Term {
  return { en, fi, group };
}

export const TRADE: Record<FieldId, TradePack> = {
  construction: {
    qualification: {
      fi: "Rakennusalan perustutkinto",
      en: "Vocational Qualification in Construction",
    },
    occupations: [
      job("Talonrakentaja", "Building Constructor", "Opintopolun tutkintonimike. Talonrakentaja tekee rungon, väliseinät ja pintaan liittyvät työt työmaalla.", true),
      job("Kirvesmies", "Carpenter", "Työmaasana. Kirvesmies tekee puurungon, levyt ja listat. Tutkintonimike on silti usein Building Constructor."),
      job("Kivirakentaja", "Mason", "Tutkintonimike. Kivirakentaja muuraa ja tekee kivi- ja betonirakenteita.", true),
      job("Raudoittaja", "Steel fixer", "Työmaasana. Raudoittaja sitoo betoniteräkset ennen valua."),
      job("Teollisuuspuurakentaja", "Industrial Carpenter", "Tutkintonimike. Tekee puuelementtejä tehtaalla, ei vain työmaalla.", true),
      job("Elementtiasentaja", "Precast installer", "Työmaasana. Nostaa ja kiinnittää betoni- tai puuelementit."),
      job("Torninosturin kuljettaja", "Tower crane operator", "Työmaasana. Nostaa kuormat torninosturilla."),
      job("Työnjohtaja", "Site supervisor", "Työmaasana. Johtaa työvaiheen ja vastaa siitä, että työ tehdään piirustusten mukaan."),
    ],
    terms: [
      word("scaffolding", "teline", "välineet"),
      word("hard hat", "kypärä", "turvallisuus"),
      word("high-visibility vest", "huomioliivi", "turvallisuus"),
      word("safety boots", "turvakengät", "turvallisuus"),
      word("safety harness", "turvavaljaat", "turvallisuus"),
      word("formwork", "muotti", "välineet"),
      word("reinforcement", "raudoitus", "välineet"),
      word("spirit level", "vatupassi", "välineet"),
      word("drawing", "piirustus", "paperit"),
      word("site induction", "työmaaperehdytys", "turvallisuus"),
      word("guard rail", "suojakaide", "turvallisuus"),
      word("site hut", "työmaakoppi", "paikat"),
    ],
  },
  electrical: {
    qualification: {
      fi: "Sähkö- ja automaatioalan perustutkinto",
      en: "Vocational Qualification in Electrical Engineering and Automation",
    },
    occupations: [
      job("Sähköasentaja", "Electrician", "Tutkintonimike. Asentaa, tarkastaa ja korjaa sähköasennuksia.", true),
      job("Automaatioasentaja", "Automation Assembler", "Tutkintonimike. Tekee koneiden ja kiinteistöjen automaatiota.", true),
      job("Elektroniikka-asentaja", "Electronics Assembler", "Tutkintonimike. Kokoaa ja korjaa elektroniikkalaitteita.", true),
      job("Sähköverkkoasentaja", "Power network installer", "Työmaasana. Tekee ilmajohtoja ja maakaapeleita. Älä sekoita tietoverkkoasentajaan."),
      job("Käyttöönottaja", "Commissioning technician", "Työmaasana. Tekee mittaukset ja luovutuksen ennen käyttöä."),
      job("Sähköalan työnjohtaja", "Electrical supervisor", "Työmaasana. Vastaa siitä, että asennus on määräysten mukainen."),
      job("Harjoittelija", "Apprentice", "Työmaasana. Opiskelee asentajan mukana eikä tee jännitetyötä ilman lupaa."),
      job("Huoltoasentaja", "Maintenance electrician", "Työmaasana. Korjaa vikoja käytössä olevissa kiinteistöissä ja tehtaissa."),
    ],
    terms: [
      word("distribution board", "jakokeskus", "välineet"),
      word("circuit breaker", "johdonsuojakatkaisija", "välineet"),
      word("RCD", "vikavirtasuoja", "turvallisuus"),
      word("lockout", "lukitus", "turvallisuus"),
      word("live", "jännitteellinen", "turvallisuus"),
      word("isolation", "erotus", "turvallisuus"),
      word("earthing", "maadoitus", "turvallisuus"),
      word("cable tray", "kaapelihylly", "välineet"),
      word("conduit", "asennusputki", "välineet"),
      word("permit to work", "työlupa", "paperit"),
      word("consumer unit", "asunnon ryhmäkeskus", "välineet"),
      word("three-phase supply", "kolmivaihesyöttö", "välineet"),
    ],
  },
  hvac: {
    qualification: {
      fi: "Talotekniikan perustutkinto",
      en: "Vocational Qualification in Building Services",
    },
    occupations: [
      job("Putkiasentaja", "Pipe Fitter", "Tutkintonimike. Asentaa vesi-, viemäri- ja lämmitysputket. Asiakas sanoo usein plumber.", true),
      job("Ilmanvaihtoasentaja", "Ventilation Fitter", "Tutkintonimike. Asentaa kanavat, päätelaitteet ja ilmanvaihtokoneet.", true),
      job("Kylmäasentaja", "Refrigeration Fitter", "Tutkintonimike. Asentaa ja huoltaa kylmälaitteita. Työ vaatii kylmäaineluvan.", true),
      job("Lämmityslaiteasentaja", "Heating installer", "Työmaasana. Asentaa kattilat, patterit ja lämmönjakolaitteet."),
      job("Rakennuspeltiseppä", "Construction Sheet Metal Worker", "Tutkintonimike. Tekee pellitykset, räystäät ja julkisivun pellit.", true),
      job("LVI-asentaja", "HVAC installer", "Työmaasana koko alalle. Heating, ventilation and plumbing kuuluvat samaan työhön."),
      job("Huoltomies, LVI", "Building services technician", "Työmaasana. Käy asiakkaan luona vuotojen ja patterien takia."),
      job("Työnjohtaja, talotekniikka", "Building services supervisor", "Työmaasana. Vastaa asennuksen järjestyksestä ja luovutuksesta."),
    ],
    terms: [
      word("stop valve", "sulkuventtiili", "välineet"),
      word("radiator", "patteri", "välineet"),
      word("air handling unit", "ilmanvaihtokone", "välineet"),
      word("filter", "suodatin", "välineet"),
      word("drain", "viemäri", "välineet"),
      word("leak", "vuoto", "turvallisuus"),
      word("refrigerant", "kylmäaine", "aineet"),
      word("duct", "kanava", "välineet"),
      word("floor drain", "lattiakaivo", "välineet"),
      word("expansion vessel", "paisunta-astia", "välineet"),
      word("boiler", "kattila", "välineet"),
      word("plant room", "lämmönjakohuone", "paikat"),
    ],
  },
  surface: {
    qualification: {
      fi: "Pintakäsittelyalan perustutkinto",
      en: "Vocational Qualification in Surface Treatment",
    },
    occupations: [
      job("Maalari", "Painter", "Tutkintonimike. Maalaa sisä- ja ulkopintoja.", true),
      job("Lattianpäällystäjä", "Floor Layer", "Tutkintonimike. Asentaa maton, parketin tai muun lattiapinnan.", true),
      job("Pintakäsittelijä", "Surface Treatment Finisher", "Tutkintonimike. Käsittelee teollisia pintoja, ei vain seiniä.", true),
      job("Laatoittaja", "Tiler", "Työmaasana. Laatoittaa seinät ja lattiat."),
      job("Ruiskumaalari", "Spray painter", "Työmaasana. Ruiskuttaa maalin tai lakan kammiossa."),
      job("Tasoitemies", "Plasterer", "Työmaasana. Tasoittaa seinät ennen maalausta. Brittienglannissa plasterer tekee myös rappauksen."),
      job("Julkisivumaalari", "Facade painter", "Työmaasana. Maalaa ulkoseinät ja käyttää putoamissuojausta."),
      job("Teollisuusmaalari", "Industrial painter", "Työmaasana. Maalaa koneita, terästä ja korroosiosuojausta."),
    ],
    terms: [
      word("coat", "maalikerros", "aineet"),
      word("primer", "pohjamaali", "aineet"),
      word("substrate", "alusta", "aineet"),
      word("masking tape", "suojateippi", "välineet"),
      word("respirator", "hengityssuojain", "turvallisuus"),
      word("spray booth", "ruiskutuskaappi", "paikat"),
      word("sandpaper", "hiomapaperi", "välineet"),
      word("filler", "tasoite", "aineet"),
      word("tile adhesive", "laattalaasti", "aineet"),
      word("grout", "saumalaasti", "aineet"),
      word("thinner", "ohenne", "turvallisuus"),
      word("data sheet", "käyttöturvallisuustiedote", "paperit"),
    ],
  },
  property: {
    qualification: {
      fi: "Puhtaus- ja kiinteistöpalvelualan perustutkinto, kiinteistönhoito",
      en: "Vocational Qualification in Cleaning and Property Services, property maintenance",
    },
    occupations: [
      job("Kiinteistönhoitaja", "Property Maintenance Operative", "Tutkintonimike. Hoitaa lämmön, pihan, lukot ja pienet korjaukset.", true),
      job("Huoltomies", "Caretaker", "Työmaasana. Sama työ kuin kiinteistönhoitajalla, näin asukas usein sanoo."),
      job("Tekninen isännöitsijä", "Technical property manager", "Työmaasana. Tilaa korjaukset ja vastaa kiinteistön tekniikasta."),
      job("Pihatyöntekijä", "Grounds maintenance worker", "Työmaasana. Hiekoittaa, auraa ja hoitaa nurmet."),
      job("Lämmönjakajan hoitaja", "Heating plant attendant", "Työmaasana. Seuraa lämmönjakohuoneen painetta ja hälytyksiä."),
      job("Kiinteistöassistentti", "Property assistant", "Työmaasana. Kirjaa vikailmoitukset ja sopii käynnit asukkaiden kanssa."),
      job("Ulkoalueiden hoitaja", "External areas operative", "Työmaasana. Vastaa kulkuväylistä, valaistuksesta ja jätepisteestä."),
      job("Päivystävä huoltomies", "On-call caretaker", "Työmaasana. Lähtee vuotoon tai hissivikaan myös illalla."),
    ],
    terms: [
      word("tenant", "vuokralainen", "ihmiset"),
      word("work order", "työmääräys", "paperit"),
      word("fault report", "vikailmoitus", "paperit"),
      word("radiator", "patteri", "välineet"),
      word("fuse", "sulake", "välineet"),
      word("master key", "yleisavain", "välineet"),
      word("gritting", "hiekoitus", "turvallisuus"),
      word("stairwell", "porrashuone", "paikat"),
      word("plant room", "tekninen tila", "paikat"),
      word("waste room", "jätehuone", "paikat"),
      word("service contract", "huoltosopimus", "paperit"),
      word("access", "kulkuoikeus", "turvallisuus"),
    ],
  },
  automotive: {
    qualification: {
      fi: "Ajoneuvoalan perustutkinto",
      en: "Vocational Qualification in Vehicle Technology",
    },
    occupations: [
      job("Automekaanikko", "Vehicle Mechanic", "Tutkintonimike. Huoltaa ja korjaa autoja.", true),
      job("Ajoneuvoasentaja", "Vehicle technician", "Nykyinen tutkintonimike suomeksi. Englanniksi korjaamo sanoo vehicle mechanic tai vehicle technician."),
      job("Automaalari", "Car Painter", "Tutkintonimike. Maalaa korin ja tekee pohjatyöt.", true),
      job("Varaosamyyjä", "Spare Parts Salesperson", "Tutkintonimike. Hakee osat ja neuvoo asiakasta.", true),
      job("Diagnoosimekaanikko", "Diagnostic Mechanic", "Tutkintonimike. Lukee vikakoodit ja etsii sähköviat.", true),
      job("Autokorimekaanikko", "Vehicle Body Mechanic", "Tutkintonimike. Oikaisee ja vaihtaa korinosat.", true),
      job("Hyötyajoneuvoasentaja", "Commercial Vehicle Mechanic", "Tutkintonimike. Korjaa kuorma- ja linja-autoja.", true),
      job("Huoltoneuvoja", "Service advisor", "Työmaasana. Ottaa auton vastaan ja selittää asiakkaalle, mitä korjataan."),
    ],
    terms: [
      word("brake pads", "jarrupalat", "välineet"),
      word("tyre", "rengas", "välineet"),
      word("warning light", "varoitusvalo", "turvallisuus"),
      word("brake fluid", "jarruneste", "aineet"),
      word("service", "huolto", "paperit"),
      word("fault code", "vikakoodi", "paperit"),
      word("workshop", "korjaamo", "paikat"),
      word("lift", "nosturi", "välineet"),
      word("torque wrench", "momenttiavain", "välineet"),
      word("inspection", "katsastus", "paperit"),
      word("exhaust", "pakoputkisto", "välineet"),
      word("coolant", "jäähdytysneste", "aineet"),
    ],
  },
  logistics: {
    qualification: {
      fi: "Logistiikan perustutkinto",
      en: "Vocational Qualification in Logistics",
    },
    occupations: [
      job("Varastonhoitaja", "Warehouse Operative", "Tutkintonimike. Kerää, hyllyttää ja lähettää tavaran.", true),
      job("Kuorma-autonkuljettaja", "Lorry Driver", "Tutkintonimike. Brittienglannissa kuorma-auto on lorry, ei truck.", true),
      job("Yhdistelmäajoneuvonkuljettaja", "Articulated Vehicle Driver", "Tutkintonimike. Ajaa vetoautoa ja puoliperävaunua.", true),
      job("Linja-autonkuljettaja", "Bus Driver", "Tutkintonimike. Ajaa reitti- tai tilausajoa.", true),
      job("Palvelulogistiikkatyöntekijä", "Service Logistics Operative", "Tutkintonimike. Hoitaa sisäiset kuljetukset ja täydennykset.", true),
      job("Trukinkuljettaja", "Forklift operator", "Työmaasana. Siirtää lavoja varastossa."),
      job("Lähettämön työntekijä", "Dispatch clerk", "Työmaasana. Tekee rahtikirjat ja lastaa lähtevät autot."),
      job("Terminaalityöntekijä", "Terminal operative", "Työmaasana. Lajittelee lähetykset terminaalissa."),
    ],
    terms: [
      word("pallet", "lava", "välineet"),
      word("consignment note", "rahtikirja", "paperit"),
      word("delivery note", "lähete", "paperit"),
      word("forklift", "trukki", "välineet"),
      word("loading bay", "lastauslaituri", "paikat"),
      word("shipment", "lähetys", "paperit"),
      word("fragile", "särkyvä", "turvallisuus"),
      word("warehouse", "varasto", "paikat"),
      word("picking", "keräily", "paikat"),
      word("barcode", "viivakoodi", "paperit"),
      word("tail lift", "takalaitanostin", "välineet"),
      word("high-visibility vest", "huomioliivi", "turvallisuus"),
    ],
  },
  machining: {
    qualification: {
      fi: "Kone- ja tuotantotekniikan perustutkinto",
      en: "Vocational Qualification in Mechanical Engineering and Production Technology",
    },
    occupations: [
      job("Koneistaja", "Machinist", "Tutkintonimike. Valmistaa kappaleita sorvilla, jyrsimellä tai koneistuskeskuksella.", true),
      job("Levyseppähitsaaja", "Plater-welder", "Tutkintonimike. Leikkaa levyä ja hitsaa rakenteet.", true),
      job("Koneenasentaja", "Mechanical Fitter", "Tutkintonimike. Kokoaa koneet ja linjastot.", true),
      job("CNC-koneistaja", "CNC machinist", "Työmaasana. Ajaa tietokoneohjattua konetta."),
      job("Hitsari", "Welder", "Työmaasana. Hitsaa puikko-, MIG- tai TIG-menetelmällä."),
      job("Kunnossapitoasentaja", "Maintenance fitter", "Työmaasana. Pitää tuotantokoneet käynnissä."),
      job("Laaduntarkastaja", "Quality inspector", "Työmaasana. Mittaa kappaleet ja päättää, meneekö erä läpi."),
      job("Työkaluntekijä", "Toolmaker", "Työmaasana. Tekee jigid, kiinnittimet ja muotit."),
    ],
    terms: [
      word("lathe", "sorvi", "välineet"),
      word("milling machine", "jyrsinkone", "välineet"),
      word("tolerance", "toleranssi", "paperit"),
      word("guard", "suojus", "turvallisuus"),
      word("cutting fluid", "lastuamisneste", "aineet"),
      word("caliper", "työntömitta", "välineet"),
      word("drawing", "piirustus", "paperit"),
      word("weld", "hitsi", "välineet"),
      word("burr", "jäyste", "aineet"),
      word("workshop", "koneistamo", "paikat"),
      word("insert", "teräpala", "välineet"),
      word("emergency stop", "hätäseis", "turvallisuus"),
    ],
  },
  process: {
    qualification: {
      fi: "Prosessiteollisuuden perustutkinto",
      en: "Vocational Qualification in Process Industry",
    },
    occupations: [
      job("Prosessinhoitaja", "Process Operator", "Tutkintonimike. Valvoo prosessia valvomon näytöiltä ja kentällä.", true),
      job("Levyprosessinhoitaja", "Board Process Operator", "Tutkintonimike. Hoitaa kartonki- tai levykonetta.", true),
      job("Kemian prosessinhoitaja", "Chemical process operator", "Työmaasana. Käsittelee kemikaaleja ja reaktoreita."),
      job("Valvomo-operaattori", "Control room operator", "Työmaasana. Istuu valvomossa ja kuittaa hälytykset."),
      job("Kenttäoperaattori", "Field operator", "Työmaasana. Kävelee laitoksella, avaa venttiilit ja ottaa näytteet."),
      job("Vuoromestari", "Shift supervisor", "Työmaasana. Vastaa vuorosta ja luovutuksesta."),
      job("Kunnossapitoasentaja", "Maintenance technician", "Työmaasana. Korjaa pumput ja venttiilit seisokin aikana."),
      job("Näytteenottaja", "Sample taker", "Työmaasana. Vie näytteet laboratorioon vuoron aikana."),
    ],
    terms: [
      word("valve", "venttiili", "välineet"),
      word("pump", "pumppu", "välineet"),
      word("pressure", "paine", "turvallisuus"),
      word("spill", "vuoto maahan", "turvallisuus"),
      word("alarm", "hälytys", "turvallisuus"),
      word("control room", "valvomo", "paikat"),
      word("shift handover", "vuoronvaihto", "paperit"),
      word("pipe", "putki", "välineet"),
      word("tank", "säiliö", "välineet"),
      word("permit to work", "työlupa", "paperit"),
      word("personal gas detector", "henkilökohtainen kaasumittari", "turvallisuus"),
      word("shutdown", "seisokki", "paikat"),
    ],
  },
  laboratory: {
    qualification: {
      fi: "Laboratorioalan perustutkinto",
      en: "Vocational Qualification in Laboratory Technology",
    },
    occupations: [
      job("Laborantti", "Laboratory Technician", "Tutkintonimike. Ottaa näytteet, tekee analyysit ja kirjaa tulokset.", true),
      job("Näytteenottaja", "Sample collector", "Työmaasana. Hakee näytteet kentältä tai osastolta."),
      job("Laadunvalvojalaborantti", "Quality control technician", "Työmaasana. Tarkistaa, että tuote on spesifikaatiossa."),
      job("Laboratorioapulainen", "Laboratory assistant", "Työmaasana. Pesee astiat, täyttää tarvikkeet ja kirjaa saapuneet näytteet."),
      job("Mikrobiologian laborantti", "Microbiology technician", "Työmaasana. Viljelee ja lukee maljoja."),
      job("Kemian laborantti", "Chemistry technician", "Työmaasana. Tekee titraukset ja liuokset."),
      job("Vastuulaborantti", "Senior laboratory technician", "Työmaasana. Tarkistaa tulokset ennen kuin ne lähtevät asiakkaalle."),
      job("Laboratorion esimies", "Laboratory supervisor", "Työmaasana. Vastaa menetelmistä ja työturvallisuudesta."),
    ],
    terms: [
      word("sample", "näyte", "aineet"),
      word("pipette", "pipetti", "välineet"),
      word("fume cupboard", "vetokaappi", "turvallisuus"),
      word("gloves", "suojakäsineet", "turvallisuus"),
      word("result", "tulos", "paperit"),
      word("reference range", "viitealue", "paperit"),
      word("contamination", "kontaminaatio", "turvallisuus"),
      word("label", "etiketti", "paperit"),
      word("bench", "työpöytä", "paikat"),
      word("reagent", "reagenssi", "aineet"),
      word("balance", "vaaka", "välineet"),
      word("method", "menetelmä", "paperit"),
    ],
  },
  maritime: {
    qualification: {
      fi: "Merenkulkualan perustutkinto",
      en: "Vocational Qualification in Seafaring",
    },
    occupations: [
      job("Matruusi", "Able Seafarer, Deck", "Tutkintonimike kannella. STCW-pätevyys: able seafarer, deck.", true),
      job("Konemies", "Able Seafarer, Engine", "Tutkintonimike konehuoneessa.", true),
      job("Vahtikonemestari", "Watchkeeping Engineer", "Tutkintonimike. Pitää konevahtia.", true),
      job("Laivasähköasentaja", "Marine Electrician", "Tutkintonimike. Huoltaa laivan sähköt.", true),
      job("Kansipäällystö, vahtiperämies", "Deck Officer", "Tutkintonimike. Pitää komentosiltavahtia.", true),
      job("Pursimies", "Boatswain", "Työmaasana. Johtaa kansimiehistön päivätyöt."),
      job("Kokki, laiva", "Ship's cook", "Työmaasana. Laivan keittiössä nimike on ship's cook."),
      job("Merimies", "Rating", "Työmaasana miehistölle, joka ei ole päällystöä. Officer on päällystöä."),
    ],
    terms: [
      word("starboard", "styyrpuuri", "paikat"),
      word("port", "paapuuri", "paikat"),
      word("bridge", "komentosilta", "paikat"),
      word("engine room", "konehuone", "paikat"),
      word("mooring line", "kiinnitysköysi", "välineet"),
      word("watch", "vahti", "ihmiset"),
      word("Mayday", "hätäkutsu", "turvallisuus"),
      word("lifejacket", "pelastusliivi", "turvallisuus"),
      word("muster list", "hälytysluettelo", "paperit"),
      word("gangway", "maihinnoususilta", "välineet"),
      word("bilge", "pilssi", "paikat"),
      word("logbook", "päiväkirja", "paperit"),
    ],
  },
  restaurant: {
    qualification: {
      fi: "Ravintola- ja catering-alan perustutkinto",
      en: "Vocational Qualification in Restaurant and Catering Services",
    },
    occupations: [
      job("Kokki", "Cook", "Tutkintonimike. Chef on keittiömestari, ei jokainen kokki.", true),
      job("Ravintolakokki", "Restaurant Cook", "Tutkintonimike ammattitutkinnossa. Tekee annosruokaa.", true),
      job("Suurtalouskokki", "Institutional Cook", "Tutkintonimike. Tekee ruokaa koulussa, sairaalassa tai henkilöstöravintolassa.", true),
      job("Tarjoilija", "Waiter/Waitress", "Tutkintonimike. Server on yleisempi nykyään, mutta tutkintonimike on waiter tai waitress.", true),
      job("Baarimestari", "Bartender", "Tutkintonimike. Tekee juomat ja vastaa baarista.", true),
      job("Vuorovastaava", "Shift leader", "Työmaasana. Vastaa salin tai keittiön vuorosta."),
      job("Keittiömestari", "Head chef", "Työmaasana. Johtaa keittiötä. Chef yksin voi tarkoittaa samaa."),
      job("Astianpesijä", "Kitchen porter", "Työmaasana. Brittienglannissa astianpesijä on usein kitchen porter."),
    ],
    terms: [
      word("allergen", "allergeeni", "turvallisuus"),
      word("reservation", "pöytävaraus", "paperit"),
      word("bill", "lasku", "paperit"),
      word("cover", "katettu asiakaspaikka", "paikat"),
      word("pass", "luukku", "paikat"),
      word("starter", "alkuruoka", "aineet"),
      word("main course", "pääruoka", "aineet"),
      word("well done", "läpikypsä", "aineet"),
      word("rare", "puolikypsä, punainen", "aineet"),
      word("section", "tarjoilualue", "paikat"),
      word("mise en place", "esivalmistelu", "välineet"),
      word("HACCP", "omavalvonta", "paperit"),
    ],
  },
  food: {
    qualification: {
      fi: "Elintarvikealan perustutkinto",
      en: "Vocational Qualification in Food Production",
    },
    occupations: [
      job("Elintarvikkeiden valmistaja", "Food Maker", "Tutkintonimike. Valmistaa ruokaa tehtaassa tai elintarvikehuoneistossa.", true),
      job("Leipuri-kondiittori", "Baker-confectioner", "Tutkintonimike. Leipoo ja tekee konditoriatuotteet.", true),
      job("Lihatuotteiden valmistaja", "Meat Products Processor", "Tutkintonimike. Käsittelee lihaa ja lihavalmisteita.", true),
      job("Meijeristi", "Dairyperson", "Tutkintonimike. Tekee maitotuotteita.", true),
      job("Leipuri", "Baker", "Työmaasana ja ammattitutkinnon nimike. Tekee leivät ja sämpylät."),
      job("Kondiittori", "Confectioner", "Työmaasana. Tekee kakut, leivokset ja suklaatyöt."),
      job("Pakkauslinjan hoitaja", "Packing line operator", "Työmaasana. Pakkaa tuotteen ja tarkistaa päiväyksen."),
      job("Laadunvalvoja", "Quality controller", "Työmaasana. Tarkistaa lämpötilan, painon ja ulkonäön."),
    ],
    terms: [
      word("cold room", "kylmiö", "paikat"),
      word("use-by date", "viimeinen käyttöpäivä", "paperit"),
      word("best-before date", "parasta ennen -päivä", "paperit"),
      word("hairnet", "päähine", "turvallisuus"),
      word("hygiene", "hygienia", "turvallisuus"),
      word("batch", "erä", "paperit"),
      word("recipe", "resepti", "paperit"),
      word("raw material", "raaka-aine", "aineet"),
      word("packaging", "pakkaus", "välineet"),
      word("temperature log", "lämpötilakirjanpito", "paperit"),
      word("cross-contamination", "ristikontaminaatio", "turvallisuus"),
      word("production line", "tuotantolinja", "paikat"),
    ],
  },
  tourism: {
    qualification: {
      fi: "Matkailualan perustutkinto",
      en: "Vocational Qualification in Tourism Industry",
    },
    occupations: [
      job("Matkailupalvelujen tuottaja", "Tourism Activities Organiser", "Tutkintonimike. Tekee ohjelmapalvelut ja retket.", true),
      job("Matkailun asiakaspalvelija", "Tourism Service Agent", "Tutkintonimike. Palvelee asiakasta myynnissä ja neuvonnassa.", true),
      job("Vastaanottovirkailija", "Receptionist", "Tutkintonimike. Tekee sisään- ja uloskirjauksen.", true),
      job("Matka-asiantuntija", "Travel Adviser", "Tutkintonimike. Myy matkoja ja neuvoo aikatauluissa.", true),
      job("Matkaopas", "Tourist Guide", "Tutkintonimike. Vetää kierroksen ja vastaa ryhmästä.", true),
      job("Hotellin vastaanottovirkailija", "Hotel receptionist", "Työmaasana. Sama työ kuin receptionist hotellissa."),
      job("Varaamo", "Reservations agent", "Työmaasana. Hoitaa huone- ja pöytävaraukset."),
      job("Kerrosemäntä", "Housekeeping supervisor", "Työmaasana. Johtaa siivousta hotellissa. Eri ammatti kuin kokki."),
    ],
    terms: [
      word("check-in", "sisäänkirjaus", "paperit"),
      word("check-out", "uloskirjaus", "paperit"),
      word("ground floor", "katutaso", "paikat"),
      word("first floor", "katutason yläpuolinen kerros", "paikat"),
      word("booking", "varaus", "paperit"),
      word("key card", "avainkortti", "välineet"),
      word("luggage", "matkatavarat", "välineet"),
      word("breakfast", "aamiainen", "aineet"),
      word("single room", "yhden hengen huone", "paikat"),
      word("double room", "kahden hengen huone", "paikat"),
      word("reception", "vastaanotto", "paikat"),
      word("itinerary", "matkaohjelma", "paperit"),
    ],
  },
  business: {
    qualification: {
      fi: "Liiketoiminnan perustutkinto",
      en: "Vocational Qualification in Business",
    },
    occupations: [
      job("Merkonomi", "Holder of a Vocational Qualification in Business", "Tutkintonimike. Se ei ole yksi työtehtävä vaan tutkinnon suorittaneen nimike.", true),
      job("Myyjä", "Salesperson", "Työmaasana. Myy tuotteen ja palvelee kassalla."),
      job("Asiakaspalvelija", "Customer service adviser", "Työmaasana. Vastaa puhelimeen, chattiin ja sähköpostiin."),
      job("Toimistoassistentti", "Office assistant", "Työmaasana. Hoitaa kalenterin, laskut ja arkiston."),
      job("Taloushallinnon assistentti", "Accounts assistant", "Työmaasana. Kirjaa laskut ja reskontran."),
      job("Vuoropäällikkö, myymälä", "Shift supervisor", "Työmaasana. Vastaa myymälän vuorosta."),
      job("Hankinta-assistentti", "Purchasing assistant", "Työmaasana. Tilaa tavaran ja seuraa toimituksia."),
      job("Markkinointiassistentti", "Marketing assistant", "Työmaasana. Tekee julkaisut ja kampanjamateriaalin."),
    ],
    terms: [
      word("invoice", "lasku", "paperit"),
      word("due date", "eräpäivä", "paperit"),
      word("attachment", "liite", "paperit"),
      word("meeting", "kokous", "paikat"),
      word("customer", "asiakas", "ihmiset"),
      word("order", "tilaus", "paperit"),
      word("receipt", "kuitti", "paperit"),
      word("discount", "alennus", "paperit"),
      word("enquiry", "tiedustelu", "paperit"),
      word("spreadsheet", "taulukko", "välineet"),
      word("deadline", "määräaika", "paperit"),
      word("complaint", "reklamaatio", "paperit"),
    ],
  },
  care: {
    qualification: {
      fi: "Sosiaali- ja terveysalan perustutkinto",
      en: "Vocational Qualification in Social and Health Care",
    },
    occupations: [
      job("Lähihoitaja", "Practical Nurse", "Suojattu tutkintonimike. Hoidon, hoivan ja kasvatuksen ammattilainen.", true),
      job("Perustason ensihoitaja", "Emergency Practical Nurse", "Tutkintonimike. Toimii ensihoidossa lähihoitajan pohjalta.", true),
      job("Lastenohjaaja", "Children's Instructor", "Tutkintonimike. Ohjaa lapsia varhaiskasvatuksessa.", true),
      job("Hoiva-avustaja", "Care assistant", "Työmaasana. Auttaa arjessa, mutta ei ole suojattu nimike niin kuin practical nurse."),
      job("Sairaanhoitaja", "Registered Nurse", "AMK-tutkinto, ei perustutkinto. Lähihoitajan pitää erottaa nämä nimikkeet."),
      job("Lääkäri", "Doctor", "Työmaasana. Vocational Englishissä sanotaan doctor, ei physician, ellei teksti ole virallinen."),
      job("Omaishoitaja", "Family carer", "Työmaasana. Hoitaa läheistä kotona. Ei ole sama kuin practical nurse."),
      job("Osastonhoitaja", "Ward manager", "Työmaasana. Johtaa osastoa. Nimike on yleensä sairaanhoitajalla."),
    ],
    terms: [
      word("pain", "kipu", "turvallisuus"),
      word("blood pressure", "verenpaine", "välineet"),
      word("medication", "lääkitys", "turvallisuus"),
      word("prescription", "lääkemääräys", "paperit"),
      word("handover", "raportti vuoronvaihdossa", "paperit"),
      word("consent", "lupa", "paperit"),
      word("fall", "kaatuminen", "turvallisuus"),
      word("resident", "asukas", "ihmiset"),
      word("patient", "potilas", "ihmiset"),
      word("ward", "osasto", "paikat"),
      word("care plan", "hoitosuunnitelma", "paperit"),
      word("gloves", "suojakäsineet", "turvallisuus"),
    ],
  },
  beauty: {
    qualification: {
      fi: "Hius- ja kauneudenhoitoalan perustutkinto",
      en: "Vocational Qualification in Hairdressing and Beauty Care",
    },
    occupations: [
      job("Parturi-kampaaja", "Hairdresser", "Tutkintonimike. Leikkaa, värjää ja viimeistelee hiukset.", true),
      job("Parturi", "Barber", "Tutkintonimike. Tekee miesten leikkaukset ja parran.", true),
      job("Kosmetologi", "Beauty Therapist", "Tutkintonimike. Tekee kasvo- ja kehonhoidot.", true),
      job("Kosmetiikkaneuvoja", "Beauty Consultant", "Tutkintonimike. Myy ja neuvoo ihonhoidossa.", true),
      job("Kynsiteknikko", "Nail technician", "Työmaasana. Tekee kynsihuollot. Ei ole sama tutkintonimike kuin kosmetologi."),
      job("Värjääjä", "Colourist", "Työmaasana. Erikoistuu hiusväreihin."),
      job("Vastaanottovirkailija, salonki", "Salon receptionist", "Työmaasana. Varaa ajat ja ottaa asiakkaan vastaan."),
      job("Kauneushoitaja", "Beautician", "Työmaasana. Lähellä beauty therapist -nimikettä, asiakas ymmärtää tämänkin."),
    ],
    terms: [
      word("appointment", "aika", "paperit"),
      word("patch test", "allergeenitesti", "turvallisuus"),
      word("colour", "hiusväri", "aineet"),
      word("bleach", "vaalennusaine", "turvallisuus"),
      word("cut", "leikkaus", "välineet"),
      word("fringe", "otsatukka", "välineet"),
      word("blow-dry", "föönaus", "välineet"),
      word("treatment", "hoito", "välineet"),
      word("skin type", "ihotyyppi", "paperit"),
      word("consultation", "kartoitus", "paperit"),
      word("salon", "liike", "paikat"),
      word("allergy", "allergia", "turvallisuus"),
    ],
  },
  cleaning: {
    qualification: {
      fi: "Puhtaus- ja kiinteistöpalvelualan perustutkinto",
      en: "Vocational Qualification in Cleaning and Property Services",
    },
    occupations: [
      job("Toimitilahuoltaja", "Site Facilities Operative", "Tutkintonimike. Siivoaa ja hoitaa toimitiloja.", true),
      job("Kodinhuoltaja", "Housekeeper", "Tutkintonimike. Tekee kotityöpalveluja.", true),
      job("Laitoshuoltaja", "Institutional Cleaner", "Tutkintonimike ammattitutkinnossa. Siivoaa sairaaloita ja laitoksia.", true),
      job("Siivooja", "Cleaner", "Työmaasana. Asiakas sanoo näin, tutkintonimike on pidempi."),
      job("Siivoustyönjohtaja", "Cleaning supervisor", "Työmaasana. Jakaa alueet ja tarkistaa laadun."),
      job("Erityissiivouksen tekijä", "Specialist cleaner", "Työmaasana. Tekee rakennussiivouksen tai desinfioinnin."),
      job("Hotellisiivooja", "Room attendant", "Työmaasana. Siiivoaa hotellihuoneet. Housekeeper voi tarkoittaa esihenkilöä."),
      job("Välinehuoltaja", "Equipment attendant", "Työmaasana. Huoltaa siivouskoneet ja annostelee aineet."),
    ],
    terms: [
      word("detergent", "pesuaine", "aineet"),
      word("bleach", "kloorivalkaisuaine", "turvallisuus"),
      word("wet floor sign", "märän lattian kyltti", "turvallisuus"),
      word("microfibre cloth", "mikrokuituliina", "välineet"),
      word("mop", "moppi", "välineet"),
      word("dosage", "annostus", "turvallisuus"),
      word("safety data sheet", "käyttöturvallisuustiedote", "paperit"),
      word("surface", "pinta", "paikat"),
      word("changing room", "pukuhuone", "paikat"),
      word("waste", "jäte", "aineet"),
      word("gloves", "suojakäsineet", "turvallisuus"),
      word("work area", "työalue", "paikat"),
    ],
  },
  security: {
    qualification: {
      fi: "Turvallisuusalan perustutkinto",
      en: "Vocational Qualification in Safety and Security",
    },
    occupations: [
      job("Turvallisuusvalvoja", "Security Officer", "Tutkintonimike. Valvoo kiinteistöä, kulkua ja järjestystä.", true),
      job("Vartija", "Security guard", "Työmaasana. Asiakas sanoo näin. Tutkintonimike on Security Officer."),
      job("Vastaanoton vartija", "Reception security officer", "Työmaasana. Tarkistaa kulkuluvat aulassa."),
      job("Kierrosvartija", "Patrol officer", "Työmaasana. Tekee tarkastuskierroksen."),
      job("Hälytyskeskuspäivystäjä", "Alarm receiving operator", "Työmaasana. Vastaa hälytyksiin keskuksessa."),
      job("Järjestyksenvalvoja", "Steward", "Työmaasana tapahtumissa. Crowd safety steward on selvämpi pitkä muoto."),
      job("Myymälätarkkailija", "Store detective", "Työmaasana. Valvoo myymälävarkauksia."),
      job("Turvallisuuspäällikkö", "Security manager", "Työmaasana. Johtaa vartiointia kohteessa."),
    ],
    terms: [
      word("ID", "henkilöllisyystodistus", "paperit"),
      word("access card", "kulkukortti", "välineet"),
      word("tailgating", "perässä tuleminen ovesta", "turvallisuus"),
      word("exit", "uloskäynti", "paikat"),
      word("incident report", "tapahtumaraportti", "paperit"),
      word("alarm", "hälytys", "turvallisuus"),
      word("visitors' book", "vieraskirja", "paperit"),
      word("CCTV", "kameravalvonta", "välineet"),
      word("patrol", "kierros", "paikat"),
      word("evacuation", "poistuminen", "turvallisuus"),
      word("reception", "aula", "paikat"),
      word("radio", "viranomaisradio", "välineet"),
    ],
  },
  agriculture: {
    qualification: {
      fi: "Maatalousalan perustutkinto",
      en: "Vocational Qualification in Agriculture",
    },
    occupations: [
      job("Maaseutuyrittäjä", "Rural Entrepreneur", "Tutkintonimike. Pitää maatilaa tai muuta maaseutuyritystä.", true),
      job("Eläintenhoitaja", "Animal Attendant", "Tutkintonimike. Hoitaa tuotanto- tai harraste-eläimiä.", true),
      job("Maatilatyöntekijä", "Agricultural worker", "Työmaasana ja ammattitutkinnon nimike. Tekee navetta- ja peltotyöt."),
      job("Tuotantoeläintenhoitaja", "Farm animal attendant", "Työmaasana. Hoitaa lehmiä, sikoja tai siipikarjaa."),
      job("Maatalouslomittaja", "Farm relief worker", "Työmaasana. Sijastaa viljelijän lomalla."),
      job("Traktorinkuljettaja", "Tractor driver", "Työmaasana. Ajaa peltotyöt ja rehukuljetukset."),
      job("Maatalouskoneasentaja", "Agricultural machinery technician", "Työmaasana. Huoltaa traktorit ja työkoneet."),
      job("Puutarhuri", "Gardener", "Tutkintonimike puutarhapuolella. Kasvattaa ja hoitaa kasvit.", true),
    ],
    terms: [
      word("cattle", "nauta", "eläimet"),
      word("barn", "navetta", "paikat"),
      word("pasture", "laidun", "paikat"),
      word("fence", "aita", "välineet"),
      word("gate", "portti", "välineet"),
      word("tractor", "traktori", "välineet"),
      word("feed", "rehu", "aineet"),
      word("milking", "lypsy", "välineet"),
      word("crop", "sato", "aineet"),
      word("frost", "halla", "turvallisuus"),
      word("livestock", "karja", "eläimet"),
      word("slurry", "liete", "turvallisuus"),
    ],
  },
  forestry: {
    qualification: {
      fi: "Metsäalan perustutkinto",
      en: "Vocational Qualification in Forestry",
    },
    occupations: [
      job("Metsäkoneenkuljettaja", "Forest Machine Operator", "Tutkintonimike. Ajaa hakkuu- tai ajokonetta.", true),
      job("Metsuri", "Forest worker", "Työmaasana. Kaataa puut moottorisahalla. Tutkintonimike on metsuri-metsäpalvelujen tuottaja."),
      job("Metsäkoneasentaja", "Forest machine mechanic", "Työmaasana. Huoltaa hakkuu- ja ajokoneet metsässä ja hallilla."),
      job("Puutavara-autonkuljettaja", "Timber truck driver", "Työmaasana. Ajaa puutavaran tehtaalle. Brittienglannissa timber, ei lumber."),
      job("Metsäpalvelujen tuottaja", "Forest services producer", "Tutkintonimikkeen osa. Tekee istutusta, raivausta ja metsänhoitoa."),
      job("Toimihenkilö, metsä", "Forest officer", "Työmaasana. Suunnittelee leimikon ja ostaa puuta."),
      job("Istuttaja", "Tree planter", "Työmaasana. Istuttaa taimet."),
      job("Raivaaja", "Clearing saw operator", "Työmaasana. Raivaa taimikon."),
    ],
    terms: [
      word("chainsaw", "moottorisaha", "välineet"),
      word("felling", "kaato", "turvallisuus"),
      word("escape route", "pakoreitti", "turvallisuus"),
      word("harvester", "hakkuukone", "välineet"),
      word("forwarder", "ajokone", "välineet"),
      word("timber", "puutavara", "aineet"),
      word("stand", "metsikkö", "paikat"),
      word("seedling", "taimi", "aineet"),
      word("high-visibility clothing", "huomioliivi ja huomioasu", "turvallisuus"),
      word("chainsaw trousers", "turvahousut", "turvallisuus"),
      word("landing", "varastopaikka", "paikat"),
      word("windthrow", "tuulenkaato", "turvallisuus"),
    ],
  },
  ict: {
    qualification: {
      fi: "Tieto- ja viestintätekniikan perustutkinto",
      en: "Vocational Qualification in Information and Communications Technology",
    },
    occupations: [
      job("Tietoverkkoasentaja", "Network Installer", "Tutkintonimike. Vetää kaapelit ja kytkee verkot.", true),
      job("IT-tukihenkilö", "IT Support Specialist", "Tutkintonimike. Auttaa käyttäjiä ja kirjaa tiketit.", true),
      job("Ohjelmistokehittäjä", "Software Developer", "Tutkintonimike. Tekee ja korjaa ohjelmia.", true),
      job("ICT-asentaja", "ICT Technician", "Tutkintonimike. Asentaa laitteet, päätelaitteet ja lähituen.", true),
      job("Elektroniikka-asentaja", "Electronics Assembler", "Tutkintonimike. Kokoaa ja testaa elektroniikkaa.", true),
      job("Pelituotannon toteuttaja", "Implementer of Game Production", "Tutkintonimike. Tekee pelin osia tuotannossa.", true),
      job("Käyttäjätuki", "Help desk analyst", "Työmaasana. Vastaa ensimmäiseen yhteydenottoon."),
      job("Järjestelmänvalvoja", "System administrator", "Työmaasana. Pitää palvelimet ja tunnukset kunnossa."),
    ],
    terms: [
      word("ticket", "tukipyyntö", "paperit"),
      word("password", "salasana", "turvallisuus"),
      word("outage", "käyttökatko", "turvallisuus"),
      word("backup", "varmuuskopio", "paperit"),
      word("server", "palvelin", "välineet"),
      word("network", "tietoverkko", "välineet"),
      word("update", "päivitys", "välineet"),
      word("user account", "käyttäjätili", "paperit"),
      word("router", "reititin", "välineet"),
      word("cable", "kaapeli", "välineet"),
      word("help desk", "käyttäjätuki", "paikat"),
      word("data protection", "tietosuoja", "turvallisuus"),
    ],
  },
  media: {
    qualification: {
      fi: "Media-alan perustutkinto",
      en: "Vocational Qualification in Media and Visual Expression",
    },
    occupations: [
      job("Mediapalvelujen toteuttaja", "Implementer of Media Services", "Tutkintonimike. Medianomi on opiskelijan arkinimitys, tämä on luettelon englanninkielinen vastine.", true),
      job("Valokuvaaja", "Photographer", "Ammattitutkinnon nimike. Kuvaa still-kuvat.", true),
      job("Videoeditoija", "Video editor", "Työmaasana. Leikkaa kuvan ja äänen."),
      job("Kuuluttaja-juontaja", "Presenter", "Työmaasana. Juontaa lähetyksen tai tallenteen."),
      job("Graafinen suunnittelija", "Graphic designer", "Työmaasana. Tekee taiton, logon ja somepohjat."),
      job("Äänitarkkailija", "Sound technician", "Työmaasana. Hoitaa äänen nauhoituksessa ja tapahtumassa."),
      job("Tuotantoassistentti", "Production assistant", "Työmaasana. Hoitaa aikataulun, luvat ja kuvauspaikan."),
      job("Journalistiharjoittelija", "Trainee journalist", "Työmaasana. Tekee jutun, mutta medianomi ei automaattisesti ole journalisti."),
    ],
    terms: [
      word("deadline", "määräaika", "paperit"),
      word("brief", "briiffi", "paperit"),
      word("copyright", "tekijänoikeus", "paperit"),
      word("subtitle", "tekstitys", "paperit"),
      word("shot", "kuva", "välineet"),
      word("edit", "leikkaus", "välineet"),
      word("interview", "haastattelu", "ihmiset"),
      word("script", "käsikirjoitus", "paperit"),
      word("studio", "studio", "paikat"),
      word("release form", "julkaisulupa", "paperit"),
      word("footage", "kuvamateriaali", "aineet"),
      word("caption", "kuvateksti", "paperit"),
    ],
  },
  textile: {
    qualification: {
      fi: "Tekstiili- ja muotialan perustutkinto",
      en: "Vocational Qualification in Textiles and Fashion",
    },
    occupations: [
      job("Ompelija", "Seamster", "Tutkintonimike luettelossa on Seamster. Verstaalla kuulee useammin sewing machinist.", true),
      job("Mittatilausompelija", "Dressmaker", "Tutkintonimike. Tekee vaatteen mittojen mukaan.", true),
      job("Muotiassistentti", "Fashion Assistant", "Tutkintonimike. Avustaa suunnittelussa, sovituksessa ja mallistossa.", true),
      job("Tekstiilien valmistaja", "Textiles Maker", "Tutkintonimike. Valmistaa tekstiilituotteita.", true),
      job("Vaatturi", "Tailor", "Tutkintonimike. Tekee miesten pukuja ja korjauksia mittatilaustyönä.", true),
      job("Modisti", "Milliner", "Tutkintonimike. Tekee hatut.", true),
      job("Suutari", "Shoemaker", "Tutkintonimike. Tekee ja korjaa jalkineet.", true),
      job("Mallimestari", "Pattern cutter", "Työmaasana. Tekee kaavat. Pattern on kaava, ei vain kuvio."),
    ],
    terms: [
      word("hem", "helma", "välineet"),
      word("seam", "sauma", "välineet"),
      word("waist", "vyötärö", "välineet"),
      word("pattern", "kaava", "paperit"),
      word("fabric", "kangas", "aineet"),
      word("thread", "lanka", "aineet"),
      word("sewing machine", "ompelukone", "välineet"),
      word("fitting", "sovitus", "paikat"),
      word("care label", "pesuohje", "paperit"),
      word("measurement", "mitta", "paperit"),
      word("lining", "vuori", "aineet"),
      word("zip", "vetoketju", "välineet"),
    ],
  },
};

const packs = Object.entries(TRADE) as [FieldId, TradePack][];

function assertTrade(): void {
  if (packs.length !== FIELD_IDS.length) {
    throw new Error("Ammattipaketteja ja aloja on eri määrä.");
  }
  for (const fieldId of FIELD_IDS) {
    const pack = TRADE[fieldId];
    if (!pack) throw new Error(`Ammattipaketti puuttuu: ${fieldId}`);
    if (pack.occupations.length < 8) throw new Error(`Nimikkeitä liian vähän: ${fieldId}`);
    if (pack.terms.length < 10) throw new Error(`Sanoja liian vähän: ${fieldId}`);
    const titles = new Set(pack.occupations.map((item) => item.en));
    if (titles.size !== pack.occupations.length) throw new Error(`Sama nimike kahdesti: ${fieldId}`);
    const words = new Set(pack.terms.map((item) => item.en));
    if (words.size !== pack.terms.length) throw new Error(`Sama sana kahdesti: ${fieldId}`);
    if (pack.qualification.fi.length < 8 || pack.qualification.en.length < 8) {
      throw new Error(`Tutkinnon nimi puuttuu: ${fieldId}`);
    }
  }
}

assertTrade();

export function getTrade(id: FieldId): TradePack {
  return TRADE[id];
}
