import { options, task } from "../field-pack";
import type { Question } from "@/lib/types";

export const movementFieldQuestions: Question[] = [
  task({
    id: "log-01",
    fieldId: "logistics",
    skillId: "word-order",
    difficulty: 2,
    level: "A2",
    prompt: "Olet vienyt lavan perille. Mitä pyydät vastaanottajalta?",
    choices: options(
      ["Please sign for the delivery.", "Sign for on kuitata vastaanotetuksi."],
      ["Please sign the delivering.", "Delivering ei ole asiakirja."],
      ["Sign you the delivery.", "Sanajärjestys on väärin."],
      ["Please sign about the delivery.", "About ei ole tämän fraasin prepositio."],
    ),
    answer: "a",
    rule: "Kuittaus on sign for the delivery.",
    why: "Sign for tarkoittaa, että vastaanottaja kuittaa lähetyksen. About the delivery kuulostaisi keskustelulta, ei kuittaukselta.",
    example: "Can you sign for these two pallets?",
    trap: "Suomen 'kuittaa' ei näytä sanaa for. Englannissa se on sign for.",
  }),
  task({
    id: "log-02",
    fieldId: "logistics",
    skillId: "present",
    difficulty: 2,
    level: "A2",
    prompt: "Rekka on jumissa satamassa. Miten ilmoitat asiakkaalle?",
    choices: options(
      ["The shipment is delayed.", "Delayed on myöhässä."],
      ["The shipment is delay.", "Delay on substantiivi, ei tilan kuvaus näin."],
      ["The shipment delayed.", "Verbi be puuttuu."],
      ["The shipment is delaying you.", "Tekijä kääntyy väärin."],
    ),
    answer: "a",
    rule: "Myöhästynyt lähetys: The shipment is delayed.",
    why: "Is delayed on passiivinen tila. Is delaying you syyttäisi asiakasta, vaikka vika on kuljetuksessa.",
    example: "The delivery is delayed by two hours.",
    trap: "Delay ja delayed eivät vaihdu. Tilaan tarvitaan delayed.",
  }),
  task({
    id: "log-03",
    fieldId: "logistics",
    skillId: "word-order",
    difficulty: 2,
    level: "A2",
    prompt: "Trukki peruuttaa lastauslaiturilla. Mitä huudat?",
    choices: options(
      ["Look behind you before you reverse.", "Katse taakse ennen peruutusta."],
      ["Reverse first and look later.", "Myöhemmin katsominen on liian myöhäistä."],
      ["Look you behind.", "Sanajärjestys on väärin."],
      ["Behind looking the truck.", "Ei ole käsky."],
    ),
    answer: "a",
    rule: "Peruutusohje: Look behind you before you reverse.",
    why: "Before you reverse pitää katsomisen ensimmäisenä. Later on se hetki, jolloin kolhu on jo tapahtunut.",
    example: "Sound the horn before you reverse.",
    trap: "Behind you on 'taaksesi'. Behind the you ei ole englantia.",
  }),
  task({
    id: "log-04",
    fieldId: "logistics",
    skillId: "articles",
    difficulty: 3,
    level: "B1",
    prompt: "Kolli on merkitty särkyväksi. Mikä merkintä on oikea?",
    choices: options(
      ["Fragile. This side up.", "Molemmat ovat oikeita kollimerkintöjä."],
      ["Fragile. This side upper.", "Upper ei ole merkinnän sana."],
      ["Broken. This side up.", "Broken väittäisi, että tavara on jo rikki."],
      ["Fragile side this up.", "Sanajärjestys ei ole painettu ohje."],
    ),
    answer: "a",
    rule: "Särkyvä ja suunta: Fragile. This side up.",
    why: "This side up kertoo, mikä kylki tulee ylös. Broken tarkoittaisi, että vahinko on jo tapahtunut, eikä sitä kirjoiteta ehjään laatikkoon.",
    example: "Handle with care.",
    trap: "Upper on 'ylempi', ei kollin yläreuna. Merkintä on up.",
  }),
  task({
    id: "log-05",
    fieldId: "logistics",
    skillId: "present",
    difficulty: 3,
    level: "B1",
    prompt: "Rahtikirja puuttuu. Miten sanot sen?",
    choices: options(
      ["The consignment note is missing.", "Consignment note on rahtikirja."],
      ["The consignment note is missed.", "Missed kuulostaisi ikävöidyltä."],
      ["A consignment note are missing.", "Yksikkö ja monikko eivät täsmää."],
      ["The note of train is missing.", "Train ei tee asiakirjasta rahtikirjaa."],
    ),
    answer: "a",
    rule: "Puuttuva paperi on missing: The consignment note is missing.",
    why: "Missing tarkoittaa, ettei paperia ole. Missed tarkoittaisi kaivattua tai ohi mennyttä. Consignment note on se asiakirja, jota terminaalissa kysytään.",
    example: "The delivery note is missing a signature.",
    trap: "Suomen 'rahtikirja' ei ole train letter. Se on consignment note tai waybill.",
  }),
  task({
    id: "log-06",
    fieldId: "logistics",
    skillId: "word-order",
    difficulty: 1,
    level: "A2",
    prompt: "Kirjoita pyyntö: kuittaa toimitus.",
    sentence: "Please ___ for the delivery.",
    kind: "cloze",
    choices: [],
    answer: "sign",
    accept: ["sign"],
    fill: "sign",
    rule: "Kuittauspyyntö on Please sign for the delivery.",
    why: "Sign for the delivery on varaston ja kuljetuksen peruslause. For kuuluu mukaan.",
    example: "Sign here for the pallet.",
    trap: "Älä kirjoita sign the delivery, jos tarkoitus on kuittaus.",
  }),

  task({
    id: "sea-01",
    fieldId: "maritime",
    skillId: "modals",
    difficulty: 4,
    level: "B2",
    prompt: "Alus on uppoamassa ja tarvitsette apua heti. Mikä kutsu on oikea?",
    choices: options(
      ["Mayday. We need immediate help.", "Mayday on välitön hätä."],
      ["Pan-pan. We need immediate help.", "Pan-pan on kiireellinen, ei uppoaminen."],
      ["Hello. We need immediate help.", "Hello ei ole hätäkutsu."],
      ["Mayday maybe later.", "Maybe kumoaa hätäsanoman."],
    ),
    answer: "a",
    rule: "Välitön hätä on Mayday. Kiireellinen mutta ei välitön vaara on pan-pan.",
    why: "Mayday käynnistää pelastuksen. Pan-pan olisi oikea, jos koneessa on vika mutta alus ei ole välittömässä vaarassa. Maybe ei kuulu hätäkutsuun.",
    example: "Mayday, Mayday, Mayday. This is ferry Aurora.",
    trap: "Älä käytä Maydayta harjoitteluun radiossa. Harjoituksessa sanotaan, että kyse on drillistä.",
  }),
  task({
    id: "sea-02",
    fieldId: "maritime",
    skillId: "word-order",
    difficulty: 3,
    level: "B1",
    prompt: "Henkilö putosi styyrpuurin puolelta. Mitä huudat?",
    choices: options(
      ["Man overboard, starboard side.", "Puoli pitää sanoa heti."],
      ["Man overboard somewhere.", "Somewhere ei riitä käännökseen."],
      ["Overboard man the starboard.", "Sanajärjestys ei ole hätähuuto."],
      ["A man is boarding on starboard.", "Boarding on nouseminen alukseen."],
    ),
    answer: "a",
    rule: "Hätähuuto on Man overboard ja heti puoli: starboard side tai port side.",
    why: "Starboard side kertoo, minne käännytään. Somewhere kadottaa sekunnit. Boarding tarkoittaisi, että joku tulee alukseen, ei että joku putosi.",
    example: "Man overboard, port side.",
    trap: "Port on vasen, starboard on oikea keulasta katsottuna. Niitä ei arvata.",
  }),
  task({
    id: "sea-03",
    fieldId: "maritime",
    skillId: "word-order",
    difficulty: 2,
    level: "A2",
    prompt: "Olette tulossa laituriin. Mitä sanot köysimiehille?",
    choices: options(
      ["Stand by the lines.", "Stand by on olkaa valmiina."],
      ["Stand the lines by.", "By ei siirry noin."],
      ["Sit by the lines.", "Sit on istua, ei valmiusasento."],
      ["Stand by a line the.", "Artikkelit ovat sekaisin."],
    ),
    answer: "a",
    rule: "Valmius köysillä: Stand by the lines.",
    why: "Stand by the lines on kansikäsky. Sit by the lines kuulostaisi levolta, ei kiinnitykseltä.",
    example: "Stand by the spring line.",
    trap: "Stand by on fraasi. Sitä ei käännetä sanajärjestyksellä stand the lines by.",
  }),
  task({
    id: "sea-04",
    fieldId: "maritime",
    skillId: "present",
    difficulty: 3,
    level: "B1",
    prompt: "Luovutat vahdin. Mikä lause kuuluu alkuun?",
    choices: options(
      ["I am handing over the watch.", "Hand over on luovuttaa vuoro."],
      ["I am handing in the watch.", "Hand in on palauttaa tavara."],
      ["I hand over the watch yesterday.", "Yesterday ei sovi tähän muotoon."],
      ["The watch hands me over.", "Tekijä on väärin."],
    ),
    answer: "a",
    rule: "Vahdin luovutus on hand over the watch.",
    why: "Hand over on vuoron tai vastuun siirto. Hand in olisi lomakkeen tai tavaran palautus. Vahdissa vastuu siirtyy seuraavalle.",
    example: "I am handing over the watch. The radar is on.",
    trap: "Over ja in muuttavat verbin merkityksen.",
  }),
  task({
    id: "sea-05",
    fieldId: "maritime",
    skillId: "prepositions",
    difficulty: 2,
    level: "A2",
    prompt: "Tupakointi on kielletty säiliöiden lähellä. Miten sen sanot?",
    sentence: "Do not smoke ___ the tanks.",
    choices: options(
      ["near", "Near the tanks on säiliöiden lähellä."],
      ["nearly", "Nearly tarkoittaa melkein."],
      ["next", "Next tarvitsee to: next to."],
      ["under", "Under olisi säiliöiden alla."],
    ),
    answer: "a",
    rule: "Lähellä on near: Do not smoke near the tanks.",
    why: "Near on prepositio. Nearly on adverbi ja tarkoittaa melkein, joten se ei paikanna tupakointia.",
    example: "No smoking near the fuel hose.",
    trap: "Near ja nearly näyttävät samalta. Vain near sopii paikan eteen.",
  }),
  task({
    id: "sea-06",
    fieldId: "maritime",
    skillId: "word-order",
    difficulty: 3,
    level: "B1",
    prompt: "Kirjoita hätähuuto: mies yli laidan, styyrpuuri.",
    sentence: "Man overboard, ___ side.",
    kind: "cloze",
    choices: [],
    answer: "starboard",
    accept: ["starboard"],
    fill: "starboard",
    rule: "Puoli sanotaan heti: Man overboard, starboard side.",
    why: "Starboard side on oikea kylki keulasta katsottuna. Ilman puolta kansi ei tiedä, minne katsoa.",
    example: "Man overboard, port side.",
    trap: "Älä kirjoita right side, jos aluksella käytetään sanaa starboard.",
  }),

  task({
    id: "farm-01",
    fieldId: "agriculture",
    skillId: "present",
    difficulty: 2,
    level: "A2",
    prompt: "Lehmä ei varaa painoa toiselle jalalle. Mitä sanot?",
    choices: options(
      ["The cow is lame.", "Lame on ontuva."],
      ["The cow is lazy.", "Lazy on laiska."],
      ["The cow is lamb.", "Lamb on karitsa."],
      ["The cow lames.", "Lame ei taivu verbinä näin."],
    ),
    answer: "a",
    rule: "Ontuva eläin on lame: The cow is lame.",
    why: "Lame on eläinlääkärin ja navetan sana. Lazy kuvaisi käytöstä, lamb on eri eläin.",
    example: "The front left leg is lame.",
    trap: "Lame ja lazy eivät kuvaa samaa vikaa.",
  }),
  task({
    id: "farm-02",
    fieldId: "agriculture",
    skillId: "modals",
    difficulty: 2,
    level: "A2",
    prompt: "Traktori peruuttaa pihalla. Mitä sanot harjoittelijalle?",
    choices: options(
      ["Do not stand behind the tractor.", "Kuollut kulma on traktorin takana."],
      ["Stand behind the tractor so he can see you.", "Takana seisominen ei näy kuljettajalle."],
      ["Do not to stand behind.", "Do not ei saa to-sanaa."],
      ["The tractor stands you behind.", "Tekijä on väärin."],
    ),
    answer: "a",
    rule: "Kielto on Do not stand behind the tractor.",
    why: "Behind the tractor on vaaravyöhyke. So he can see you on väärä neuvo, koska kuljettaja ei näe taakse ilman peiliä ja katsomista.",
    example: "Keep away from the PTO shaft.",
    trap: "Behind ei ole beside. Beside olisi sivulla.",
  }),
  task({
    id: "farm-03",
    fieldId: "agriculture",
    skillId: "present",
    difficulty: 2,
    level: "A2",
    prompt: "Aita on kaatunut ja eläimet voivat karata. Miten ilmoitat?",
    choices: options(
      ["The fence is down.", "Down on poikki tai kaatunut."],
      ["The fence is downstairs.", "Downstairs on alempi kerros."],
      ["Fence down is the.", "Sanajärjestys on väärin."],
      ["The fence downs.", "Down ei ole verbi tässä."],
    ),
    answer: "a",
    rule: "Kaatunut aita: The fence is down.",
    why: "Is down on lyhyt ja selvä. Downstairs veisi aidan rakennuksen sisään.",
    example: "The gate is open.",
    trap: "Down ja downstairs eivät ole sama paikka.",
  }),
  task({
    id: "farm-04",
    fieldId: "agriculture",
    skillId: "future",
    difficulty: 3,
    level: "B1",
    prompt: "Ennuste lupaa hallaa yölle. Mitä sanot aamulypsyn jälkeen?",
    choices: options(
      ["The forecast says there will be frost tonight.", "Will be sopii ennusteeseen."],
      ["The forecast says there was frost tonight.", "Was on mennyttä, tonight on tuleva yö."],
      ["The forecast says frost will tonight.", "Verbi be puuttuu."],
      ["Forecast say a frost.", "Yksikköverbi ja artikkeli ovat pielessä."],
    ),
    answer: "a",
    rule: "Ennuste tulevasta: The forecast says there will be frost tonight.",
    why: "Will be frost tonight on tuleva sää. Was frost tonight sekoittaa menneen ja tämän yön.",
    example: "There will be heavy rain this afternoon.",
    trap: "Says ei muutu sayksi, kun tekijä on forecast.",
  }),
  task({
    id: "farm-05",
    fieldId: "agriculture",
    skillId: "word-order",
    difficulty: 1,
    level: "A2",
    prompt: "Vasikat ruokitaan ennen muita. Miten sanot järjestyksen?",
    choices: options(
      ["Feed the calves first.", "First lopussa kertoo järjestyksen."],
      ["Feed first the calves.", "First ei halkaise käskyä noin."],
      ["The calves feed you first.", "Tekijä kääntyy väärin."],
      ["Feeding the calves.", "Ei ole käsky."],
    ),
    answer: "a",
    rule: "Työjärjestys on käsky plus first: Feed the calves first.",
    why: "Feed the calves first on navetan aamujärjestys. The calves feed you tarkoittaisi, että vasikat ruokkivat sinut.",
    example: "Close the parlour door first.",
    trap: "Englannin käsky ei ala sanalla first verbin väliin tungettuna.",
  }),
  task({
    id: "farm-06",
    fieldId: "agriculture",
    skillId: "word-order",
    difficulty: 1,
    level: "A2",
    prompt: "Kirjoita portin ohje.",
    sentence: "___ the gate behind you.",
    kind: "cloze",
    choices: [],
    answer: "Shut",
    accept: ["shut", "Close", "close"],
    fill: "Shut",
    rule: "Porttikäsky on Shut the gate behind you.",
    why: "Behind you muistuttaa, että portti suljetaan omalta puolelta, ei jätetä auki selän taakse.",
    example: "Shut the gate after the herd.",
    trap: "Gate shut ei ole käsky.",
  }),

  task({
    id: "for-01",
    fieldId: "forestry",
    skillId: "word-order",
    difficulty: 3,
    level: "B1",
    prompt: "Ennen loveusta pitää olla pakoreitti. Mitä sanot?",
    choices: options(
      ["Clear the escape route before you cut.", "Reitti auki ennen sahausta."],
      ["Cut first and clear the route if the tree moves.", "Silloin reittiä ei ehdi avata."],
      ["Clearing the escape route.", "Ei ole täysi käsky."],
      ["Escape the route clear.", "Sanat ovat väärässä järjestyksessä."],
    ),
    answer: "a",
    rule: "Ennen kaatoa: Clear the escape route before you cut.",
    why: "Before you cut on ehdoton järjestys. If the tree moves on liian myöhään, koska puu on jo liikkeessä.",
    example: "Plan the escape route at 45 degrees behind you.",
    trap: "Escape route on pakoreitti. Escape the route ei tarkoita samaa.",
  }),
  task({
    id: "for-02",
    fieldId: "forestry",
    skillId: "comparison",
    difficulty: 2,
    level: "A2",
    prompt: "Tuuli on kova eikä latva pysy hallinnassa. Mitä ilmoitat?",
    choices: options(
      ["Stop work. The wind is too strong.", "Too strong keskeyttää kaadon."],
      ["Stop work. The wind is too strongly.", "Strongly on tapa, ei tuulen voima."],
      ["Continue. The wind is too strong.", "Continue ja too strong riitelevät."],
      ["The wind is strong too much.", "Too much strong ei ole englantia."],
    ),
    answer: "a",
    rule: "Liian kova tuuli: The wind is too strong. Työ keskeytetään: Stop work.",
    why: "Too strong on adjektiivi. Strongly kuvaisi tekemistä voimakkaasti. Continue kumoaisi keskeytyksen.",
    example: "The gusts are too strong for felling.",
    trap: "Too much ei tule adjektiivin eteen. Sano too strong.",
  }),
  task({
    id: "for-03",
    fieldId: "forestry",
    skillId: "articles",
    difficulty: 2,
    level: "A2",
    prompt: "Sahuri on ilman turvahousuja. Mitä sanot?",
    choices: options(
      ["Wear chainsaw trousers.", "Chainsaw trousers on turvahousut."],
      ["Wear chainsaw trouser.", "Housut ovat monikossa."],
      ["Wear a chainsaw trouser the.", "Artikkeli on väärässä paikassa."],
      ["Wear chainsaw pants of office.", "Office ei kuulu metsään."],
    ),
    answer: "a",
    rule: "Turvahousut ovat monikko: chainsaw trousers.",
    why: "Trousers on aina monikko, kuten pants. Yksikkö trouser ei kuvaa vaatetta. Office pants veisi housut toimistoon.",
    example: "Wear a helmet with a visor.",
    trap: "Brittienglannissa trousers. Pants on läheinen, mutta trousers on selvä työvaate.",
  }),
  task({
    id: "for-04",
    fieldId: "forestry",
    skillId: "future",
    difficulty: 2,
    level: "A2",
    prompt: "Näytät kaatosuunnan. Mikä lause on selvä?",
    choices: options(
      ["The tree will fall that way.", "Will fall on tuleva suunta."],
      ["The tree fell that way.", "Fell on jo tapahtunut kaato."],
      ["The tree will fall yesterday.", "Yesterday ei ole tulevaa."],
      ["That way falls the tree.", "Sanajärjestys on runollinen, ei työohje."],
    ),
    answer: "a",
    rule: "Kaatosuunta ennen loveusta: The tree will fall that way.",
    why: "Will fall kertoo suunnitelman. Fell kertoisi, että puu on jo maassa, eikä suuntaa enää valita.",
    example: "It will fall towards the gap.",
    trap: "Fall ja feel sekoittuvat. Kaadossa verbi on fall.",
  }),
  task({
    id: "for-05",
    fieldId: "forestry",
    skillId: "modals",
    difficulty: 3,
    level: "B1",
    prompt: "Työkaveri aikoo jäädä yksin leimikolle kertomatta kenellekään. Mitä sanot?",
    choices: options(
      ["Tell someone before you work alone.", "Yksin työskentely vaatii ilmoituksen."],
      ["Work alone and tell someone next week.", "Viikon päästä on liian myöhään."],
      ["You must to tell someone.", "Must ei saa to-sanaa."],
      ["Someone tells you after.", "Järjestys on väärin."],
    ),
    answer: "a",
    rule: "Ennen yksin jäämistä: Tell someone before you work alone.",
    why: "Before you work alone on se järjestys, jota metsässä noudatetaan. Next week ei auta, jos saha juuttuu tänään.",
    example: "Send your location before you start the saw.",
    trap: "Must to on väärin. Must someone tell on myös väärä järjestys.",
  }),
  task({
    id: "for-06",
    fieldId: "forestry",
    skillId: "word-order",
    difficulty: 3,
    level: "B1",
    prompt: "Kirjoita ohje: avaa pakoreitti ennen sahausta.",
    sentence: "Clear the escape route ___ you cut.",
    kind: "cloze",
    choices: [],
    answer: "before",
    accept: ["before"],
    fill: "before",
    rule: "Järjestys on before you cut, ei after you cut.",
    why: "Before you cut tekee pakoreitistä ehdon. After you cut kuvaisi tilannetta, jossa puu on jo kaatumassa.",
    example: "Check the lean before you cut.",
    trap: "Before ja after ovat metsässä eri päätöksiä.",
  }),
];
