import { options, task } from "../field-pack";
import type { Question } from "@/lib/types";

export const precisionFieldQuestions: Question[] = [
  task({
    id: "lab-01",
    fieldId: "laboratory",
    skillId: "word-order",
    difficulty: 2,
    level: "A2",
    prompt: "Näyte pitää merkitä ennen kuin se lähtee tiskiltä. Mitä sanot?",
    choices: options(
      ["Label the sample with the date and time.", "With the date and time kertoo merkinnän."],
      ["Label the example with the date and time.", "Example on esimerkki, ei näyte."],
      ["Label sample the date.", "Artikkeli ja with puuttuvat."],
      ["The sample labels you.", "Tekijä on väärin."],
    ),
    answer: "a",
    rule: "Näyte on sample. Merkintä on Label the sample with the date and time.",
    why: "Sample on se putki tai purkki, joka menee analyysiin. Example on oppikirjan esimerkki. With kertoo, mitä etikettiin tulee.",
    example: "Label the sample with your initials.",
    trap: "Sample ja example eivät vaihdu pöytäkirjassa.",
  }),
  task({
    id: "lab-02",
    fieldId: "laboratory",
    skillId: "modals",
    difficulty: 2,
    level: "A2",
    prompt: "Harjoittelija aikoo imeä pipettiin suulla. Mitä sanot?",
    choices: options(
      ["Do not pipette by mouth.", "By mouth on suulla."],
      ["Do not pipette by mouse.", "Mouse on hiiri."],
      ["Pipette by mouth if you are careful.", "Varovaisuus ei tee tavasta turvallista."],
      ["Do not to pipette.", "Do not ei saa to-sanaa."],
    ),
    answer: "a",
    rule: "Kielto on Do not pipette by mouth.",
    why: "By mouth on vanha ja kielletty tapa. Mouse on tietokoneen hiiri tai eläin. Careful ei muuta ohjetta.",
    example: "Use the pipette controller.",
    trap: "Mouth ja mouse eroavat yhdellä kirjaimella.",
  }),
  task({
    id: "lab-03",
    fieldId: "laboratory",
    skillId: "present",
    difficulty: 3,
    level: "B1",
    prompt: "Tulos ei ole viitealueella. Miten ilmoitat sen?",
    choices: options(
      ["The result is out of range.", "Out of range on alueen ulkopuolella."],
      ["The result is out of order.", "Out of order on laite rikki."],
      ["The result is out range.", "Of puuttuu."],
      ["Result out of range is.", "Sanajärjestys on väärin."],
    ),
    answer: "a",
    rule: "Poikkeava tulos on out of range. Rikkinäinen laite on out of order.",
    why: "Out of range kuuluu laadunvalvontaan. Out of order lähettäisi ilmoituksen huoltoon, vaikka luku on vain alueen ulkopuolella.",
    example: "This glucose result is out of range.",
    trap: "Of ei saa jäädä pois.",
  }),
  task({
    id: "lab-04",
    fieldId: "laboratory",
    skillId: "prepositions",
    difficulty: 2,
    level: "A2",
    prompt: "Hanskat ovat yhä kädessä ja edessä on näppäimistö. Mitä sanot?",
    choices: options(
      ["Take your gloves off before the keyboard.", "Before the keyboard on ennen näppäimistöä."],
      ["Take your gloves off after the keyboard.", "After levittäisi näytteen näppäimiin."],
      ["Take your gloves of before the keyboard.", "Of ei ole off."],
      ["Take off you gloves.", "Omistus on your."],
    ),
    answer: "a",
    rule: "Hanskat pois ennen puhdasta pintaa: Take your gloves off before the keyboard.",
    why: "Before the keyboard estää kontaminaation. After the keyboard on väärä järjestys. Of ja off ovat eri sanat.",
    example: "Take your gloves off before you open the door.",
    trap: "Off on irti. Of on omistus tai osa rakenteesta.",
  }),
  task({
    id: "lab-05",
    fieldId: "laboratory",
    skillId: "articles",
    difficulty: 3,
    level: "B1",
    prompt: "Yksi näyte on voinut sekoittua toiseen. Miten sanot sen?",
    choices: options(
      ["This sample may be contaminated.", "May be on mahdollinen, ei varma."],
      ["This sample may contaminated.", "Be puuttuu."],
      ["This sample must be contaminated.", "Must väittäisi varmaa saastumista."],
      ["A samples may be contaminated.", "A ja monikko eivät sovi."],
    ),
    answer: "a",
    rule: "Epäily sanotaan may be: This sample may be contaminated.",
    why: "May be jättää tilaa varmistukselle. Must be contaminated väittäisi, että saastuminen on varma. May contaminated ilman be-verbiä ei ole lause.",
    example: "The control may be contaminated. Run it again.",
    trap: "May ja must eivät ole sama varmuuden aste.",
  }),
  task({
    id: "lab-06",
    fieldId: "laboratory",
    skillId: "word-order",
    difficulty: 2,
    level: "A2",
    prompt: "Kirjoita käsky: merkitse näyte.",
    sentence: "___ the sample.",
    kind: "cloze",
    choices: [],
    answer: "Label",
    accept: ["label"],
    fill: "Label",
    rule: "Käsky on Label the sample.",
    why: "Label the sample on laboratorion peruskäsky. Sample label ei ole käsky.",
    example: "Label the sample before you leave the bench.",
    trap: "Älä kirjoita example, kun putkessa on näyte.",
  }),

  task({
    id: "ict-01",
    fieldId: "ict",
    skillId: "past",
    difficulty: 2,
    level: "A2",
    prompt: "Käyttäjän kone on jumissa. Mikä on ensimmäinen kysymys?",
    choices: options(
      ["Have you turned it off and on again?", "Have you turned kysyy jo tehdyn yrityksen."],
      ["Did you turned it off?", "Did ja turned eivät ole yhdessä."],
      ["Have you turn it off and on again?", "Perfekti tarvitsee turned."],
      ["You turned it off and on again.", "Toteamus ei ole kysymys."],
    ),
    answer: "a",
    rule: "Uudelleenkäynnistys kysytään: Have you turned it off and on again?",
    why: "Have you turned sopii, kun teko vaikuttaa yhä tilanteeseen. Did you turned on kaksoismennyt. Have you turn jättää verbin kesken.",
    example: "Have you tried another cable?",
    trap: "Did you turn, ei did you turned.",
  }),
  task({
    id: "ict-02",
    fieldId: "ict",
    skillId: "modals",
    difficulty: 2,
    level: "A2",
    prompt: "Käyttäjä aikoo lähettää salasanan sähköpostilla. Mitä sanot?",
    choices: options(
      ["Do not share your password.", "Share on jakaa toiselle."],
      ["Do not shear your password.", "Shear on keritä."],
      ["Share your password with the whole team.", "Koko tiimi ei saa salasanaa."],
      ["Do not to share it.", "Do not ei saa to-sanaa."],
    ),
    answer: "a",
    rule: "Salasanaa ei jaeta: Do not share your password.",
    why: "Share on jakaa. Shear on keritä villaa. Whole team on juuri se virhe, jota tukiohje kieltää.",
    example: "Do not send your password in the chat.",
    trap: "Share ja shear näyttävät samalta vain hetken. Tietoturvassa verbi on share.",
  }),
  task({
    id: "ict-03",
    fieldId: "ict",
    skillId: "present",
    difficulty: 3,
    level: "B1",
    prompt: "Palvelin ei vastaa. Miten ilmoitat katkon?",
    choices: options(
      ["The server is down.", "Down on alhaalla."],
      ["The server is outage.", "Outage on substantiivi, ei näin."],
      ["The server is outrage.", "Outrage on tuohtumus."],
      ["Server down is the.", "Sanajärjestys on väärin."],
    ),
    answer: "a",
    rule: "Palvelin alhaalla: The server is down. Katko on an outage.",
    why: "Is down on tila. Outrage tarkoittaisi vihaa. Outage on tapahtuman nimi: There is an outage, ei The server is outage.",
    example: "The mail server is down.",
    trap: "Outage ja outrage eroavat yhdellä kirjaimella.",
  }),
  task({
    id: "ict-04",
    fieldId: "ict",
    skillId: "future",
    difficulty: 2,
    level: "A2",
    prompt: "Et korjaa vikaa puhelimessa vaan kirjaat sen. Mitä sanot?",
    choices: options(
      ["I will raise a ticket.", "Raise a ticket on avata tukipyyntö."],
      ["I will rise a ticket.", "Rise on nousta, ei avata."],
      ["I will to raise a ticket.", "Will ei saa to-sanaa."],
      ["I raise a ticket yesterday.", "Yesterday ei sovi tähän."],
    ),
    answer: "a",
    rule: "Tukipyyntö avataan: I will raise a ticket.",
    why: "Raise on nostaa tai avata asia. Rise on nousta itsestään. Will to raise on kieliopillisesti väärin.",
    example: "I will raise a ticket and send you the number.",
    trap: "Rise, rose, risen. Raise, raised, raised.",
  }),
  task({
    id: "ict-05",
    fieldId: "ict",
    skillId: "word-order",
    difficulty: 3,
    level: "B1",
    prompt: "Päivitys voi epäonnistua. Mitä sanot ennen kuin käyttäjä aloittaa?",
    choices: options(
      ["Back up your files before you update.", "Varmuuskopio on ennen päivitystä."],
      ["Update first and back up if it fails.", "Epäonnistumisen jälkeen tiedostoja ei välttämättä ole."],
      ["Backing up your files.", "Ei ole täysi ohje."],
      ["Back up you files.", "Omistus on your."],
    ),
    answer: "a",
    rule: "Järjestys on Back up your files before you update.",
    why: "Before you update pitää kopion olemassa. If it fails on liian myöhään. You files on väärä omistus.",
    example: "Back up the database before the upgrade.",
    trap: "Back up on verbi. Backup on substantiivi. Ohjeessa tarvitaan verbi.",
  }),
  task({
    id: "ict-06",
    fieldId: "ict",
    skillId: "past",
    difficulty: 2,
    level: "A2",
    prompt: "Kirjoita: katko alkoi kello kahdeksan.",
    sentence: "The outage ___ at eight.",
    kind: "cloze",
    choices: [],
    answer: "started",
    accept: ["started"],
    fill: "started",
    rule: "Kellonaika vie menneeseen: The outage started at eight.",
    why: "Started at eight on päättyneen alun kuvaus. Has started at eight on väärä pari, koska at eight rajaa ajan.",
    example: "The outage started at 08:05.",
    trap: "Outage, ei outrage.",
  }),

  task({
    id: "med-01",
    fieldId: "media",
    skillId: "present",
    difficulty: 3,
    level: "B1",
    prompt: "Tekstin pitää olla valmis keskipäivällä. Miten deadline sanotaan?",
    choices: options(
      ["The copy is due at noon.", "Due at noon on palautettava keskipäivällä."],
      ["The copy is due to noon.", "Due to tarkoittaisi syytä."],
      ["The copy is due on noon.", "On ei ole kellonajan prepositio."],
      ["Copy due noon.", "Lauseesta puuttuu verbi."],
    ),
    answer: "a",
    rule: "Määräaika kellonlyömällä: The copy is due at noon.",
    why: "Due at on palautushetki. Due to noon kuulostaisi syylauseelta. On noon ei ole kellonaika.",
    example: "The film is due at four.",
    trap: "Due to tarkoittaa 'johtuen'. Due at tarkoittaa 'palautettava'.",
  }),
  task({
    id: "med-02",
    fieldId: "media",
    skillId: "modals",
    difficulty: 2,
    level: "A2",
    prompt: "Haluat nauhoittaa haastattelun. Miten kysyt luvan?",
    choices: options(
      ["May I record this interview?", "May I on kohtelias lupa."],
      ["I record this interview.", "Ilmoitus ei ole kysymys."],
      ["May I to record this interview?", "May ei saa to-sanaa."],
      ["Record I this interview?", "Sanajärjestys ei ole kysymys."],
    ),
    answer: "a",
    rule: "Lupa kysytään: May I record this interview?",
    why: "May I on haastattelun kohtelias kysymys. May I to lisää ylimääräisen to-sanan. I record on ilmoitus, jonka jälkeen on myöhäistä kieltäytyä.",
    example: "May I use your name in the piece?",
    trap: "May ja can ovat molemmat mahdollisia, mutta may I on selvä lupapyyntö.",
  }),
  task({
    id: "med-03",
    fieldId: "media",
    skillId: "present",
    difficulty: 3,
    level: "B1",
    prompt: "Kuva on netistä. Mitä kysyt ennen julkaisua?",
    choices: options(
      ["Who owns the rights to this photo?", "Rights on käyttöoikeudet."],
      ["Who owns the right to this photo?", "Yksikkö right on heikompi, kun kyse on oikeuksista."],
      ["Who own the rights to this photo?", "Who owns saa -s."],
      ["Whose owns the rights?", "Whose ja owns eivät ala kysymystä näin."],
    ),
    answer: "a",
    rule: "Kuvaoikeus kysytään: Who owns the rights to this photo?",
    why: "The rights on vakiintunut monikko. Who own ilman -s-päätettä on väärä yksikkö. Whose owns sekoittaa kaksi kysymyssanaa.",
    example: "Do we have permission to publish it?",
    trap: "Right voi olla oikea suunta. Rights on juridiset oikeudet.",
  }),
  task({
    id: "med-04",
    fieldId: "media",
    skillId: "modals",
    difficulty: 4,
    level: "B2",
    prompt: "Jutussa on lapsen koko nimi. Mitä sanot ennen julkaisua?",
    choices: options(
      ["Do not publish the child's name.", "Lapsen nimi jätetään pois."],
      ["Publish the child's full name and school.", "Koulu ja koko nimi tunnistavat lapsen."],
      ["Do not to publish the name.", "Do not ei saa to-sanaa."],
      ["The child publishes the name.", "Tekijä on väärin."],
    ),
    answer: "a",
    rule: "Tunnistettava lapsi: Do not publish the child's name.",
    why: "Child's name on minimi, joka pitää pois. Full name and school tekisi tunnistamisen helpoksi. Do not to on kieliopillisesti väärin.",
    example: "Use a first name only, and not the school.",
    trap: "Child's on omistus. Childs ei ole monikon omistus.",
  }),
  task({
    id: "med-05",
    fieldId: "media",
    skillId: "quantifiers",
    difficulty: 2,
    level: "A2",
    prompt: "Briiffi pyytää 30 sekunnin klipin. Miten sen sanot?",
    choices: options(
      ["The brief asks for a 30-second clip.", "30-second on yhdysadjektiivi, yksikkö."],
      ["The brief asks for a 30-seconds clip.", "Yhdyssanassa yksikkö ei saa monikkoa."],
      ["The brief asks a 30-second clip.", "Ask for on pyytää jotain."],
      ["Brief ask for 30 second clips the.", "Sanajärjestys on väärin."],
    ),
    answer: "a",
    rule: "Mittamääre yhdyssanassa on yksikkö: a 30-second clip. Verbi on ask for.",
    why: "30-second on adjektiivi, joten second ei ole monikossa. Asks for on oikea verbi. Asks a clip jättää for-sanan pois.",
    example: "We need a 15-second version too.",
    trap: "30 seconds on kesto lauseessa. 30-second on määre substantiivin edessä.",
  }),
  task({
    id: "med-06",
    fieldId: "media",
    skillId: "present",
    difficulty: 3,
    level: "B1",
    prompt: "Kirjoita deadline: teksti on palautettava keskipäivällä.",
    sentence: "The copy is ___ at noon.",
    kind: "cloze",
    choices: [],
    answer: "due",
    accept: ["due"],
    fill: "due",
    rule: "Palautushetki on due at noon.",
    why: "Due at noon on toimituksen deadline. Due to noon tarkoittaisi syytä, ei kelloa.",
    example: "The subtitles are due at noon.",
    trap: "At noon, ei to noon.",
  }),

  task({
    id: "tex-01",
    fieldId: "textile",
    skillId: "word-order",
    difficulty: 2,
    level: "A2",
    prompt: "Asiakas haluaa helman lyhyemmäksi. Miten kirjaat sovituksen?",
    choices: options(
      ["The client wants the hem shorter.", "Hem on helma."],
      ["The client wants the him shorter.", "Him on hänet."],
      ["The client want the hem shorter.", "Client on yksikkö."],
      ["Hem shorter the client wants.", "Sanajärjestys ei ole työmääräys."],
    ),
    answer: "a",
    rule: "Helma on hem: The client wants the hem shorter.",
    why: "Hem on vaatteen reuna. Him on pronomini. Wants saa -s, koska client on yksikkö.",
    example: "Take the hem up by two centimetres.",
    trap: "Hem ja him kuulostavat läheisiltä. Sovituksessa sana on hem.",
  }),
  task({
    id: "tex-02",
    fieldId: "textile",
    skillId: "present",
    difficulty: 2,
    level: "A2",
    prompt: "Kangas kutistuu pesussa. Miten varoitat asiakasta?",
    choices: options(
      ["This fabric shrinks in the wash.", "Shrinks on kutistuu."],
      ["This fabric sinks in the wash.", "Sinks on uppoaa."],
      ["This fabric shrink in the wash.", "Yksiköstä puuttuu -s."],
      ["This fabric is shrink.", "Be ei korvaa verbiä näin."],
    ),
    answer: "a",
    rule: "Kutistuminen on shrink: This fabric shrinks in the wash.",
    why: "Shrinks on pesuohjeen verbi. Sinks tarkoittaisi, että kangas uppoaa. Shrink ilman -s-päätettä ei sovi sanaan this fabric.",
    example: "Pre-wash it. It shrinks.",
    trap: "Shrink, shrank, shrunk. Älä sekoita sitä sink-verbiin.",
  }),
  task({
    id: "tex-03",
    fieldId: "textile",
    skillId: "word-order",
    difficulty: 2,
    level: "A2",
    prompt: "Mitta pitää ottaa kahdesti. Mikä ohje on oikea?",
    choices: options(
      ["Measure twice.", "Twice on kahdesti."],
      ["Measure two times the client.", "Sanajärjestys hajoaa."],
      ["Measuring twice.", "Ei ole käsky."],
      ["Twice measure you.", "Sanajärjestys on väärin."],
    ),
    answer: "a",
    rule: "Kahdesti on twice: Measure twice.",
    why: "Measure twice on ompelijan lyhyt ohje. Two times voi esiintyä, mutta twice on luonteva ja valmis käsky.",
    example: "Measure twice, cut once.",
    trap: "Twice ei ole twin. Twin on kaksonen.",
  }),
  task({
    id: "tex-04",
    fieldId: "textile",
    skillId: "present",
    difficulty: 3,
    level: "B1",
    prompt: "Sauma on ratkennut. Miten kirjaat korjauksen?",
    choices: options(
      ["The seam has split.", "Has split kuvaa yhä auki olevaa saumaa."],
      ["The seam has splitted.", "Split ei saa -ed-päätettä."],
      ["The seem has split.", "Seem on vaikuttaa."],
      ["The seam split has.", "Sanajärjestys on väärin."],
    ),
    answer: "a",
    rule: "Ratkennut sauma: The seam has split. Split ei taivu splitted.",
    why: "Has split kertoo, että sauma on auki nyt. Seem on verbi 'vaikuttaa'. Splitted ei ole englannin muoto.",
    example: "The side seam has split.",
    trap: "Seam on sauma. Seem on näyttää joltakin.",
  }),
  task({
    id: "tex-05",
    fieldId: "textile",
    skillId: "articles",
    difficulty: 2,
    level: "A2",
    prompt: "Pesuohje pitää lukea lapusta. Miten sen sanot?",
    choices: options(
      ["Read the care label.", "Care label on hoito-ohje."],
      ["Read the care level.", "Level on taso, ei lappu."],
      ["Read a care label the.", "Artikkeli on väärässä paikassa."],
      ["Read care label.", "Ilman artikkelia käsky jää keskeneräiseksi."],
    ),
    answer: "a",
    rule: "Pesulappu on the care label.",
    why: "The care label on vaatteen vakiolappu. Level veisi ohjeen tasokokeeseen. Artikkeli the tarvitaan, koska lappu on juuri tässä vaatteessa.",
    example: "The care label says wash at 30 degrees.",
    trap: "Label on lappu. Level on taso.",
  }),
  task({
    id: "tex-06",
    fieldId: "textile",
    skillId: "word-order",
    difficulty: 2,
    level: "A2",
    prompt: "Kirjoita käsky: ota vyötärömitta.",
    sentence: "Take the ___ measurement.",
    kind: "cloze",
    choices: [],
    answer: "waist",
    accept: ["waist"],
    fill: "waist",
    rule: "Vyötärö on waist: Take the waist measurement.",
    why: "Waist on vartalon kohta. Waste on jäte. Mitassa oikea sana on waist.",
    example: "Take the hip measurement too.",
    trap: "Waist ja waste lausutaan samankaltaisesti. Ompelussa kirjoitetaan waist.",
  }),
];
