import { options, task } from "../field-pack";
import type { Question } from "@/lib/types";

export const serviceFieldQuestions: Question[] = [
  task({
    id: "res-01",
    fieldId: "restaurant",
    skillId: "present",
    difficulty: 2,
    level: "A2",
    prompt: "Asiakas osoittaa keittoa. Miten kysyt pähkinästä?",
    choices: options(
      ["Does this contain nuts?", "This viittaa juuri tähän annokseen."],
      ["Does this contain notes?", "Notes on muistiinpanoja."],
      ["Do this contain nuts?", "This on yksikkö, verbi on does."],
      ["Is this contain nuts?", "Contain ei taivu be-verbin kanssa näin."],
    ),
    answer: "a",
    rule: "Allergeeni kysytään: Does this contain nuts?",
    why: "Does this contain on yksikön kysymys tästä annoksesta. Do this on väärä apuverbi, notes on eri sana kuin nuts.",
    example: "Does this contain gluten?",
    trap: "Nuts ja notes näyttävät läheisiltä. Allergiakysymyksessä kirjain on u.",
  }),
  task({
    id: "res-02",
    fieldId: "restaurant",
    skillId: "present",
    difficulty: 2,
    level: "A2",
    prompt: "Pöytä on varattu nimellä Nieminen. Miten sen sanot?",
    choices: options(
      ["The table is booked under Nieminen.", "Under the name on varausnimen fraasi."],
      ["The table is booked below Nieminen.", "Below ei ole varauskirjan prepositio."],
      ["The table booked Nieminen.", "Verbi be ja prepositio puuttuvat."],
      ["The table is booking Nieminen.", "Pöytä ei varaa asiakasta."],
    ),
    answer: "a",
    rule: "Varaus nimiin: The table is booked under Nieminen.",
    why: "Under Nieminen tarkoittaa nimellä Nieminen. Below kuulostaisi paikalta asiakkaan alapuolella.",
    example: "The booking is under Korhonen at seven.",
    trap: "Suomen 'nimellä' ei ole with the name tässä fraasissa. Se on under.",
  }),
  task({
    id: "res-03",
    fieldId: "restaurant",
    skillId: "present",
    difficulty: 2,
    level: "A2",
    prompt: "Sali on täynnä eikä vapaata pöytää ole. Mitä sanot ovella?",
    choices: options(
      ["I am sorry, we are fully booked.", "Fully booked on loppuun varattu."],
      ["I am sorry, we are fully booking.", "Booking olisi parhaillaan varaamassa."],
      ["I am sorry, we are full booked.", "Full ei ole tämän fraasin muoto."],
      ["Sorry we full.", "Lauseesta puuttuu verbi."],
    ),
    answer: "a",
    rule: "Täysi sali: We are fully booked.",
    why: "Fully booked on ravintolan vakiofraasi. Fully booking kuvaisi toimintaa, ei tilannetta ovelle.",
    example: "We are fully booked until nine.",
    trap: "Sorry yksin ei riitä. Asiakas tarvitsee syyn: we are fully booked.",
  }),
  task({
    id: "res-04",
    fieldId: "restaurant",
    skillId: "articles",
    difficulty: 2,
    level: "A2",
    prompt: "Asiakas haluaa laskun. Mikä sana on oikea?",
    choices: options(
      ["Could we have the bill, please?", "Bill on ravintolan lasku."],
      ["Could we have the note, please?", "Note on lappu."],
      ["Could we have a bill the, please?", "Artikkeli on väärässä paikassa."],
      ["Could we have the billing, please?", "Billing on laskutus toimintana, ei paperi pöydässä."],
    ),
    answer: "a",
    rule: "Ravintolassa lasku on the bill.",
    why: "The bill on se, mitä tarjoilija tuo. The note olisi viesti. Billing on toimisto-sana, ei pöydän repliikki.",
    example: "I will bring the bill.",
    trap: "Suomen 'lasku' ei ole note. Note on muistilappu.",
  }),
  task({
    id: "res-05",
    fieldId: "restaurant",
    skillId: "word-order",
    difficulty: 2,
    level: "A2",
    prompt: "Pihvi on tilattu. Miten kysyt kypsyyden?",
    choices: options(
      ["How would you like your steak?", "Would you like on kohtelias kysymys."],
      ["How you like your steak?", "Would tai do puuttuu."],
      ["How would your steak like you?", "Pihvi ei valitse asiakasta."],
      ["What like steak?", "Lause on kesken."],
    ),
    answer: "a",
    rule: "Kypsyys kysytään: How would you like your steak?",
    why: "Would you like on asiakaspalvelun kysymys. Ilman apuverbiä How you like kuulostaa töksähtävältä ja on kieliopillisesti vajaa.",
    example: "Would you like it rare, medium or well done?",
    trap: "Rare on puolikypsä, ei 'harvinainen' tässä kysymyksessä.",
  }),
  task({
    id: "res-06",
    fieldId: "restaurant",
    skillId: "present",
    difficulty: 2,
    level: "A2",
    prompt: "Kirjoita kysymys: onko tässä gluteenia?",
    sentence: "___ this contain gluten?",
    kind: "cloze",
    choices: [],
    answer: "Does",
    accept: ["does"],
    fill: "Does",
    rule: "Yksikön kysymys on Does this contain...?",
    why: "Does this contain gluten on se kysymys, jonka asiakas ja kokki molemmat ymmärtävät. Do this olisi väärä apuverbi.",
    example: "Does the sauce contain dairy?",
    trap: "This on yksikkö. Älä kirjoita Do this contain.",
  }),

  task({
    id: "foo-01",
    fieldId: "food",
    skillId: "prepositions",
    difficulty: 2,
    level: "A2",
    prompt: "Kylmiö on neljä astetta. Miten ilmoitat lämpötilan?",
    choices: options(
      ["The cold room is at four degrees.", "At kuuluu lämpötilan eteen."],
      ["The cold room is on four degrees.", "On ei ole lämpötilan prepositio."],
      ["The cold room is in four degrees.", "In ei kerro mittarilukemaa."],
      ["The cold room is four degree.", "Yli yhden asteen jälkeen monikko, ja at puuttuu."],
    ),
    answer: "a",
    rule: "Lämpötila on at + luku + degrees: at four degrees.",
    why: "At four degrees on tarkastuskirjan kieli. On four degrees ei ole englantia, jota kylmiön ovessa käytetään.",
    example: "The freezer is at minus eighteen degrees.",
    trap: "Suomen 'neljässä asteessa' houkuttelee sanaan in. Mittarilukema on at.",
  }),
  task({
    id: "foo-02",
    fieldId: "food",
    skillId: "word-order",
    difficulty: 1,
    level: "A2",
    prompt: "Työntekijä tulee linjalle pesemättä käsiä. Mitä sanot?",
    choices: options(
      ["Wash your hands.", "Käsky on suora."],
      ["You washing the hands.", "Ei ole käsky."],
      ["Wash you hands.", "Omistus on your, ei you."],
      ["Hands wash.", "Sanajärjestys on väärin."],
    ),
    answer: "a",
    rule: "Hygieniakäsky: Wash your hands.",
    why: "Your hands kuuluu käskyyn. You hands on yleinen virhe, koska suomessa omistusta ei taivuteta samalla sanalla.",
    example: "Wash your hands after the raw meat.",
    trap: "You ei ole omistusmuoto. Omistus on your.",
  }),
  task({
    id: "foo-03",
    fieldId: "food",
    skillId: "modals",
    difficulty: 3,
    level: "B1",
    prompt: "Sulaneen tuotteen pakkauksessa lukee, ettei sitä saa jäädyttää uudelleen. Mitä sanot?",
    choices: options(
      ["Do not refreeze it.", "Refreeze on jäädyttää uudelleen."],
      ["Do not unfreeze it.", "Unfreeze on sulattaa, eli päinvastainen ohje."],
      ["Refreeze it tonight.", "Tämä rikkoo ohjeen."],
      ["Do not to refreeze it.", "Do not ei saa to-sanaa."],
    ),
    answer: "a",
    rule: "Uudelleenjäädytys kielletään: Do not refreeze it.",
    why: "Refreeze on jäädyttää uudelleen. Unfreeze on sulattaa. Ne ovat vastakkaiset ohjeet, ja väärä etuliite pilaa kylmäketjun.",
    example: "Do not refreeze thawed chicken.",
    trap: "Re- tarkoittaa uudelleen. Un- kumoaa tekemisen.",
  }),
  task({
    id: "foo-04",
    fieldId: "food",
    skillId: "articles",
    difficulty: 3,
    level: "B1",
    prompt: "Tuotteen turvallinen viimeinen päivä pitää tarkistaa. Mikä ilmaus on oikea?",
    choices: options(
      ["Check the use-by date.", "Use-by on viimeinen käyttöpäivä."],
      ["Check the best-before date if it is already unsafe.", "Best before kertoo laatua, ei tätä vaaraa."],
      ["Check the use-by dates the.", "Artikkeli on väärässä paikassa."],
      ["Check a use-by date somewhere.", "Somewhere ei kelpaa erän tarkastukseen."],
    ),
    answer: "a",
    rule: "Turvallisuuden raja on the use-by date. Best before kertoo laadusta.",
    why: "Use-by date on päivä, jonka jälkeen ruokaa ei pidetä turvallisena. Best before voi ylittyä laadun heiketessä, mutta se ei ole sama hälytys.",
    example: "Throw it away. The use-by date was yesterday.",
    trap: "Älä vaihda use-by ja best-before keskenään tarkastuspöytäkirjassa.",
  }),
  task({
    id: "foo-05",
    fieldId: "food",
    skillId: "modals",
    difficulty: 2,
    level: "A2",
    prompt: "Tukka on auki linjalla. Mitä sanot?",
    choices: options(
      ["You must wear a hairnet.", "Must wear on ehdoton hygieniaohje."],
      ["You must to wear a hairnet.", "Must ei saa to-sanaa."],
      ["A hairnet wears you.", "Tekijä on väärin."],
      ["You wear maybe a hairnet.", "Maybe ei kuulu suojaukseen."],
    ),
    answer: "a",
    rule: "Pakollinen suojaus: You must wear a hairnet.",
    why: "Must wear on velvoite. Must to wear on kieliopillisesti väärin, maybe tekee velvoitteesta toiveen.",
    example: "You must tie your hair back.",
    trap: "Mustin jälkeen verbi on perusmuodossa ilman to-sanaa.",
  }),
  task({
    id: "foo-06",
    fieldId: "food",
    skillId: "prepositions",
    difficulty: 2,
    level: "A2",
    prompt: "Kirjoita: kylmiö on neljässä asteessa.",
    sentence: "The cold room is ___ four degrees.",
    kind: "cloze",
    choices: [],
    answer: "at",
    accept: ["at"],
    fill: "at",
    rule: "Lämpötila ilmoitetaan at four degrees.",
    why: "At four degrees on mittarilukema. In four degrees ei ole tämän ilmoituksen prepositio.",
    example: "Keep it at or below four degrees.",
    trap: "Älä kirjoita on four degrees.",
  }),

  task({
    id: "tou-01",
    fieldId: "tourism",
    skillId: "present",
    difficulty: 2,
    level: "A2",
    prompt: "Vastaanotossa kerrot, milloin huoneen saa. Mikä on oikein?",
    choices: options(
      ["Check-in is from three o'clock.", "From kertoo alkamisajan."],
      ["Check-in is since three o'clock.", "Since sopii kestoon, ei aikatauluun näin."],
      ["Check-in is from three hours.", "Hours on kesto, ei kellonaika."],
      ["Checking in are at three.", "Yksikkö ja monikko eivät täsmää."],
    ),
    answer: "a",
    rule: "Aikataulun alku on from: Check-in is from three o'clock.",
    why: "From three o'clock kertoo, että sisäänkirjaus alkaa kello kolme. Since viittaisi siihen, että jokin on jatkunut kello kolmesta asti.",
    example: "The desk is open from seven.",
    trap: "O'clock kuuluu tasatuntiin. Three hours on kolme tuntia, ei kello kolme.",
  }),
  task({
    id: "tou-02",
    fieldId: "tourism",
    skillId: "prepositions",
    difficulty: 4,
    level: "B1",
    prompt: "Brittiasiakkaan huone on katutason yläpuolisessa kerroksessa. Miten sen sanot?",
    choices: options(
      ["Your room is on the first floor.", "Brittienglannissa first floor on katutason yläpuolella."],
      ["Your room is on the ground floor.", "Ground floor on katutaso."],
      ["Your room is in the first floor.", "Kerros on on, ei in."],
      ["Your room is at first floor.", "At ei ole kerroksen prepositio."],
    ),
    answer: "a",
    rule: "Brittienglannissa ground floor on katutaso ja first floor sitä seuraava. Kerros on on the floor.",
    why: "Suomalainen 2. kerros on usein brittiläinen first floor, jos katutaso lasketaan ground flooriksi. On the first floor on oikea prepositio.",
    example: "The lift starts at the ground floor.",
    trap: "Älä käännä suomalaista 1. kerrosta automaattisesti first flooriksi.",
  }),
  task({
    id: "tou-03",
    fieldId: "tourism",
    skillId: "present",
    difficulty: 2,
    level: "A2",
    prompt: "Aamiainen on tarjolla 7–10. Miten sen sanot?",
    choices: options(
      ["Breakfast is served from seven to ten.", "From ... to kertoo välin."],
      ["Breakfast is served since seven to ten.", "Since ei ala aikataulua näin."],
      ["Breakfast serves from seven to ten.", "Aamiainen ei tarjoile itseään tässä fraasissa."],
      ["Breakfast is serving from seven.", "Käynnissä oleva muoto ei ole aikataulu."],
    ),
    answer: "a",
    rule: "Tarjoiluaika on is served from seven to ten.",
    why: "Is served on passiivi: aamiainen tarjotaan. Serves tarkoittaisi, että aamiainen tekee jotain. From ... to on kelloväli.",
    example: "Dinner is served from six to nine.",
    trap: "Since seven tarkoittaisi 'kello seitsemästä asti tähän päivään', ei aamiaisen loppua.",
  }),
  task({
    id: "tou-04",
    fieldId: "tourism",
    skillId: "present",
    difficulty: 2,
    level: "A2",
    prompt: "Huoneen 12 suihku ei toimi. Miten vastaanotto kirjaa vian?",
    choices: options(
      ["The shower in room 12 does not work.", "Does not work on ei toimi."],
      ["The shower in room 12 does not works.", "Not-kieltoon ei tule -s."],
      ["The shower in room 12 is not working yesterday.", "Yesterday ei sovi käynnissä olevaan muotoon."],
      ["Shower 12 no work.", "Ei ole lause."],
    ),
    answer: "a",
    rule: "Ei toimi: does not work. Kieltomuodossa pääverbi on perusmuodossa.",
    why: "Does not work on oikea kielto. Does not works lisää -s-päätteen, joka kuuluu vain myönteiseen yksikköön.",
    example: "The key card does not work.",
    trap: "He works, mutta he does not work. -s katoaa kiellossa.",
  }),
  task({
    id: "tou-05",
    fieldId: "tourism",
    skillId: "modals",
    difficulty: 3,
    level: "B1",
    prompt: "Asiakas pyytää myöhäisempää uloskirjausta. Miten vastaat, jos se sopii?",
    choices: options(
      ["You can check out at twelve.", "Can antaa luvan."],
      ["You can to check out at twelve.", "Can ei saa to-sanaa."],
      ["You could checked out at twelve.", "Could ei saa mennyttä muotoa näin."],
      ["Check out you at twelve.", "Sanajärjestys on väärin."],
    ),
    answer: "a",
    rule: "Lupa on can + perusmuoto: You can check out at twelve.",
    why: "Can check out on lupa. Can to ja could checked ovat molemmat rikkinäisiä muotoja, joita vastaanotossa ei käytetä.",
    example: "You can leave your bags here.",
    trap: "Canin jälkeen ei tule to eikä mennyttä aikamuotoa.",
  }),
  task({
    id: "tou-06",
    fieldId: "tourism",
    skillId: "present",
    difficulty: 2,
    level: "A2",
    prompt: "Kirjoita: aamiainen on tarjolla seitsemästä kymmeneen.",
    sentence: "Breakfast is served ___ seven to ten.",
    kind: "cloze",
    choices: [],
    answer: "from",
    accept: ["from"],
    fill: "from",
    rule: "Aikaväli alkaa from: from seven to ten.",
    why: "From seven to ten on aikataulu. Since seven to ten ei ole tämä fraasi.",
    example: "The pool is open from eight to eight.",
    trap: "To tarvitsee parikseen from, ei since.",
  }),

  task({
    id: "bus-01",
    fieldId: "business",
    skillId: "present",
    difficulty: 3,
    level: "B1",
    prompt: "Vahvistat tapaamisen sähköpostin ensimmäisessä lauseessa. Mikä on luontevin?",
    choices: options(
      ["I am writing to confirm our meeting.", "I am writing to on kirjeen aloitus."],
      ["I write to confirm our meeting yesterday.", "Yesterday rikkoo tarkoituksen."],
      ["I am write to confirm.", "Am write ei ole englantia."],
      ["Writing I confirm.", "Sanajärjestys ei ole sähköposti."],
    ),
    answer: "a",
    rule: "Asiallinen aloitus on I am writing to confirm...",
    why: "I am writing to on liike-elämän sähköpostin vakiorakenne. Am write jättää -ing-muodon pois.",
    example: "I am writing to ask for the price list.",
    trap: "Älä aloita I want. Se on töksähtävämpi kuin I am writing to.",
  }),
  task({
    id: "bus-02",
    fieldId: "business",
    skillId: "articles",
    difficulty: 2,
    level: "A2",
    prompt: "Lasku lähtee liitteenä. Mikä lause on oikea?",
    choices: options(
      ["Please find the invoice attached.", "Find attached on liitteen vakiofraasi."],
      ["Please find the invoice attaching.", "Attaching kuvaisi parhaillaan kiinnittämistä."],
      ["Please find a invoice attached.", "Invoice alkaa vokaaliäänteellä, a ei sovi."],
      ["Please find invoice the attached.", "Artikkeli on väärässä paikassa."],
    ),
    answer: "a",
    rule: "Liite ilmoitetaan: Please find the invoice attached.",
    why: "The invoice attached on valmis fraasi. A invoice on väärä artikkeli, koska invoice alkaa vokaaliäänteellä. Attaching ei ole liitteen adjektiivi.",
    example: "Please find the report attached.",
    trap: "An invoice, the invoice. Ei a invoice.",
  }),
  task({
    id: "bus-03",
    fieldId: "business",
    skillId: "present",
    difficulty: 3,
    level: "B1",
    prompt: "Eräpäivä meni eilen. Miten asia sanotaan?",
    choices: options(
      ["The invoice is overdue.", "Overdue on myöhässä oleva maksu."],
      ["The invoice is overdate.", "Overdate ei ole sana."],
      ["The invoice is overdue yesterday.", "Yesterday ei sovi tähän tilaan."],
      ["Invoice overdue are.", "Sanajärjestys ja verbi ovat väärin."],
    ),
    answer: "a",
    rule: "Myöhässä oleva lasku on overdue: The invoice is overdue.",
    why: "Overdue kuvaa nykyistä tilaa. Yesterday tekisi siitä kellonajan, jota tämä adjektiivi ei tarvitse. Overdate ei ole englantia.",
    example: "Payment is overdue by ten days.",
    trap: "Delay kuvaa lähetystä. Laskulle sana on overdue.",
  }),
  task({
    id: "bus-04",
    fieldId: "business",
    skillId: "modals",
    difficulty: 3,
    level: "B1",
    prompt: "Et pääse torstain tapaamiseen. Miten kieltäydyt kohteliaasti?",
    choices: options(
      ["I am afraid I cannot make Thursday.", "I am afraid pehmentää kieltäytymisen."],
      ["I am afraid of Thursday.", "Afraid of tarkoittaisi, että pelkäät torstaita."],
      ["I cannot to make Thursday.", "Cannot ei saa to-sanaa."],
      ["No. Thursday is bad.", "Sisältö ymmärretään, mutta sävy on tarpeettoman kova."],
    ),
    answer: "a",
    rule: "Kohtelias este: I am afraid I cannot make Thursday.",
    why: "I am afraid ei kerro pelosta vaan siitä, että uutinen on ikävä. Afraid of Thursday tarkoittaisi pelkoa. Cannot to on kieliopillisesti väärin.",
    example: "I am afraid the delivery will be late.",
    trap: "Afraid of ja I am afraid that eivät ole sama rakenne.",
  }),
  task({
    id: "bus-05",
    fieldId: "business",
    skillId: "future",
    difficulty: 2,
    level: "A2",
    prompt: "Ehdotat tapaamista tiistaiksi. Mikä on luontevin?",
    choices: options(
      ["Could we meet on Tuesday?", "On Tuesday on viikonpäivä."],
      ["Could we meet in Tuesday?", "In ei ole viikonpäivän prepositio."],
      ["Could we meet at Tuesday?", "At ei sovi pelkälle viikonpäivälle."],
      ["Could we meeting on Tuesday?", "Could we tarvitsee perusmuodon."],
    ),
    answer: "a",
    rule: "Viikonpäivä on on Tuesday. Ehdotus on Could we meet...?",
    why: "On Tuesday on oikea prepositio. In Tuesday ja at Tuesday ovat suomalaiselle tuttuja arvauksia, mutta eivät kalenterikieltä.",
    example: "Could we meet on Tuesday at ten?",
    trap: "Kellonaika on at ten, viikonpäivä on on Tuesday. Ne voivat olla samassa lauseessa.",
  }),
  task({
    id: "bus-06",
    fieldId: "business",
    skillId: "articles",
    difficulty: 2,
    level: "A2",
    prompt: "Kirjoita: lasku on liitteenä.",
    sentence: "Please find ___ invoice attached.",
    kind: "cloze",
    choices: [],
    answer: "the",
    accept: ["the"],
    fill: "the",
    rule: "Juuri tämä lasku on the invoice.",
    why: "The invoice tarkoittaa sitä laskua, jonka vastaanottaja odottaa. A invoice olisi myös artikkeli väärin, koska sana alkaa vokaaliäänteellä.",
    example: "Please find the agenda attached.",
    trap: "Älä jätä artikkelia pois: find invoice attached kuulostaa keskeneräiseltä.",
  }),

  task({
    id: "care-01",
    fieldId: "care",
    skillId: "present",
    difficulty: 2,
    level: "A2",
    prompt: "Asukas pitää kylkeään. Miten kysyt kivun paikan?",
    choices: options(
      ["Where does it hurt?", "Does it hurt on kipukysymys."],
      ["Where it hurts?", "Kysymyssanan jälkeen apuverbi puuttuu."],
      ["Where does it hurts?", "Kieltokysymyksessä ja kysymyksessä pääverbi ei saa -s."],
      ["Where is it hurt?", "Is hurt ei ole tämä kysymys."],
    ),
    answer: "a",
    rule: "Kipu kysytään: Where does it hurt?",
    why: "Does it hurt siirtää apuverbin subjektin eteen. Does it hurts jättää -s-päätteen, joka kuuluu vain myönteiseen lauseeseen it hurts.",
    example: "Does it hurt when you breathe?",
    trap: "It hurts, mutta Does it hurt?",
  }),
  task({
    id: "care-02",
    fieldId: "care",
    skillId: "past",
    difficulty: 2,
    level: "A2",
    prompt: "Raportoit, että hän kaatui aamulla. Mikä on oikein?",
    choices: options(
      ["She fell this morning.", "Fell on kaatua, mennyt aika."],
      ["She felt this morning.", "Felt on tuntea."],
      ["She has fallen this morning.", "This morning rajaa ajan, joten past simple on selvempi."],
      ["She fall this morning.", "Aikamuoto puuttuu."],
    ),
    answer: "a",
    rule: "Päättynyt kaatuminen aamulla: She fell this morning.",
    why: "Fell on fall-verbin mennyt aika. Felt on feel-verbin mennyt aika ja tarkoittaisi tunnetta. Raportissa ero on iso.",
    example: "He fell in the bathroom.",
    trap: "Fall, fell, fallen. Feel, felt, felt. Älä sekoita niitä raportissa.",
  }),
  task({
    id: "care-03",
    fieldId: "care",
    skillId: "modals",
    difficulty: 3,
    level: "B1",
    prompt: "Omainen pyytää sinua antamaan lääkkeen, jota ei ole määrätty. Mitä sanot?",
    choices: options(
      ["I cannot give medicine that is not prescribed.", "Lupa puuttuu, joten kielto on selvä."],
      ["I can give it if you ask nicely.", "Kohteliaisuus ei ole lääkemääräys."],
      ["I cannot to give it.", "Cannot ei saa to-sanaa."],
      ["The medicine gives me.", "Tekijä on väärin."],
    ),
    answer: "a",
    rule: "Ilman määräystä: I cannot give medicine that is not prescribed.",
    why: "That is not prescribed rajaa kiellon oikein. Nicely ei muuta lupaa. Cannot to on kieliopillisesti väärin.",
    example: "I will ask the nurse about the dose.",
    trap: "Can ja cannot eivät saa to-sanaa.",
  }),
  task({
    id: "care-04",
    fieldId: "care",
    skillId: "modals",
    difficulty: 2,
    level: "A2",
    prompt: "Haluat mitata verenpaineen. Miten pyydät luvan?",
    choices: options(
      ["Is it all right if I check your blood pressure?", "If I check pyytää luvan."],
      ["I check your blood pressure now.", "Ilmoitus ei ole kysymys."],
      ["Is it all right if I checked yesterday?", "Yesterday vie luvan menneisyyteen."],
      ["Check I your blood pressure?", "Sanajärjestys ei ole kysymys."],
    ),
    answer: "a",
    rule: "Lupa kysytään: Is it all right if I...?",
    why: "If I check your blood pressure jättää päätöksen asukkaalle. I check now on ilmoitus, ei kysymys.",
    example: "Is it all right if I help you sit up?",
    trap: "Hoidossa kosketus ja mittaus kysytään, ei ilmoiteta jälkikäteen.",
  }),
  task({
    id: "care-05",
    fieldId: "care",
    skillId: "past",
    difficulty: 4,
    level: "B1",
    prompt: "Hän ei ole syönyt aamupalan jälkeen. Miten raportoit tilanteen, joka jatkuu yhä?",
    choices: options(
      ["She has not eaten since breakfast.", "Since + perfekti kuvaa yhä jatkuvaa tilaa."],
      ["She did not eat since breakfast.", "Did not eat ei sovi sanaan since."],
      ["She has not eaten yesterday.", "Yesterday ei sovi perfektiin."],
      ["She not eaten since breakfast.", "Apuverbi has puuttuu."],
    ),
    answer: "a",
    rule: "Jatkunut tila lähtökohdasta asti: has not eaten since breakfast.",
    why: "Since breakfast tarvitsee perfektin, koska syömättä olo alkoi aamulla ja jatkuu nyt. Did not eat since on yleinen mutta väärä yhdistelmä.",
    example: "He has not slept since the operation.",
    trap: "Since ei yhdisty past simpleen. Yesterday ei yhdisty perfektiin.",
  }),
  task({
    id: "care-06",
    fieldId: "care",
    skillId: "present",
    difficulty: 2,
    level: "A2",
    prompt: "Kirjoita kysymys: missä koskee?",
    sentence: "Where ___ it hurt?",
    kind: "cloze",
    choices: [],
    answer: "does",
    accept: ["does"],
    fill: "does",
    rule: "Kysymys on Where does it hurt?",
    why: "Does siirtää lauseen kysymykseksi. Where it hurt jää keskeneräiseksi.",
    example: "Where does it hurt the most?",
    trap: "Älä kirjoita Where does it hurts?",
  }),

  task({
    id: "bea-01",
    fieldId: "beauty",
    skillId: "past",
    difficulty: 3,
    level: "B1",
    prompt: "Ennen hiusten väriä pitää tietää, onko testi tehty. Mitä kysyt?",
    choices: options(
      ["Have you had a patch test?", "Have you had kysyy kokemusta tähän asti."],
      ["Did you had a patch test?", "Did ja had eivät ole yhdessä."],
      ["Have you have a patch test?", "Have ei toistu noin."],
      ["You had a patch test?", "Sävy on syytös, ja muoto on vajaa kohteliaaksi kysymykseksi."],
    ),
    answer: "a",
    rule: "Aiempi testi kysytään: Have you had a patch test?",
    why: "Have you had sopii, kun tulos vaikuttaa yhä tähän värjäykseen. Did you had on kaksoismennyt ja väärin.",
    example: "Have you coloured your hair before?",
    trap: "Did you have, ei did you had.",
  }),
  task({
    id: "bea-02",
    fieldId: "beauty",
    skillId: "prepositions",
    difficulty: 2,
    level: "A2",
    prompt: "Aika on 14.30. Miten sen sanot niin, ettei se sekoitu puoleen kahteen?",
    choices: options(
      ["Your appointment is at half past two.", "Half past two on 14.30."],
      ["Your appointment is at half to two.", "Half to two on 13.30."],
      ["Your appointment is in half past two.", "In ei ole kellonajan prepositio."],
      ["Your appointment is at half past two hours.", "Hours tekisi siitä keston."],
    ),
    answer: "a",
    rule: "14.30 on half past two. Kellonaika on at.",
    why: "Half past two on puoli tuntia kahden jälkeen. Half to two on puoli tuntia ennen kahta. In half past two ei ole kello.",
    example: "See you at half past four.",
    trap: "Suomen 'puoli kolme' on 14.30, ei half to three.",
  }),
  task({
    id: "bea-03",
    fieldId: "beauty",
    skillId: "modals",
    difficulty: 2,
    level: "A2",
    prompt: "Värin jälkeen hiuksia ei pestä kahteen vuorokauteen. Mitä sanot?",
    choices: options(
      ["Do not wash your hair for 48 hours.", "For 48 hours on kesto."],
      ["Do not wash your hair since 48 hours.", "Since ei kerro tulevaa kestoa."],
      ["Do not to wash your hair.", "Do not ei saa to-sanaa."],
      ["Not wash the hairs.", "Hair on tässä jakamaton, ja lause on vajaa."],
    ),
    answer: "a",
    rule: "Kesto on for 48 hours: Do not wash your hair for 48 hours.",
    why: "For 48 hours kertoo, kuinka kauan kielto kestää. Since 48 hours ei ole tulevan kiellon rakenne. Hairs tarkoittaisi yksittäisiä karvoja.",
    example: "Do not use heat for two days.",
    trap: "Hair on yleensä yksikkö, kun puhutaan tukasta. Hairs on yksittäisiä karvoja.",
  }),
  task({
    id: "bea-04",
    fieldId: "beauty",
    skillId: "present",
    difficulty: 3,
    level: "B1",
    prompt: "Väriaineen pitää vaikuttaa asiakkaan päässä. Miten sen sanot?",
    choices: options(
      ["The colour needs to develop.", "Develop on vaikuttaa, kehittyä valmiiksi."],
      ["The colour needs to envelope.", "Envelope on kirjekuori."],
      ["The colour need to develop.", "Colour on yksikkö."],
      ["The colour is develop.", "Be ei korvaa needs to."],
    ),
    answer: "a",
    rule: "Vaikutusaika: The colour needs to develop.",
    why: "Needs to develop on kampaamon lause. Envelope on kirjekuori. Need ilman -s-päätettä rikkoo yksikön, koska colour on yksi aine.",
    example: "Leave it on. It needs to develop for twenty minutes.",
    trap: "Colour kirjoitetaan brittienglannissa ilman u-kirjainta keskellä... odota, brittienglannissa on colour. Pitää käyttää colour.",
  }),
  task({
    id: "bea-05",
    fieldId: "beauty",
    skillId: "present",
    difficulty: 2,
    level: "A2",
    prompt: "Kysyt allergioista ennen kestolakausta. Mikä on selvin?",
    choices: options(
      ["Are you allergic to anything?", "Allergic to on allerginen jollekin."],
      ["Are you allergic for anything?", "For ei ole tämän adjektiivin prepositio."],
      ["Are you allergy to anything?", "Allergy on substantiivi."],
      ["Do you allergic?", "Do ei sovi adjektiiviin."],
    ),
    answer: "a",
    rule: "Allergia kysytään: Are you allergic to anything?",
    why: "Allergic on adjektiivi ja saa to. Allergy on substantiivi: I have an allergy. For anything on väärä prepositio.",
    example: "Are you allergic to the tint?",
    trap: "Allergic ja allergy eivät vaihdu keskenään lauseessa.",
  }),
  task({
    id: "bea-06",
    fieldId: "beauty",
    skillId: "past",
    difficulty: 3,
    level: "B1",
    prompt: "Kirjoita kysymys: onko sinulle tehty allergeenitesti?",
    sentence: "Have you ___ a patch test?",
    kind: "cloze",
    choices: [],
    answer: "had",
    accept: ["had"],
    fill: "had",
    rule: "Have you had a patch test? on oikea perfekti.",
    why: "Had on have-verbin muoto perfektissä. Have you have ei ole englantia, did you had on kaksoisvirhe.",
    example: "Have you had a reaction before?",
    trap: "Have you had, ei have you have.",
  }),

  task({
    id: "cln-01",
    fieldId: "cleaning",
    skillId: "modals",
    difficulty: 3,
    level: "B1",
    prompt: "Työkaveri aikoo sekoittaa kloorin ja happaman pesuaineen. Mitä sanot?",
    choices: options(
      ["Never mix bleach with acid.", "Bleach on kloorivalkaisuaine."],
      ["Never mix beach with acid.", "Beach on ranta."],
      ["Mix bleach with acid for a stronger clean.", "Vahvempi seos on vaarallinen."],
      ["Never mixing bleach.", "Ei ole täysi kielto."],
    ),
    answer: "a",
    rule: "Kielto on ehdoton: Never mix bleach with acid.",
    why: "Bleach with acid voi vapauttaa myrkyllistä kaasua. Beach on ranta. Stronger clean on juuri se perustelu, joka pitää torjua.",
    example: "Never mix bleach with ammonia.",
    trap: "Bleach ja beach eroavat yhdellä kirjaimella. Aineohjeessa oikea sana on bleach.",
  }),
  task({
    id: "cln-02",
    fieldId: "cleaning",
    skillId: "word-order",
    difficulty: 2,
    level: "A2",
    prompt: "Käytävä on märkä. Mitä teet ennen kuin jatkat?",
    choices: options(
      ["Put out the wet floor sign.", "Put out on laittaa esille."],
      ["Put the wet floor sign out after people walk through.", "Jälkikäteen kyltti ei estä liukastumista."],
      ["Put out a wet floor signs.", "A ja monikko eivät sovi."],
      ["Out put the sign.", "Sanajärjestys on väärin."],
    ),
    answer: "a",
    rule: "Kyltti laitetaan esille heti: Put out the wet floor sign.",
    why: "Put out tarkoittaa esille laittamista. After people walk through on liian myöhään. A signs on artikkeli- ja monikkovirhe.",
    example: "Put out the sign at both ends of the corridor.",
    trap: "Put out ei ole sama kuin put outside. Kyltti voi olla sisällä.",
  }),
  task({
    id: "cln-03",
    fieldId: "cleaning",
    skillId: "articles",
    difficulty: 2,
    level: "A2",
    prompt: "Peilit pestään eri aineella kuin lattia. Miten ohjeistat?",
    choices: options(
      ["Use the glass cleaner on the mirrors.", "On the mirrors kertoo pinnan."],
      ["Use the glass cleaner in the mirrors.", "In kuulostaisi peilien sisältä."],
      ["Use a glass cleaner on the mirror the.", "Artikkeli on väärässä paikassa."],
      ["Use the floor cleaner on the mirrors.", "Lattia-aine ei ole lasille."],
    ),
    answer: "a",
    rule: "Pinta sanotaan on: on the mirrors. Aine on the glass cleaner, kun se on sovittu.",
    why: "On the mirrors on oikea prepositio. Floor cleaner peileissä on väärä aine, vaikka lause näyttäisi muuten siistiltä.",
    example: "Use the toilet cleaner only in the bowl.",
    trap: "In the mirrors ei ole pesuohje.",
  }),
  task({
    id: "cln-04",
    fieldId: "cleaning",
    skillId: "present",
    difficulty: 2,
    level: "A2",
    prompt: "Sivuoven lukko on rikki. Miten ilmoitat sen?",
    choices: options(
      ["The lock on the side door is broken.", "On the side door paikantaa lukon."],
      ["The lock on the side door is broke.", "Broke on verbin mennyt aika, ei tila."],
      ["The lock in the side door is broken.", "In on heikompi kuin on, kun lukko on ovessa."],
      ["Side door lock broken is.", "Sanajärjestys on väärin."],
    ),
    answer: "a",
    rule: "Rikki oleva lukko: The lock is broken. Ovessa on on the door.",
    why: "Is broken kuvaa nykyistä kuntoa. Broke on mennyt tapahtuma ilman be-verbiä, eikä se ole tämän lauseen muoto.",
    example: "The handle is broken.",
    trap: "Broken on adjektiivi. Broke on verbi.",
  }),
  task({
    id: "cln-05",
    fieldId: "cleaning",
    skillId: "modals",
    difficulty: 2,
    level: "A2",
    prompt: "Aine on ärsyttävää. Mitä sanot hanskoista?",
    choices: options(
      ["You must wear gloves.", "Must wear on velvoite."],
      ["You must to wear gloves.", "Must ei saa to-sanaa."],
      ["Gloves wear you.", "Tekijä on väärin."],
      ["You wear gloves maybe.", "Maybe kumoaa velvoitteen."],
    ),
    answer: "a",
    rule: "Suojakäsineet ovat velvoite: You must wear gloves.",
    why: "Must wear gloves on kemikaaliohje. Must to wear on kieliopillisesti väärin, maybe ei kuulu käyttöturvallisuuteen.",
    example: "You must wear goggles with this product.",
    trap: "Must + perusmuoto, ilman to-sanaa.",
  }),
  task({
    id: "cln-06",
    fieldId: "cleaning",
    skillId: "word-order",
    difficulty: 2,
    level: "A2",
    prompt: "Kirjoita käsky: laita märän lattian kyltti.",
    sentence: "Put out the ___ floor sign.",
    kind: "cloze",
    choices: [],
    answer: "wet",
    accept: ["wet"],
    fill: "wet",
    rule: "Kyltin nimi on the wet floor sign.",
    why: "Wet floor sign on se kyltti, jonka ohikulkija tunnistaa. Water floor sign ei ole vakiintunut nimi.",
    example: "Leave the wet floor sign until the floor is dry.",
    trap: "Älä käännä kylttiä sanalla wet floors sign monikolla, jos kylttejä on yksi.",
  }),

  task({
    id: "sec-01",
    fieldId: "security",
    skillId: "modals",
    difficulty: 2,
    level: "A2",
    prompt: "Ovella pitää nähdä kulkulupa. Miten pyydät sen?",
    choices: options(
      ["Can I see your ID, please?", "Can I see on kohtelias ja selvä."],
      ["I see your ID.", "Ilmoitus ei ole pyyntö."],
      ["Can I to see your ID?", "Can ei saa to-sanaa."],
      ["See I your ID?", "Sanajärjestys ei ole kysymys."],
    ),
    answer: "a",
    rule: "Pyyntö on Can I see your ID, please?",
    why: "Can I see on kysymys. I see your ID on toteamus. Can I to see lisää ylimääräisen to-sanan.",
    example: "Can I see your visitor pass?",
    trap: "ID on henkilöllisyys tai kulkulupa. Idea ei ole sama sana.",
  }),
  task({
    id: "sec-02",
    fieldId: "security",
    skillId: "word-order",
    difficulty: 3,
    level: "B1",
    prompt: "Kaksi ihmistä yrittää tulla yhdestä ovenavauksesta. Mitä sanot?",
    choices: options(
      ["Please do not tailgate.", "Tailgate on tulla toisen kulkuoikeudella perässä."],
      ["Please do not tail.", "Tail yksin ei ole tämä ohje."],
      ["Please tailgate one at a time.", "Tämä sallisi juuri kielletyn."],
      ["Do not to tailgate.", "Do not ei saa to-sanaa."],
    ),
    answer: "a",
    rule: "Perässä tuleminen kielletään: Please do not tailgate.",
    why: "Tailgate on kulunvalvonnan verbi. Tail yksin ei riitä ohjeeksi. One at a time kuuluu eri lauseeseen: Come in one at a time.",
    example: "One card, one person. Please do not tailgate.",
    trap: "Tailgate autossa on ajaa puskurissa kiinni. Ovella se on tulla perässä.",
  }),
  task({
    id: "sec-03",
    fieldId: "security",
    skillId: "word-order",
    difficulty: 2,
    level: "A2",
    prompt: "Hälytys käy ja käytävä pitää tyhjentää. Mitä ohjaat?",
    choices: options(
      ["Leave by the nearest exit.", "By the nearest exit on poistumisreitti."],
      ["Leave by the nearest entrance.", "Entrance on sisäänkäynti."],
      ["Leave to the nearest exit.", "To ei ole tämän ohjeen prepositio."],
      ["Nearest exit leave.", "Ei ole käsky."],
    ),
    answer: "a",
    rule: "Poistuminen: Leave by the nearest exit.",
    why: "Exit on ulos, entrance on sisään. By the nearest exit on kuulutuksen kieli. To the exit voi esiintyä, mutta by on poistumiskäskyn prepositio.",
    example: "Do not use the lift. Leave by the stairs.",
    trap: "Entrance ja exit ovat vastakkaiset suunnat.",
  }),
  task({
    id: "sec-04",
    fieldId: "security",
    skillId: "past",
    difficulty: 3,
    level: "B1",
    prompt: "Kirjaat raporttiin, mitä tapahtui kello 21. Mikä aikamuoto on oikea?",
    choices: options(
      ["A visitor refused to show ID at nine.", "Kellonaika ja mennyt aika sopivat yhteen."],
      ["A visitor has refused to show ID at nine.", "At nine ei sovi perfektiin."],
      ["A visitor refuses to show ID at nine yesterday.", "Yesterday ja preesens riitelevät."],
      ["A visitor refuse to show ID.", "Aikamuoto ja -s puuttuvat."],
    ),
    answer: "a",
    rule: "Raportin kellonaika on menneessä ajassa: refused ... at nine.",
    why: "At nine rajaa tapahtuman menneisyyteen. Has refused at nine on väärä pari. Refuses yesterday sekoittaa nykyisen ja eilisen.",
    example: "The alarm sounded at 21:10.",
    trap: "Raportissa kellonaika vie lauseen past simpleen.",
  }),
  task({
    id: "sec-05",
    fieldId: "security",
    skillId: "articles",
    difficulty: 2,
    level: "A2",
    prompt: "Vieras pitää kuitata kirjaan. Mitä sanot?",
    choices: options(
      ["Please sign the visitors' book.", "Visitors' book on vieraskirja."],
      ["Please sign the visitor book the.", "Artikkeli on väärässä paikassa."],
      ["Please sign a visitors book somewhere.", "Somewhere ei ole valvomon ohje."],
      ["Please sign the visitors'.", "Omistus jää kesken ilman book-sanaa."],
    ),
    answer: "a",
    rule: "Vieraskirja on the visitors' book. Heittomerkki on monikon jälkeen.",
    why: "Visitors' kertoo, että kirja on vieraille. The visitors ilman book-sanaa ei ole kuitattava esine.",
    example: "Sign in at the visitors' book.",
    trap: "Visitor's book olisi yhden vieraan kirja. Visitors' book on yhteinen kirja.",
  }),
  task({
    id: "sec-06",
    fieldId: "security",
    skillId: "word-order",
    difficulty: 2,
    level: "A2",
    prompt: "Kirjoita poistumiskäsky.",
    sentence: "Leave ___ the nearest exit.",
    kind: "cloze",
    choices: [],
    answer: "by",
    accept: ["by"],
    fill: "by",
    rule: "Poistumisreitti on by the nearest exit.",
    why: "By the nearest exit on kuulutuksen prepositio. Through voi esiintyä toisaalla, mutta tämä vakiokäsky käyttää by.",
    example: "Leave by the west stairs.",
    trap: "Älä kirjoita Leave to the nearest exit, jos tarkoitus on kuulutuksen vakiolause.",
  }),
];
