import { options, task } from "../field-pack";
import type { Question } from "@/lib/types";

export const technicalFieldQuestions: Question[] = [
  task({
    id: "con-01",
    fieldId: "construction",
    skillId: "word-order",
    difficulty: 2,
    level: "A2",
    prompt: "Kollega aikoo kiivetä telineelle ilman valjaita. Mikä käsky on oikea?",
    sentence: "___ your harness before you climb.",
    choices: options(
      ["Wear", "Työmaakäsky on kokonainen lause."],
      ["You wearing", "Ing-muoto ei ole käsky."],
      ["Wears", "Hän-muoto ei käske kuulijaa."],
      ["Helmet the wear", "Sanajärjestys on suomea englanniksi."],
    ),
    answer: "a",
    rule: "Työmaakäsky alkaa käskymuodolla: Wear, Mind, Stop. Älä jätä esinettä ilman artikkelia tai omistusta.",
    why: "Wear your harness before you climb on se lause, jonka kollega ymmärtää heti. You wearing on keskeneräinen, wears puhuu jostakusta muusta.",
    example: "Wear your helmet on site.",
    trap: "Suomeksi riittää usein 'valjaat päälle'. Englannissa tarvitaan verbi ja your.",
  }),
  task({
    id: "con-02",
    fieldId: "construction",
    skillId: "quantifiers",
    difficulty: 2,
    level: "A2",
    prompt: "Piirustuksessa laatan paksuus on 150 mm. Miten sen sanot työmaalla?",
    sentence: "The slab is ___ thick.",
    choices: options(
      ["150 millimetres", "Mitta ja yksikkö kuuluvat yhteen."],
      ["150 of millimetre", "Of ei rakenna mittaa näin."],
      ["a 150 millimetres", "Epämääräinen artikkeli ei sovi tarkkaan mittaan."],
      ["150 the millimetres", "Artikkeli ei tule yksikön eteen."],
    ),
    answer: "a",
    rule: "Mittayksikkö tulee luvun jälkeen monikossa: 150 millimetres, 3.2 metres.",
    why: "Brittienglannissa yksikkö on millimetre, ja yli yhden jälkeen monikko. The slab is 150 millimetres thick on se lause, jonka mittamies kirjoittaa ja sanoo.",
    example: "The opening is 900 millimetres wide.",
    trap: "Älä käännä '150 milliä paksu' sanalla from tai of.",
  }),
  task({
    id: "con-03",
    fieldId: "construction",
    skillId: "articles",
    difficulty: 3,
    level: "B1",
    prompt: "Betoni on juuri valettu. Miten varoitat?",
    sentence: "Don't step on ___ fresh concrete.",
    choices: options(
      ["the", "Juuri tämä valu on tiedossa kaikille."],
      ["a", "Kyse ei ole jostain satunnaisesta betonista."],
      ["an", "Fresh alkaa konsonanttiäänteellä."],
      ["—", "Ilman artikkelia kuulostaa yleiseltä aineelta, ei tältä valulta."],
    ),
    answer: "a",
    rule: "Kun kaikki näkevät, mistä betonista puhutaan, käytä the: the fresh concrete.",
    why: "Työmaalla the fresh concrete tarkoittaa juuri tätä valua. A fresh concrete tekisi siitä yhden epämääräisen erän jossain.",
    example: "Don't walk on the wet paint.",
    trap: "Suomeksi 'tuoreelle betonille' ei tule artikkelia. Englannissa the tarvitaan.",
  }),
  task({
    id: "con-04",
    fieldId: "construction",
    skillId: "modals",
    difficulty: 3,
    level: "B1",
    prompt: "Palkkia ei saa katkaista omin päin. Mitä sanot?",
    choices: options(
      ["Check with the site manager before you cut that beam.", "Lupa haetaan ennen työtä."],
      ["You cut the beam and then tell the manager.", "Jälkikäteen kertominen on liian myöhäistä."],
      ["The beam is cutting yourself.", "Passiivi ja tekijä ovat sekaisin."],
      ["Cut first, permission later.", "Tämä on juuri se virhe, jota työmaa ei salli."],
    ),
    answer: "a",
    rule: "Ennen kuin muutat kantavaa rakennetta, sano lupa ääneen: Check with the site manager first.",
    why: "Check with the site manager before you cut that beam pitää järjestyksen oikein: ensin lupa, sitten leikkaus. Toinen vaihtoehto tekee työn ensin.",
    example: "Ask the engineer before you move that prop.",
    trap: "Before you cut ei ole sama kuin after you cut.",
  }),
  task({
    id: "con-05",
    fieldId: "construction",
    skillId: "prepositions",
    difficulty: 2,
    level: "A2",
    prompt: "Miten kerrot, että mitta löytyy piirustuksesta?",
    sentence: "The dimension is ___ the drawing.",
    choices: options(
      ["on", "Piirustuksen päällä oleva tieto on on the drawing."],
      ["in", "In the drawing kuulostaa siltä, että olet piirustuksen sisällä."],
      ["at", "At ei paikanna merkintää paperilla."],
      ["to", "To kertoo suunnan, ei paikkaa."],
    ),
    answer: "a",
    rule: "Merkintä on piirustuksessa: on the drawing. Työmaa itse on on site.",
    why: "On the drawing on vakiintunut ilmaus. In the drawing ei ole se prepositio, jota työnjohtaja käyttää mitasta puhuessaan.",
    example: "The level is marked on the drawing.",
    trap: "Suomen 'piirustuksessa' houkuttelee sanaan in. Työenglannissa se on on.",
  }),
  task({
    id: "con-06",
    fieldId: "construction",
    skillId: "word-order",
    difficulty: 1,
    level: "A2",
    prompt: "Käytävässä on kattoon asti auki oleva aukko. Kirjoita varoitus, jonka huudat.",
    sentence: "___ the opening.",
    kind: "cloze",
    choices: [],
    answer: "Mind",
    accept: ["mind", "Watch", "watch"],
    fill: "Mind",
    rule: "Lyhyt vaarahuito on käsky: Mind the opening tai Watch your head.",
    why: "Mind the opening on työmaan lyhyt varoitus. Se ei tarvitse please-sanaa, kun joku on astumassa aukkoon.",
    example: "Mind the step.",
    trap: "Älä kirjoita Look the opening. Look tarvitsee at: look at the opening.",
  }),

  task({
    id: "ele-01",
    fieldId: "electrical",
    skillId: "modals",
    difficulty: 3,
    level: "B1",
    prompt: "Keskus pitää tehdä jännitteettömäksi ja lukita. Mikä ohje on oikea?",
    choices: options(
      ["Isolate the supply and lock it off.", "Erotus ja lukitus kuuluvat yhteen."],
      ["Open the door and start working.", "Ovi auki ei tarkoita jännitteetöntä."],
      ["Turn the light off in the room.", "Huoneen valo ei erota syöttöä."],
      ["Lock the van before you leave.", "Auto ei ole sähkökeskus."],
    ),
    answer: "a",
    rule: "Erotus sanotaan: Isolate the supply and lock it off. Pelkkä valokatkaisin ei riitä.",
    why: "Isolate the supply and lock it off on se lause, jonka toinen sähköasentaja ymmärtää lukitukseksi. Valojen sammuttaminen ei tee piiriä turvalliseksi.",
    example: "Lock off the breaker and keep the key.",
    trap: "Switch off the lights ja isolate the supply ovat eri työvaiheita.",
  }),
  task({
    id: "ele-02",
    fieldId: "electrical",
    skillId: "articles",
    difficulty: 3,
    level: "B1",
    prompt: "Olet mitannut ja johdin on yhä jännitteellinen. Mitä sanot?",
    sentence: "Stop. The circuit is still ___.",
    choices: options(
      ["live", "Live tarkoittaa jännitteellistä."],
      ["life", "Life on elämä."],
      ["alive", "Alive kuvaisi elävää olentoa."],
      ["living", "Living ei ole jännitteen nimi."],
    ),
    answer: "a",
    rule: "Jännitteellinen piiri on live: The circuit is still live.",
    why: "Live on sähkötyön vakiosana. Life kuulostaa samalta suomalaiselle, mutta tarkoittaa elämää. Alive puhuisi ihmisestä tai eläimestä.",
    example: "Treat every cable as live until you have tested it.",
    trap: "Älä kirjoita The circuit is still life.",
  }),
  task({
    id: "ele-03",
    fieldId: "electrical",
    skillId: "quantifiers",
    difficulty: 2,
    level: "A2",
    prompt: "Miten ilmoitat ryhmäkeskuksen jännitteen?",
    sentence: "This board is ___.",
    choices: options(
      ["230 volts", "Luku ja yksikkö, monikossa."],
      ["230 of volt", "Of ei kuulu jännitteeseen."],
      ["a volt 230", "Sanajärjestys on väärin."],
      ["volts the 230", "Artikkeli ei tule näin."],
    ),
    answer: "a",
    rule: "Jännite sanotaan 230 volts. Yksikkö on monikossa, kun luku on yli yksi.",
    why: "230 volts on mittalukema, jonka kollega kirjaa. A volt 230 ei ole englantia, jota keskuksella käytetään.",
    example: "The control voltage is 24 volts.",
    trap: "Älä sano 230 of voltage. Voltage on ilmiö, volts on lukeman yksikkö.",
  }),
  task({
    id: "ele-04",
    fieldId: "electrical",
    skillId: "past",
    difficulty: 3,
    level: "B1",
    prompt: "Vikavirtasuoja laukesi äsken. Miten raportoit sen?",
    choices: options(
      ["The RCD has tripped.", "Laukaisu vaikuttaa yhä, joten perfekti sopii."],
      ["The RCD is tripping yesterday.", "Yesterday ei sovi käynnissä olevaan muotoon."],
      ["The RCD trip.", "Verbistä puuttuu aikamuoto."],
      ["The RCD has trip.", "Perfekti tarvitsee kolmannen muodon tripped."],
    ),
    answer: "a",
    rule: "Kun suoja on lauennut ja tila jatkuu, sano The RCD has tripped.",
    why: "Has tripped kertoo, että laukaisu tapahtui ja piiri on yhä poissa. Is tripping yesterday sekoittaa ajan ja muodon.",
    example: "The breaker has tripped twice this morning.",
    trap: "Suomen 'laukes' ei kerro, onko kyseessä nykyinen tila. Has tripped kertoo.",
  }),
  task({
    id: "ele-05",
    fieldId: "electrical",
    skillId: "modals",
    difficulty: 4,
    level: "B1",
    prompt: "Oppilas aikoo työskennellä jännitteisenä ilman lupaa. Mitä sanot?",
    choices: options(
      ["Do not work live. You do not have a permit.", "Kielto ja syy ovat molemmat selvät."],
      ["Work live quickly, then lock it.", "Jännitetyö ei ole oikotie."],
      ["You must to work live.", "Must ei saa to-sanaa."],
      ["Working live are allowed always.", "Muoto ja sisältö ovat molemmat väärin."],
    ),
    answer: "a",
    rule: "Kielto on suora: Do not work live. Lupa sanotaan erikseen: You do not have a permit.",
    why: "Do not work live on käsky, jonka voi huutaa. Must to work on kieliopillisesti rikki ja sisällöltään vaarallinen.",
    example: "Do not remove the lockout.",
    trap: "Must ei taivu must to. Sama koskee must not.",
  }),
  task({
    id: "ele-06",
    fieldId: "electrical",
    skillId: "word-order",
    difficulty: 2,
    level: "A2",
    prompt: "Kirjoita sääntö, jonka sanot ennen kuin kukaan koskee johtimeen.",
    sentence: "___ before you touch.",
    kind: "cloze",
    choices: [],
    answer: "Test",
    accept: ["test"],
    fill: "Test",
    rule: "Vakiojärjestys on testaa ensin: Test before you touch.",
    why: "Test before you touch on sähkötyön peruslause. Se kieltää arvauksen ja vaatii mittauksen.",
    example: "Test the circuit before you touch it.",
    trap: "Touch before you test on väärä järjestys ja vaarallinen ohje.",
  }),

  task({
    id: "hvac-01",
    fieldId: "hvac",
    skillId: "word-order",
    difficulty: 2,
    level: "A2",
    prompt: "Allaskaapin putki pitää avata. Mitä sanot ensin?",
    choices: options(
      ["Turn the water off first.", "Vesi suljetaan ennen avaamista."],
      ["Open the pipe, then find the valve.", "Järjestys aiheuttaa vuodon."],
      ["Water off turning.", "Ing-muoto ei ole ohje."],
      ["Turn off you the water.", "Sanajärjestys on väärin."],
    ),
    answer: "a",
    rule: "Turn the water off first. Off voi olla myös ennen objektia: Turn off the water.",
    why: "Turn the water off first on asiakkaan luona se lause, joka estää vesivahingon. Open the pipe ensin on väärä työjärjestys.",
    example: "Shut the valve before you disconnect the hose.",
    trap: "First kuuluu loppuun tai alkuun, mutta ei verbin sisään: ei Turn first the water off ilman koko lausetta.",
  }),
  task({
    id: "hvac-02",
    fieldId: "hvac",
    skillId: "prepositions",
    difficulty: 2,
    level: "A2",
    prompt: "Vuoto on allaskaapin alla. Miten paikannat sen?",
    sentence: "There is a leak ___ the sink.",
    choices: options(
      ["under", "Under the sink on kaapin sisällä alapuolella."],
      ["below", "Below voi tarkoittaa alempaa kerrosta."],
      ["on", "On the sink olisi altaan pinnalla."],
      ["at", "At ei kerro, onko vuoto alla vai vieressä."],
    ),
    answer: "a",
    rule: "Allaskaapin vuoto on under the sink. On the sink olisi pesualtaan reunalla.",
    why: "Under the sink on se paikka, johon asentaja kurkkaa. Below the sink voi kuulostaa siltä, että vesi tulee alakerrasta.",
    example: "The drip is under the bath.",
    trap: "Suomen 'alla' ei aina ole below. Kalusteen alla on under.",
  }),
  task({
    id: "hvac-03",
    fieldId: "hvac",
    skillId: "comparison",
    difficulty: 3,
    level: "B1",
    prompt: "Kattilan painemittari on punaisella. Mitä ilmoitat?",
    choices: options(
      ["The boiler pressure is too high.", "Too high on selvä vikailmoitus."],
      ["The boiler pressure is too highly.", "Highly on tapa, ei mitta."],
      ["The boiler is high pressure too much.", "Sanajärjestys hajoaa."],
      ["Pressure high is the boiler.", "Lause on käännetty sanasta sanaan."],
    ),
    answer: "a",
    rule: "Liikaa on too + adjektiivi: too high, too low, too hot.",
    why: "The boiler pressure is too high on lause, jonka päivystäjä ymmärtää. Highly kuvaisi tekemisen tapaa, ei mittaria.",
    example: "The flow temperature is too low.",
    trap: "Too much high ei ole englantia. Sano too high.",
  }),
  task({
    id: "hvac-04",
    fieldId: "hvac",
    skillId: "future",
    difficulty: 2,
    level: "A2",
    prompt: "Osaa puuttuu ja tulette huomenna aamulla. Mitä sanot asiakkaalle?",
    choices: options(
      ["We will be back tomorrow morning.", "Will sopii sovittuun paluuseen."],
      ["We back tomorrow.", "Verbistä puuttuu apuverbi."],
      ["We are back yesterday morning.", "Yesterday ei ole tulevaisuutta."],
      ["We will to be back.", "Will ei saa to-sanaa."],
    ),
    answer: "a",
    rule: "Sovittu paluu asiakkaalle: We will be back tomorrow morning.",
    why: "Will be back on lupaus. We back tomorrow on muistilappu, ei lause, jonka asiakas kuulee selvästi.",
    example: "I will call you when the part arrives.",
    trap: "Will ei taivu will to. Sama virhe kuin must to.",
  }),
  task({
    id: "hvac-05",
    fieldId: "hvac",
    skillId: "present",
    difficulty: 2,
    level: "A2",
    prompt: "Patteri ei lämpene, koska se pitää ilmata. Miten ohjeat?",
    choices: options(
      ["Bleed the radiator.", "Bleed on ilmata patteri."],
      ["Blood the radiator.", "Blood on veri."],
      ["Blow the radiator away.", "Away veisi patterin pois."],
      ["Bleed a radiator the.", "Artikkeli on väärässä paikassa."],
    ),
    answer: "a",
    rule: "Patterin ilmaus on bleed the radiator. Blood on eri sana.",
    why: "Bleed the radiator on talotekniikan vakio-ohje. Blood kuulostaa samalta, mutta tarkoittaa verta.",
    example: "Bleed the radiator until water comes out.",
    trap: "Älä kirjoita blood, kun työkalu on ilmausavain.",
  }),
  task({
    id: "hvac-06",
    fieldId: "hvac",
    skillId: "word-order",
    difficulty: 2,
    level: "A2",
    prompt: "Kirjoita ohje: sulje vesi ensin.",
    sentence: "___ the water off first.",
    kind: "cloze",
    choices: [],
    answer: "Turn",
    accept: ["turn", "Shut", "shut", "Switch", "switch"],
    fill: "Turn",
    rule: "Sulkemiskäsky alkaa verbillä: Turn the water off first.",
    why: "Turn the water off first on lyhyt ja yksiselitteinen. First lopussa korostaa järjestystä.",
    example: "Turn the pump off first.",
    trap: "Water turn off ei ole käsky.",
  }),

  task({
    id: "sur-01",
    fieldId: "surface",
    skillId: "word-order",
    difficulty: 2,
    level: "A2",
    prompt: "Huoneessa aiotaan ruiskumaalata. Mitä sanot ennen kuin kompressori käynnistyy?",
    choices: options(
      ["Ventilate the room before you spray.", "Tuuletus on ennen ruiskutusta."],
      ["Spray first and open the window later.", "Liuotinhöyry ehtii jäädä huoneeseen."],
      ["Ventilating the room.", "Ei ole täysi ohje."],
      ["The room ventilates you.", "Tekijä on väärin."],
    ),
    answer: "a",
    rule: "Ennen ruiskutusta: Ventilate the room before you spray.",
    why: "Before you spray pitää tuuletuksen ensimmäisenä. Later on liian myöhään, kun sumu on jo ilmassa.",
    example: "Open the windows before you use the solvent.",
    trap: "Before ja after vaihtavat työjärjestyksen. Pintakäsittelyssä järjestys on turvallisuus.",
  }),
  task({
    id: "sur-02",
    fieldId: "surface",
    skillId: "quantifiers",
    difficulty: 2,
    level: "A2",
    prompt: "Työselostus vaatii kaksi maalikerrosta. Miten sen sanot?",
    choices: options(
      ["Apply two coats.", "Coat on maalikerros."],
      ["Apply two jackets.", "Jacket on takki."],
      ["Apply two coat.", "Kahden jälkeen monikko."],
      ["Apply a coats.", "A ja monikko eivät sovi yhteen."],
    ),
    answer: "a",
    rule: "Maalikerros on a coat. Kaksi kerrosta on two coats.",
    why: "Apply two coats on työselostuksen kieli. Jacket on vaate, eikä sitä levitetä seinään.",
    example: "Let the first coat dry.",
    trap: "Älä käännä kerrosta sanalla layer joka kerta. Maalissa vakiintunut sana on coat.",
  }),
  task({
    id: "sur-03",
    fieldId: "surface",
    skillId: "modals",
    difficulty: 3,
    level: "B1",
    prompt: "Pohja on yhä kostea. Mitä sanot ennen pohjamaalia?",
    choices: options(
      ["The substrate must be dry.", "Must be kertoo ehdon."],
      ["The substrate must dry be.", "Sanajärjestys on väärin."],
      ["The substrate must to be dry.", "Must ei saa to-sanaa."],
      ["Dry is maybe the substrate.", "Ehkä ei riitä pohjatöissä."],
    ),
    answer: "a",
    rule: "Pohjan ehto on must be: The substrate must be dry.",
    why: "Must be dry on ehdoton. Must to be on yleinen suomalainen virhe, koska suomessa verbi taipuu toisin.",
    example: "The surface must be clean and dry.",
    trap: "Mustin jälkeen ei tule to.",
  }),
  task({
    id: "sur-04",
    fieldId: "surface",
    skillId: "prepositions",
    difficulty: 2,
    level: "A2",
    prompt: "Miten ohjeistat hionnan kahden kerroksen välissä?",
    choices: options(
      ["Sand between coats.", "Between on kahden kerroksen välissä."],
      ["Sand among coats.", "Among on joukossa, ei kahden välissä."],
      ["Sand under coats.", "Under olisi kerrosten alla."],
      ["Sand besides coats.", "Besides tarkoittaa lisäksi."],
    ),
    answer: "a",
    rule: "Kahden kerroksen välissä on between coats.",
    why: "Sand between coats on lyhyt työohje. Among sopisi useaan epämääräiseen joukkoon, ei tähän väliin.",
    example: "Wait between coats.",
    trap: "Besides tarkoittaa 'sen lisäksi', ei 'vieressä'. Vieressä olisi beside.",
  }),
  task({
    id: "sur-05",
    fieldId: "surface",
    skillId: "articles",
    difficulty: 3,
    level: "B1",
    prompt: "Ruiskumaalari ei ole laittanut hengityssuojainta. Mitä sanot?",
    choices: options(
      ["Put the respirator on.", "Juuri tämä suojain, joka kuuluu työhön."],
      ["Put a respirator the on.", "Artikkeli on väärässä paikassa."],
      ["Put respirator.", "Esine jää ilman ratkaisua, kuulostaako se yleiseltä vai tältä."],
      ["Put on respirators many.", "Monikko ja sanajärjestys ovat pielessä."],
    ),
    answer: "a",
    rule: "Kun suojain on työn vaatima varuste, sano Put the respirator on.",
    why: "The respirator tarkoittaa sitä suojainta, joka tälle työlle kuuluu. Pelkkä Put respirator on keskeneräinen käsky.",
    example: "Wear the mask in the spray booth.",
    trap: "Suomeksi 'maski päälle' ei näytä artikkelia. Englannissa the tai your tarvitaan.",
  }),
  task({
    id: "sur-06",
    fieldId: "surface",
    skillId: "word-order",
    difficulty: 2,
    level: "A2",
    prompt: "Kirjoita ohje kerrosten välisestä hionnasta.",
    sentence: "Sand ___ coats.",
    kind: "cloze",
    choices: [],
    answer: "between",
    accept: ["between"],
    fill: "between",
    rule: "Kerrosten väli on between coats.",
    why: "Sand between coats on se fraasi, joka työselostukseen kirjoitetaan. Between ei taivu eikä saa monikkoa.",
    example: "Dust off between coats.",
    trap: "Älä kirjoita between the each coats.",
  }),

  task({
    id: "prop-01",
    fieldId: "property",
    skillId: "present",
    difficulty: 2,
    level: "A2",
    prompt: "Asukas soittaa: keittiössä tippuu vettä. Miten kirjaat vian?",
    choices: options(
      ["The tenant reports a leak.", "Tenant on vuokralainen, leak on vuoto."],
      ["The tenet reports a leak.", "Tenet ei ole asukas."],
      ["The tenant report a leak.", "He-muodosta puuttuu -s."],
      ["The tenant reports a lake.", "Lake on järvi."],
    ),
    answer: "a",
    rule: "Vikailmoitus: The tenant reports a leak. Yksikön he-muodossa verbi saa -s.",
    why: "Reports on oikea preesens. Report ilman -s-päätettä on perusmuoto, ei tämä lause. Lake ja leak eroavat yhdellä kirjaimella.",
    example: "The tenant reports a cold radiator.",
    trap: "Suomen 'ilmoittaa' ei näytä -s-päätettä. Englannissa he/she/it reports.",
  }),
  task({
    id: "prop-02",
    fieldId: "property",
    skillId: "future",
    difficulty: 2,
    level: "A2",
    prompt: "Menet asuntoon korjaamaan lukkoa. Miten sovit käynnin?",
    choices: options(
      ["I will call before I come in.", "Ensin soitto, sitten sisään."],
      ["I come in and call after.", "Jälkikäteen soitto ei ole lupa."],
      ["I will to call before.", "Will ei saa to-sanaa."],
      ["I called before I come in.", "Menneen ja nykyisen sekoitus on epäselvä."],
    ),
    answer: "a",
    rule: "Asuntoon mennään sopien: I will call before I come in.",
    why: "Will call before I come in on lupaus, jonka asukas ymmärtää. After tekisi käynnistä yllätyksen.",
    example: "I will text you when I am downstairs.",
    trap: "Before I come in ei ole sama kuin after I come in.",
  }),
  task({
    id: "prop-03",
    fieldId: "property",
    skillId: "present",
    difficulty: 1,
    level: "A2",
    prompt: "Patteri ei lämpene. Miten kuvaat vian lyhyesti?",
    choices: options(
      ["The radiator is cold.", "Cold kuvaa patterin tilan."],
      ["The radiator is coldly.", "Coldly on tapa, ei lämpötila."],
      ["The radiator colds.", "Cold ei ole verbi tässä."],
      ["Cold is radiator the.", "Sanajärjestys on väärin."],
    ),
    answer: "a",
    rule: "Vian tila on adjektiivi: The radiator is cold.",
    why: "Is cold on selvä ilmoitus kiinteistöhuollolle. Coldly kuvaisi tekemistä kylmästi, ei patteria.",
    example: "The tap is dripping.",
    trap: "Älä taivuta adjektiivia verbin näköiseksi: ei colds.",
  }),
  task({
    id: "prop-04",
    fieldId: "property",
    skillId: "modals",
    difficulty: 3,
    level: "B1",
    prompt: "Piha on jäinen. Mitä kirjaat aamun kierrokselle?",
    choices: options(
      ["The path needs gritting.", "Needs + ing kertoo tarvittavan työn."],
      ["The path needs grit.", "Grit yksin ei kerro työtä yhtä selvästi."],
      ["The path is needing a grit.", "Tarve ei ole käynnissä oleva toiminta."],
      ["Path need gritting.", "Artikkeli ja verbi puuttuvat."],
    ),
    answer: "a",
    rule: "Tarvittava työ sanotaan needs + -ing: The path needs gritting.",
    why: "Needs gritting tarkoittaa, että hiekoitus pitää tehdä. Is needing kuulostaa siltä, että piha parhaillaan haluaa jotain.",
    example: "The lock needs replacing.",
    trap: "Suomen 'pitää hiekoittaa' ei ole is needing. Se on needs gritting.",
  }),
  task({
    id: "prop-05",
    fieldId: "property",
    skillId: "articles",
    difficulty: 2,
    level: "A2",
    prompt: "Raportoit yhden tietyn asunnon vuodon. Mikä on luontevin?",
    sentence: "There is a leak in ___.",
    choices: options(
      ["flat 4", "Asunnon numero yksilöi paikan."],
      ["the flats", "Monikko veisi kaikkiin asuntoihin."],
      ["a building somewhere", "Liian epämääräinen huoltokirjaan."],
      ["flat the 4", "Artikkeli on väärässä paikassa."],
    ),
    answer: "a",
    rule: "Huoneiston numero riittää: in flat 4. The ei ole pakollinen numeron edessä.",
    why: "Flat 4 on täsmällinen. The flats tarkoittaisi talon kaikkia asuntoja, eikä huoltomies tietäisi mihin mennä.",
    example: "The stair light on floor 2 is out.",
    trap: "Somewhere ei kelpaa vikailmoitukseen.",
  }),
  task({
    id: "prop-06",
    fieldId: "property",
    skillId: "present",
    difficulty: 1,
    level: "A2",
    prompt: "Kirjoita vika: patteri on kylmä.",
    sentence: "The radiator ___ cold.",
    kind: "cloze",
    choices: [],
    answer: "is",
    accept: ["is"],
    fill: "is",
    rule: "Tila kuvataan verbillä be: The radiator is cold.",
    why: "Is cold on lyhin oikea ilmoitus. Pelkkä radiator cold ei ole lause, jonka järjestelmä tai kollega kirjaa.",
    example: "The corridor light is out.",
    trap: "Älä kirjoita The radiator are cold. Radiator on yksikkö.",
  }),

  task({
    id: "aut-01",
    fieldId: "automotive",
    skillId: "present",
    difficulty: 2,
    level: "A2",
    prompt: "Asiakas kysyy, miksi auto ei läpäise jarrutarkistusta. Mitä sanot?",
    choices: options(
      ["The front brake pads are worn.", "Worn tarkoittaa kulunutta."],
      ["The front brake pads are wore.", "Wore on menneen ajan muoto, ei tila."],
      ["The front brake pads are wear.", "Wear ei ole adjektiivi."],
      ["Front brakes pad is worn.", "Monikko ja yksikkö eivät täsmää."],
    ),
    answer: "a",
    rule: "Kulunut osa on worn: The front brake pads are worn.",
    why: "Are worn kuvaa nykyistä kuntoa. Wore kertoisi menneestä tapahtumasta, ei siitä, mitä asiakas näkee nyt.",
    example: "The rear tyres are worn on the inside.",
    trap: "Wear, wore ja worn sekoittuvat. Kunnon kuvaukseen tarvitaan worn.",
  }),
  task({
    id: "aut-02",
    fieldId: "automotive",
    skillId: "modals",
    difficulty: 3,
    level: "B1",
    prompt: "Jarruneste on vähissä ja poljin painuu pohjaan. Mitä sanot asiakkaalle?",
    choices: options(
      ["Do not drive it like this.", "Kielto on ehdoton."],
      ["You can drive if you are careful.", "Varovaisuus ei korjaa jarruja."],
      ["Drive it to the shop tomorrow maybe.", "Maybe ei sovi, kun jarru pettää."],
      ["Do not to drive it.", "Do not ei saa to-sanaa."],
    ),
    answer: "a",
    rule: "Vaarallisesta ajokista sanotaan Do not drive it like this.",
    why: "Like this viittaa juuri tähän kuntoon. Careful ei tee jarrunestevajausta turvalliseksi, eikä Do not to ole englantia.",
    example: "Do not drive it. The brake pedal goes to the floor.",
    trap: "Älä pehmennä turvallisuusasiaa sanalla maybe.",
  }),
  task({
    id: "aut-03",
    fieldId: "automotive",
    skillId: "past",
    difficulty: 2,
    level: "A2",
    prompt: "Asiakas kertoo, että varoitusvalo syttyi moottoritiellä. Miten kirjaat sen?",
    choices: options(
      ["The warning light came on.", "Come on, came on on syttyä."],
      ["The warning light came in.", "In ei ole valon syttyminen."],
      ["The warning light has come on yesterday.", "Yesterday ei sovi perfektiin."],
      ["The warning light come on.", "Aikamuoto puuttuu."],
    ),
    answer: "a",
    rule: "Varoitusvalo syttyi: The warning light came on.",
    why: "Came on on mennyttä aikaa, koska syttyminen tapahtui matkalla. Has come on yesterday on kieliopillisesti rikki.",
    example: "The oil light came on at 80 km/h.",
    trap: "Come in on tulla sisään. Valo tulee on: come on.",
  }),
  task({
    id: "aut-04",
    fieldId: "automotive",
    skillId: "articles",
    difficulty: 2,
    level: "A2",
    prompt: "Rengaspaine on matala. Miten sanot sen brittienglanniksi?",
    choices: options(
      ["The tyre pressure is low.", "Tyre on brittiläinen rengas."],
      ["The tired pressure is low.", "Tired on väsynyt."],
      ["Tyre pressure are low.", "Pressure on yksikkö."],
      ["A tyre pressure is low.", "A tekisi siitä yhden satunnaisen paineen."],
    ),
    answer: "a",
    rule: "Brittienglannissa rengas on tyre. Paine on the tyre pressure.",
    why: "The tyre pressure is low on huollon lause. Tired kuulostaa läheltä, mutta tarkoittaa väsynyttä.",
    example: "The offside rear tyre is flat.",
    trap: "Tire on amerikanenglannin rengas. Tällä sivustolla linja on tyre.",
  }),
  task({
    id: "aut-05",
    fieldId: "automotive",
    skillId: "prepositions",
    difficulty: 3,
    level: "B1",
    prompt: "Kuluma on renkaan sisäreunassa. Miten paikannat sen?",
    sentence: "The tyre is worn ___ the inside.",
    choices: options(
      ["on", "Kuluma on pinnalla: on the inside."],
      ["in", "In the inside on kömpelö toisto."],
      ["at", "At ei kuvaa kulutuspintaa."],
      ["to", "To on suunta, ei paikka."],
    ),
    answer: "a",
    rule: "Kulutuspinnan paikka on on the inside tai on the outside.",
    why: "Worn on the inside on katsastuksen ja rengasliikkeen fraasi. Se kertoo aurauksen tai kulman viasta.",
    example: "The pads are worn on one side.",
    trap: "Suomen 'sisäpuolelta' houkuttelee sanaan from. Kuluma ilmoitetaan on the inside.",
  }),
  task({
    id: "aut-06",
    fieldId: "automotive",
    skillId: "present",
    difficulty: 2,
    level: "A2",
    prompt: "Kirjoita asiakkaalle: etujarrupalat ovat kuluneet.",
    sentence: "The front brake pads ___ worn.",
    kind: "cloze",
    choices: [],
    answer: "are",
    accept: ["are"],
    fill: "are",
    rule: "Monikko pads saa are: The front brake pads are worn.",
    why: "Are worn on kunnon kuvaus. Is worn sopisi yhteen palaseen, ei molempiin etupaloihin.",
    example: "The rear pads are worn too.",
    trap: "Pads on monikko. Älä kirjoita pads is.",
  }),

  task({
    id: "mac-01",
    fieldId: "machining",
    skillId: "word-order",
    difficulty: 2,
    level: "A2",
    prompt: "Kappale pitää mitata kesken ajon. Mitä sanot?",
    choices: options(
      ["Stop the machine before you measure.", "Kone seisoo ennen mittaa."],
      ["Measure while the spindle is running.", "Pyörivä kara ja mitta on vaarallinen."],
      ["Stopping the machine.", "Ei ole täysi käsky."],
      ["You measuring after never.", "Sanajärjestys ei ole ohje."],
    ),
    answer: "a",
    rule: "Ennen mittausta kone seisoo: Stop the machine before you measure.",
    why: "Before you measure pitää järjestyksen. While the spindle is running on juuri se tilanne, jota koneistamossa ei sallita.",
    example: "Stop the spindle before you open the door.",
    trap: "While ja before eivät ole sama työjärjestys.",
  }),
  task({
    id: "mac-02",
    fieldId: "machining",
    skillId: "quantifiers",
    difficulty: 4,
    level: "B1",
    prompt: "Toleranssi on 0,05 mm. Miten sen sanot ääneen?",
    choices: options(
      ["The tolerance is five hundredths of a millimetre.", "Desimaali sanotaan hundredths."],
      ["The tolerance is five hundreds of a millimetre.", "Hundreds on satoja kappaleita."],
      ["The tolerance is 0,05 millimetre.", "Pilkku ei ole englannin desimaali."],
      ["The tolerance are five hundredth.", "Yksikkö ja monikko eivät täsmää."],
    ),
    answer: "a",
    rule: "0.05 on five hundredths. Englannin desimaalimerkki on piste, ei pilkku.",
    why: "Five hundredths of a millimetre on se, mitä mittavälineen vieressä sanotaan. Hundreds tarkoittaisi satoja, ja pilkku 0,05 ei ole brittiläinen desimaali.",
    example: "The limit is two tenths of a millimetre.",
    trap: "Suomalainen desimaalipilkku kirjoitetaan englannissa pisteeksi: 0.05.",
  }),
  task({
    id: "mac-03",
    fieldId: "machining",
    skillId: "modals",
    difficulty: 2,
    level: "A2",
    prompt: "Suoja on tiellä ja kone käy. Mitä sanot?",
    choices: options(
      ["Do not remove the guard.", "Suoja pysyy paikallaan."],
      ["Remove the guard so you can see better.", "Näkyvyys ei ohita suojaa."],
      ["Do not to remove the guard.", "Do not ei saa to-sanaa."],
      ["The guard removes you.", "Tekijä on väärin."],
    ),
    answer: "a",
    rule: "Kielto on Do not remove the guard.",
    why: "Do not remove the guard on ehdoton. So you can see better on tyypillinen huono perustelu, jota ei hyväksytä.",
    example: "Keep the guard closed.",
    trap: "Do not to on kaksoisvirhe: sekä kielioppi että lupaus, jota ei ole.",
  }),
  task({
    id: "mac-04",
    fieldId: "machining",
    skillId: "present",
    difficulty: 3,
    level: "B1",
    prompt: "Kappale ei ole mitassa. Miten ilmoitat sen?",
    choices: options(
      ["The part is out of tolerance.", "Out of tolerance on hylkäys."],
      ["The part is out of order.", "Out of order tarkoittaa rikkinäistä konetta."],
      ["The part is out tolerance.", "Of puuttuu."],
      ["The part out of tolerance is.", "Sana be on väärässä paikassa."],
    ),
    answer: "a",
    rule: "Hylätty mitta on out of tolerance. Rikkinäinen kone on out of order.",
    why: "Out of tolerance kertoo laadun. Out of order veisi ilmoituksen kunnossapidolle, vaikka vika on kappaleessa.",
    example: "This bore is out of tolerance.",
    trap: "Of ei saa jäädä pois: ei out tolerance.",
  }),
  task({
    id: "mac-05",
    fieldId: "machining",
    skillId: "articles",
    difficulty: 2,
    level: "A2",
    prompt: "Terä on tylsä. Miten sanot sen?",
    choices: options(
      ["The tool is blunt.", "Blunt on tylsä terä."],
      ["The tool is blonde.", "Blonde on vaalea tukka."],
      ["Tool is a blunt.", "Artikkelit ovat väärin päin."],
      ["The tool blunts.", "Verbi kuulostaisi tapahtumalta, ei tilalta."],
    ),
    answer: "a",
    rule: "Tylsä terä on blunt: The tool is blunt.",
    why: "Blunt on koneistamon sana. Blonde on hiusväri, ja ne näyttävät suomalaiselle läheisiltä vain hetken.",
    example: "Change the insert. This one is blunt.",
    trap: "Älä sano dull, jos ohje tai mestari käyttää sanaa blunt. Molemmat voivat esiintyä, mutta blunt on terän vakiosana.",
  }),
  task({
    id: "mac-06",
    fieldId: "machining",
    skillId: "word-order",
    difficulty: 2,
    level: "A2",
    prompt: "Kirjoita käsky: pysäytä kone ennen mittausta.",
    sentence: "___ the machine before you measure.",
    kind: "cloze",
    choices: [],
    answer: "Stop",
    accept: ["stop"],
    fill: "Stop",
    rule: "Käsky alkaa verbillä: Stop the machine before you measure.",
    why: "Stop the machine before you measure on se lappu, joka kuuluu koneen viereen. Before pitää mittauksen toisena.",
    example: "Stop the feed before you open the guard.",
    trap: "Machine stop ei ole käsky.",
  }),

  task({
    id: "prc-01",
    fieldId: "process",
    skillId: "present",
    difficulty: 3,
    level: "B1",
    prompt: "Paine nousee. Mitä sanot heti?",
    choices: options(
      ["The pressure is rising. Close the inlet valve.", "Tila ja toimenpide ovat molemmat selvät."],
      ["The pressure rose yesterday. Open the valve.", "Eilinen nousu ja venttiilin avaus ovat väärä vaste."],
      ["Pressure rising close.", "Lauseet ovat jääneet sanoiksi."],
      ["The pressure is raising. Close the inlet valve.", "Raise on nostaa jotain, rise on nousta."],
    ),
    answer: "a",
    rule: "Paine nousee itsestään: The pressure is rising. Raise olisi, että joku nostaa sitä.",
    why: "Is rising kertoo käynnissä olevan muutoksen. Raising tarkoittaisi, että joku nostaa painetta tarkoituksella. Venttiili suljetaan, ei avata.",
    example: "The temperature is rising. Reduce the feed.",
    trap: "Rise, rose, risen on nousta. Raise, raised, raised on nostaa.",
  }),
  task({
    id: "prc-02",
    fieldId: "process",
    skillId: "present",
    difficulty: 2,
    level: "A2",
    prompt: "Pumppu ei ole käytössä. Miten ilmoitat sen vuoronvaihdossa?",
    choices: options(
      ["The pump is down.", "Down on pois käytöstä."],
      ["The pump is downed.", "Down ei taivu noin."],
      ["The pump is downstairs.", "Downstairs on alemmassa kerroksessa."],
      ["Pump down is.", "Sanajärjestys on väärin."],
    ),
    answer: "a",
    rule: "Kone pois käytöstä: The pump is down.",
    why: "Is down on vuoronvaihdon vakioilmaus. Downstairs veisi pumpun kellariin, vaikka se on vain seis.",
    example: "Line two is down.",
    trap: "Downed ei ole tämän fraasin muoto.",
  }),
  task({
    id: "prc-03",
    fieldId: "process",
    skillId: "word-order",
    difficulty: 3,
    level: "B1",
    prompt: "Kemikaalia on lattialla. Mikä ohje on oikea?",
    choices: options(
      ["Contain the spill and call the supervisor.", "Ensin rajaus, sitten kutsu."],
      ["Wash the spill into the drain.", "Viemäri ei ole keräysastia."],
      ["Contain the spell and call.", "Spell on kirjoitusasu."],
      ["Call the supervisor after the shift.", "Vuoron jälkeen on liian myöhään."],
    ),
    answer: "a",
    rule: "Vuoto rajataan heti: Contain the spill and call the supervisor.",
    why: "Spill on valunut aine. Spell on oikeinkirjoitus. Viemäriin huuhtominen levittää vahingon.",
    example: "Contain the spill with absorbent mats.",
    trap: "Spill ja spell näyttävät samalta kiireessä. Hälytystekstissä kirjain on i.",
  }),
  task({
    id: "prc-04",
    fieldId: "process",
    skillId: "modals",
    difficulty: 4,
    level: "B2",
    prompt: "Hälytys soi ja joku aikoo kuitata sen ohitse. Mitä sanot?",
    choices: options(
      ["Do not bypass the alarm.", "Ohitus on kielletty."],
      ["Bypass it so the noise stops.", "Melu ei ole syy ohittaa suojausta."],
      ["You must to bypass the alarm.", "Must ei saa to-sanaa, ja sisältö on väärä."],
      ["The alarm bypasses you.", "Tekijä on väärin."],
    ),
    answer: "a",
    rule: "Suojausta ei ohiteta: Do not bypass the alarm.",
    why: "Bypass on prosessityön vaarallinen verbi. Do not bypass the alarm on se kielto, joka jää pöytäkirjaan.",
    example: "Do not reset the trip until you know the cause.",
    trap: "So the noise stops on huono syy. Hälytys soi, koska jokin on vialla.",
  }),
  task({
    id: "prc-05",
    fieldId: "process",
    skillId: "past",
    difficulty: 3,
    level: "B1",
    prompt: "Kirjaat vuoronvaihtoon, että venttiili suljettiin kello 6. Mikä on selvin?",
    choices: options(
      ["We closed the inlet valve at six.", "Mennyt aika sopii päättyneeseen tekoon."],
      ["We have closed the inlet valve at six.", "Kellonaika at six ei sovi perfektiin."],
      ["We close the inlet valve at six.", "Preesens kuulostaa joka päivän rutiinilta."],
      ["We closing the inlet valve at six.", "Ing-muoto ei ole mennyttä."],
    ),
    answer: "a",
    rule: "Päättynyt teko kellonajalla on menneessä ajassa: We closed the inlet valve at six.",
    why: "At six rajaa tapahtuman menneisyyteen, joten closed on oikein. Have closed at six on suomalaisille tuttu mutta tässä väärä yhdistelmä.",
    example: "The pump stopped at 14:10.",
    trap: "Perfekti ei kerro kellonaikaa sanalla at. Silloin käytetään past simpleä.",
  }),
  task({
    id: "prc-06",
    fieldId: "process",
    skillId: "word-order",
    difficulty: 2,
    level: "A2",
    prompt: "Kirjoita käsky: sulje tuloventtiili.",
    sentence: "___ the inlet valve.",
    kind: "cloze",
    choices: [],
    answer: "Close",
    accept: ["close", "Shut", "shut"],
    fill: "Close",
    rule: "Venttiilikäsky on Close the inlet valve.",
    why: "Close the inlet valve on yksiselitteinen. Inlet kertoo, mikä venttiili, the yksilöi sen.",
    example: "Open the bypass valve slowly.",
    trap: "Valve close ei ole käsky.",
  }),
];
